package io.axiam.sdk.reactor;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.io.InputStream;
import java.util.HexFormat;
import java.util.UUID;

/**
 * Loader for the CONTRACT.md &sect;22.13 reference vectors
 * ({@code crates/axiam-amqp/tests/fixtures/reactor_v2_reference_vectors.json},
 * copied verbatim onto this module's test classpath).
 *
 * <p>The vectors were generated by the AXIAM server's own reactor sign path and
 * ship beside the &sect;8 vectors under the <strong>same</strong> master key,
 * tenant and derived subkey — which is why this loader is shaped exactly like
 * {@code V2ReferenceVectorHmacTest}'s: one loader serves both, and the only
 * difference between the two message families ({@code hmac_signature} present
 * and {@code null} here, absent there) is a test rather than a paragraph to
 * remember.
 *
 * <p><strong>Fixture-reading note, inherited from the &sect;8 loader:</strong>
 * a vector's {@code message} object is a convenience rendering with
 * alphabetically sorted keys and must never be fed to a verifier directly. The
 * one authoritative field for wire order is {@code canonical_signed_json}, whose
 * key order as written in the fixture text <em>is</em> the declared field order.
 * Every helper below builds its wire body from that string.
 */
final class ReactorVectors {

    static final ObjectMapper MAPPER = new ObjectMapper();

    private static final String FIXTURE_PATH = "/reactor_v2_reference_vectors.json";

    private ReactorVectors() {
    }

    static JsonNode load() throws Exception {
        try (InputStream in = ReactorVectors.class.getResourceAsStream(FIXTURE_PATH)) {
            if (in == null) {
                throw new IllegalStateException("fixture not found on classpath: " + FIXTURE_PATH);
            }
            return MAPPER.readTree(in);
        }
    }

    /** The HKDF-derived per-tenant AMQP subkey both directions sign with. */
    static byte[] subkey(JsonNode root) {
        return HexFormat.of().parseHex(root.get("hkdf").get("derived_subkey_hex").asText());
    }

    static UUID tenantId(JsonNode root) {
        return UUID.fromString(root.get("tenant_id").asText());
    }

    static UUID correlationId(JsonNode root) {
        return UUID.fromString(root.get("expected_correlation_id").asText());
    }

    /**
     * Reconstructs the signed wire body for {@code vector}: the canonical bytes
     * with {@code hmac_signature} carrying the committed hex instead of
     * {@code null}. Re-putting an existing key keeps its position, so the field
     * stays exactly where the server wrote it.
     */
    static byte[] wireBody(JsonNode vector) throws Exception {
        ObjectNode node = canonicalNode(vector);
        node.put("hmac_signature", vector.get("hmac_signature_hex").asText());
        return MAPPER.writeValueAsBytes(node);
    }

    /** The canonical (signed-over) tree: {@code hmac_signature} present and null. */
    static ObjectNode canonicalNode(JsonNode vector) throws Exception {
        return (ObjectNode) MAPPER.readTree(vector.get("canonical_signed_json").asText());
    }
}
