// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.axiam.sdk.errors.NetworkError;
import io.axiam.sdk.internal.ManagementTransport;
import io.axiam.sdk.management.models.ActorType;
import io.axiam.sdk.management.models.AttestationMode;
import io.axiam.sdk.management.models.AttributeSource;
import io.axiam.sdk.management.models.AuditOutcome;
import io.axiam.sdk.management.models.AuthnRequestParamsMode;
import io.axiam.sdk.management.models.CertificateStatus;
import io.axiam.sdk.management.models.CertificateType;
import io.axiam.sdk.management.models.CertificationLevel;
import io.axiam.sdk.management.models.CibaDeliveryMode;
import io.axiam.sdk.management.models.CibaRequestSigningAlg;
import io.axiam.sdk.management.models.ClientAuthMethod;
import io.axiam.sdk.management.models.ClientProfile;
import io.axiam.sdk.management.models.DeprovisionPolicy;
import io.axiam.sdk.management.models.DirectoryKind;
import io.axiam.sdk.management.models.FailurePolicy;
import io.axiam.sdk.management.models.KeyAlgorithm;
import io.axiam.sdk.management.models.ManagedBy;
import io.axiam.sdk.management.models.MfaMethodType;
import io.axiam.sdk.management.models.NameIdFormat;
import io.axiam.sdk.management.models.NotificationEventType;
import io.axiam.sdk.management.models.PermissionEffect;
import io.axiam.sdk.management.models.PgpKeyAlgorithm;
import io.axiam.sdk.management.models.PgpKeyPurpose;
import io.axiam.sdk.management.models.PgpKeyStatus;
import io.axiam.sdk.management.models.ReactorMode;
import io.axiam.sdk.management.models.SamlBinding;
import io.axiam.sdk.management.models.SamlIdpCredentialStatus;
import io.axiam.sdk.management.models.SamlIdpSlot;
import io.axiam.sdk.management.models.ScimTargetAuth;
import io.axiam.sdk.management.models.ScimTargetAuthUnknown;
import io.axiam.sdk.management.models.ScimTargetScope;
import io.axiam.sdk.management.models.ScimTargetScopeUnknown;
import io.axiam.sdk.management.models.ScimTokenStatus;
import io.axiam.sdk.management.models.SettingsScope;
import io.axiam.sdk.management.models.SsfDeliveryMethod;
import io.axiam.sdk.management.models.SsfEventType;
import io.axiam.sdk.management.models.SsfStatusActor;
import io.axiam.sdk.management.models.SsfStreamStatus;
import io.axiam.sdk.management.models.SsfSubjectFormat;
import io.axiam.sdk.management.models.TenantKind;
import io.axiam.sdk.management.models.TenantStatus;
import io.axiam.sdk.management.models.UnknownAaguidAction;
import io.axiam.sdk.management.models.UserNameSource;
import io.axiam.sdk.management.models.UserStatus;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Generated open-set conformance: a value this SDK does not know decodes, and is never sent.
 *
 * <p>CONTRACT §27.11 rule 1 for every string enum on the surface, and §31.2 for the tagged unions
 * whose tag is an open set. Decoding goes through {&#64;link ManagementTransport#reader()},
 * encoding through {&#64;link ManagementTransport#encodeBody}, the two the SDK actually uses.
 */
class ManagementOpenValuesGeneratedTest {

    /** The reader every management response is decoded with. */
    private static final ObjectMapper JSON = ManagementTransport.reader();

    /** No server sends this spelling, for any field. */
    private static final String UNLISTED = "\"not-a-value-the-spec-lists\"";

    /** §27.11 rule 1 for ActorType. */
    @Test
    void actorTypeIsOpen() throws Exception {
        assertEquals(ActorType.USER, JSON.readValue("\"User\"", ActorType.class));
        assertEquals(ActorType.UNKNOWN, JSON.readValue(UNLISTED, ActorType.class));
    }

    /** §27.11 rule 1 for AttestationMode. */
    @Test
    void attestationModeIsOpen() throws Exception {
        assertEquals(AttestationMode.NONE, JSON.readValue("\"none\"", AttestationMode.class));
        assertEquals(AttestationMode.UNKNOWN, JSON.readValue(UNLISTED, AttestationMode.class));
    }

    /** §27.11 rule 1 for AttributeSource. */
    @Test
    void attributeSourceIsOpen() throws Exception {
        assertEquals(AttributeSource.USERNAME, JSON.readValue("\"username\"", AttributeSource.class));
        assertEquals(AttributeSource.UNKNOWN, JSON.readValue(UNLISTED, AttributeSource.class));
    }

    /** §27.11 rule 1 for AuditOutcome. */
    @Test
    void auditOutcomeIsOpen() throws Exception {
        assertEquals(AuditOutcome.SUCCESS, JSON.readValue("\"Success\"", AuditOutcome.class));
        assertEquals(AuditOutcome.UNKNOWN, JSON.readValue(UNLISTED, AuditOutcome.class));
    }

    /** §27.11 rule 1 for AuthnRequestParamsMode. */
    @Test
    void authnRequestParamsModeIsOpen() throws Exception {
        assertEquals(AuthnRequestParamsMode.IGNORE, JSON.readValue("\"ignore\"", AuthnRequestParamsMode.class));
        assertEquals(AuthnRequestParamsMode.UNKNOWN, JSON.readValue(UNLISTED, AuthnRequestParamsMode.class));
    }

    /** §27.11 rule 1 for CertificateStatus. */
    @Test
    void certificateStatusIsOpen() throws Exception {
        assertEquals(CertificateStatus.ACTIVE, JSON.readValue("\"Active\"", CertificateStatus.class));
        assertEquals(CertificateStatus.UNKNOWN, JSON.readValue(UNLISTED, CertificateStatus.class));
    }

    /** §27.11 rule 1 for CertificateType. */
    @Test
    void certificateTypeIsOpen() throws Exception {
        assertEquals(CertificateType.USER, JSON.readValue("\"User\"", CertificateType.class));
        assertEquals(CertificateType.UNKNOWN, JSON.readValue(UNLISTED, CertificateType.class));
    }

    /** §27.11 rule 1 for CertificationLevel. */
    @Test
    void certificationLevelIsOpen() throws Exception {
        assertEquals(CertificationLevel.L1, JSON.readValue("\"L1\"", CertificationLevel.class));
        assertEquals(CertificationLevel.UNKNOWN, JSON.readValue(UNLISTED, CertificationLevel.class));
    }

    /** §27.11 rule 1 for CibaDeliveryMode. */
    @Test
    void cibaDeliveryModeIsOpen() throws Exception {
        assertEquals(CibaDeliveryMode.POLL, JSON.readValue("\"poll\"", CibaDeliveryMode.class));
        assertEquals(CibaDeliveryMode.UNKNOWN, JSON.readValue(UNLISTED, CibaDeliveryMode.class));
    }

    /** §27.11 rule 1 for CibaRequestSigningAlg. */
    @Test
    void cibaRequestSigningAlgIsOpen() throws Exception {
        assertEquals(CibaRequestSigningAlg.PS256, JSON.readValue("\"PS256\"", CibaRequestSigningAlg.class));
        assertEquals(CibaRequestSigningAlg.UNKNOWN, JSON.readValue(UNLISTED, CibaRequestSigningAlg.class));
    }

    /** §27.11 rule 1 for ClientAuthMethod. */
    @Test
    void clientAuthMethodIsOpen() throws Exception {
        assertEquals(ClientAuthMethod.CLIENT_SECRET_POST, JSON.readValue("\"client_secret_post\"", ClientAuthMethod.class));
        assertEquals(ClientAuthMethod.UNKNOWN, JSON.readValue(UNLISTED, ClientAuthMethod.class));
    }

    /** §27.11 rule 1 for ClientProfile. */
    @Test
    void clientProfileIsOpen() throws Exception {
        assertEquals(ClientProfile.STANDARD, JSON.readValue("\"standard\"", ClientProfile.class));
        assertEquals(ClientProfile.UNKNOWN, JSON.readValue(UNLISTED, ClientProfile.class));
    }

    /** §27.11 rule 1 for DeprovisionPolicy. */
    @Test
    void deprovisionPolicyIsOpen() throws Exception {
        assertEquals(DeprovisionPolicy.DEACTIVATE, JSON.readValue("\"deactivate\"", DeprovisionPolicy.class));
        assertEquals(DeprovisionPolicy.UNKNOWN, JSON.readValue(UNLISTED, DeprovisionPolicy.class));
    }

    /** §27.11 rule 1 for DirectoryKind. */
    @Test
    void directoryKindIsOpen() throws Exception {
        assertEquals(DirectoryKind.OPEN_LDAP, JSON.readValue("\"open_ldap\"", DirectoryKind.class));
        assertEquals(DirectoryKind.UNKNOWN, JSON.readValue(UNLISTED, DirectoryKind.class));
    }

    /** §27.11 rule 1 for FailurePolicy. */
    @Test
    void failurePolicyIsOpen() throws Exception {
        assertEquals(FailurePolicy.FAIL_CLOSED, JSON.readValue("\"fail_closed\"", FailurePolicy.class));
        assertEquals(FailurePolicy.UNKNOWN, JSON.readValue(UNLISTED, FailurePolicy.class));
    }

    /** §27.11 rule 1 for KeyAlgorithm. */
    @Test
    void keyAlgorithmIsOpen() throws Exception {
        assertEquals(KeyAlgorithm.RSA4096, JSON.readValue("\"Rsa4096\"", KeyAlgorithm.class));
        assertEquals(KeyAlgorithm.UNKNOWN, JSON.readValue(UNLISTED, KeyAlgorithm.class));
    }

    /** §27.11 rule 1 for ManagedBy. */
    @Test
    void managedByIsOpen() throws Exception {
        assertEquals(ManagedBy.ADMIN, JSON.readValue("\"admin\"", ManagedBy.class));
        assertEquals(ManagedBy.UNKNOWN, JSON.readValue(UNLISTED, ManagedBy.class));
    }

    /** §27.11 rule 1 for MfaMethodType. */
    @Test
    void mfaMethodTypeIsOpen() throws Exception {
        assertEquals(MfaMethodType.TOTP, JSON.readValue("\"Totp\"", MfaMethodType.class));
        assertEquals(MfaMethodType.UNKNOWN, JSON.readValue(UNLISTED, MfaMethodType.class));
    }

    /** §27.11 rule 1 for NameIdFormat. */
    @Test
    void nameIdFormatIsOpen() throws Exception {
        assertEquals(NameIdFormat.PERSISTENT, JSON.readValue("\"persistent\"", NameIdFormat.class));
        assertEquals(NameIdFormat.UNKNOWN, JSON.readValue(UNLISTED, NameIdFormat.class));
    }

    /** §27.11 rule 1 for NotificationEventType. */
    @Test
    void notificationEventTypeIsOpen() throws Exception {
        assertEquals(NotificationEventType.LOGIN_FAILURE, JSON.readValue("\"login_failure\"", NotificationEventType.class));
        assertEquals(NotificationEventType.UNKNOWN, JSON.readValue(UNLISTED, NotificationEventType.class));
    }

    /** §27.11 rule 1 for PermissionEffect. */
    @Test
    void permissionEffectIsOpen() throws Exception {
        assertEquals(PermissionEffect.ALLOW, JSON.readValue("\"allow\"", PermissionEffect.class));
        assertEquals(PermissionEffect.UNKNOWN, JSON.readValue(UNLISTED, PermissionEffect.class));
    }

    /** §27.11 rule 1 for PgpKeyAlgorithm. */
    @Test
    void pgpKeyAlgorithmIsOpen() throws Exception {
        assertEquals(PgpKeyAlgorithm.RSA4096, JSON.readValue("\"Rsa4096\"", PgpKeyAlgorithm.class));
        assertEquals(PgpKeyAlgorithm.UNKNOWN, JSON.readValue(UNLISTED, PgpKeyAlgorithm.class));
    }

    /** §27.11 rule 1 for PgpKeyPurpose. */
    @Test
    void pgpKeyPurposeIsOpen() throws Exception {
        assertEquals(PgpKeyPurpose.AUDIT_SIGNING, JSON.readValue("\"AuditSigning\"", PgpKeyPurpose.class));
        assertEquals(PgpKeyPurpose.UNKNOWN, JSON.readValue(UNLISTED, PgpKeyPurpose.class));
    }

    /** §27.11 rule 1 for PgpKeyStatus. */
    @Test
    void pgpKeyStatusIsOpen() throws Exception {
        assertEquals(PgpKeyStatus.ACTIVE, JSON.readValue("\"Active\"", PgpKeyStatus.class));
        assertEquals(PgpKeyStatus.UNKNOWN, JSON.readValue(UNLISTED, PgpKeyStatus.class));
    }

    /** §27.11 rule 1 for ReactorMode. */
    @Test
    void reactorModeIsOpen() throws Exception {
        assertEquals(ReactorMode.INTERCEPT, JSON.readValue("\"intercept\"", ReactorMode.class));
        assertEquals(ReactorMode.UNKNOWN, JSON.readValue(UNLISTED, ReactorMode.class));
    }

    /** §27.11 rule 1 for SamlBinding. */
    @Test
    void samlBindingIsOpen() throws Exception {
        assertEquals(SamlBinding.HTTP_POST, JSON.readValue("\"http_post\"", SamlBinding.class));
        assertEquals(SamlBinding.UNKNOWN, JSON.readValue(UNLISTED, SamlBinding.class));
    }

    /** §27.11 rule 1 for SamlIdpCredentialStatus. */
    @Test
    void samlIdpCredentialStatusIsOpen() throws Exception {
        assertEquals(SamlIdpCredentialStatus.ACTIVE, JSON.readValue("\"active\"", SamlIdpCredentialStatus.class));
        assertEquals(SamlIdpCredentialStatus.UNKNOWN, JSON.readValue(UNLISTED, SamlIdpCredentialStatus.class));
    }

    /** §27.11 rule 1 for SamlIdpSlot. */
    @Test
    void samlIdpSlotIsOpen() throws Exception {
        assertEquals(SamlIdpSlot.ACTIVE, JSON.readValue("\"active\"", SamlIdpSlot.class));
        assertEquals(SamlIdpSlot.UNKNOWN, JSON.readValue(UNLISTED, SamlIdpSlot.class));
    }

    /** §27.11 rule 1 for ScimTokenStatus. */
    @Test
    void scimTokenStatusIsOpen() throws Exception {
        assertEquals(ScimTokenStatus.ACTIVE, JSON.readValue("\"active\"", ScimTokenStatus.class));
        assertEquals(ScimTokenStatus.UNKNOWN, JSON.readValue(UNLISTED, ScimTokenStatus.class));
    }

    /** §27.11 rule 1 for SettingsScope. */
    @Test
    void settingsScopeIsOpen() throws Exception {
        assertEquals(SettingsScope.ORG, JSON.readValue("\"Org\"", SettingsScope.class));
        assertEquals(SettingsScope.UNKNOWN, JSON.readValue(UNLISTED, SettingsScope.class));
    }

    /** §27.11 rule 1 for SsfDeliveryMethod. */
    @Test
    void ssfDeliveryMethodIsOpen() throws Exception {
        assertEquals(SsfDeliveryMethod.PUSH, JSON.readValue("\"push\"", SsfDeliveryMethod.class));
        assertEquals(SsfDeliveryMethod.UNKNOWN, JSON.readValue(UNLISTED, SsfDeliveryMethod.class));
    }

    /** §27.11 rule 1 for SsfEventType. */
    @Test
    void ssfEventTypeIsOpen() throws Exception {
        assertEquals(SsfEventType.SESSION_REVOKED, JSON.readValue("\"https://schemas.openid.net/secevent/caep/event-type/session-revoked\"", SsfEventType.class));
        assertEquals(SsfEventType.UNKNOWN, JSON.readValue(UNLISTED, SsfEventType.class));
    }

    /** §27.11 rule 1 for SsfStatusActor. */
    @Test
    void ssfStatusActorIsOpen() throws Exception {
        assertEquals(SsfStatusActor.ADMIN, JSON.readValue("\"admin\"", SsfStatusActor.class));
        assertEquals(SsfStatusActor.UNKNOWN, JSON.readValue(UNLISTED, SsfStatusActor.class));
    }

    /** §27.11 rule 1 for SsfStreamStatus. */
    @Test
    void ssfStreamStatusIsOpen() throws Exception {
        assertEquals(SsfStreamStatus.ENABLED, JSON.readValue("\"enabled\"", SsfStreamStatus.class));
        assertEquals(SsfStreamStatus.UNKNOWN, JSON.readValue(UNLISTED, SsfStreamStatus.class));
    }

    /** §27.11 rule 1 for SsfSubjectFormat. */
    @Test
    void ssfSubjectFormatIsOpen() throws Exception {
        assertEquals(SsfSubjectFormat.ISS_SUB, JSON.readValue("\"iss_sub\"", SsfSubjectFormat.class));
        assertEquals(SsfSubjectFormat.UNKNOWN, JSON.readValue(UNLISTED, SsfSubjectFormat.class));
    }

    /** §27.11 rule 1 for TenantKind. */
    @Test
    void tenantKindIsOpen() throws Exception {
        assertEquals(TenantKind.STANDARD, JSON.readValue("\"standard\"", TenantKind.class));
        assertEquals(TenantKind.UNKNOWN, JSON.readValue(UNLISTED, TenantKind.class));
    }

    /** §27.11 rule 1 for TenantStatus. */
    @Test
    void tenantStatusIsOpen() throws Exception {
        assertEquals(TenantStatus.ACTIVE, JSON.readValue("\"Active\"", TenantStatus.class));
        assertEquals(TenantStatus.UNKNOWN, JSON.readValue(UNLISTED, TenantStatus.class));
    }

    /** §27.11 rule 1 for UnknownAaguidAction. */
    @Test
    void unknownAaguidActionIsOpen() throws Exception {
        assertEquals(UnknownAaguidAction.ALLOW, JSON.readValue("\"allow\"", UnknownAaguidAction.class));
        assertEquals(UnknownAaguidAction.UNKNOWN, JSON.readValue(UNLISTED, UnknownAaguidAction.class));
    }

    /** §27.11 rule 1 for UserNameSource. */
    @Test
    void userNameSourceIsOpen() throws Exception {
        assertEquals(UserNameSource.USERNAME, JSON.readValue("\"username\"", UserNameSource.class));
        assertEquals(UserNameSource.UNKNOWN, JSON.readValue(UNLISTED, UserNameSource.class));
    }

    /** §27.11 rule 1 for UserStatus. */
    @Test
    void userStatusIsOpen() throws Exception {
        assertEquals(UserStatus.ACTIVE, JSON.readValue("\"Active\"", UserStatus.class));
        assertEquals(UserStatus.UNKNOWN, JSON.readValue(UNLISTED, UserStatus.class));
    }

    /** §31.2 for ScimTargetAuth: an unknown type decodes, and is never sent. */
    @Test
    void scimTargetAuthDecodesAnUnknownArmAndRefusesToSendIt() throws Exception {
        ScimTargetAuth decoded = JSON.readValue("{\"type\": \"from_a_later_contract\", \"member\": \"dropped\"}", ScimTargetAuth.class);
        ScimTargetAuthUnknown unknown = assertInstanceOf(ScimTargetAuthUnknown.class, decoded);
        assertEquals("from_a_later_contract", unknown.type());
        assertThrows(NetworkError.class, () -> ManagementTransport.encodeBody("test", unknown));
        assertThrows(NetworkError.class,
                () -> ManagementTransport.encodeBody("test", java.util.List.<ScimTargetAuth>of(unknown)));
    }

    /** §31.2 for ScimTargetScope: an unknown type decodes, and is never sent. */
    @Test
    void scimTargetScopeDecodesAnUnknownArmAndRefusesToSendIt() throws Exception {
        ScimTargetScope decoded = JSON.readValue("{\"type\": \"from_a_later_contract\", \"member\": \"dropped\"}", ScimTargetScope.class);
        ScimTargetScopeUnknown unknown = assertInstanceOf(ScimTargetScopeUnknown.class, decoded);
        assertEquals("from_a_later_contract", unknown.type());
        assertThrows(NetworkError.class, () -> ManagementTransport.encodeBody("test", unknown));
        assertThrows(NetworkError.class,
                () -> ManagementTransport.encodeBody("test", java.util.List.<ScimTargetScope>of(unknown)));
    }

}
