// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The audit management namespace (CONTRACT §27.1).
 *
 * <p>Append-only audit log, read-only by construction.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().audit()...) — one line, rather than 146 more methods to keep in step.
 */
public final class AuditApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    AuditApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/audit-logs.
     *
     * @param actorId the optional actor_id query filter, or null to omit it
     * @param action the optional action query filter, or null to omit it
     * @param outcome the optional outcome query filter, or null to omit it
     * @param resourceId the optional resource_id query filter, or null to omit it
     * @param from the optional from query filter, or null to omit it
     * @param to the optional to query filter, or null to omit it
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.AuditLogEntry> list(@Nullable String actorId, @Nullable String action, @Nullable String outcome, @Nullable String resourceId, @Nullable String from, @Nullable String to, @Nullable PageRequest page) {
        final String operation = "audit.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        query.put("actor_id", actorId);
        query.put("action", action);
        query.put("outcome", outcome);
        query.put("resource_id", resourceId);
        query.put("from", from);
        query.put("to", to);
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/audit-logs", "/api/v1/audit-logs", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.AuditLogEntry.class, operation);
    }

    /**
     * Walks audit.list to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param actorId the optional actor_id query filter, or null to omit it
     * @param action the optional action query filter, or null to omit it
     * @param outcome the optional outcome query filter, or null to omit it
     * @param resourceId the optional resource_id query filter, or null to omit it
     * @param from the optional from query filter, or null to omit it
     * @param to the optional to query filter, or null to omit it
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.AuditLogEntry> listAll(@Nullable String actorId, @Nullable String action, @Nullable String outcome, @Nullable String resourceId, @Nullable String from, @Nullable String to, @Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> list(actorId, action, outcome, resourceId, from, to, p));
    }

    /**
     * Issues GET /api/v1/audit-logs/system.
     *
     * @param actorId the optional actor_id query filter, or null to omit it
     * @param action the optional action query filter, or null to omit it
     * @param outcome the optional outcome query filter, or null to omit it
     * @param resourceId the optional resource_id query filter, or null to omit it
     * @param from the optional from query filter, or null to omit it
     * @param to the optional to query filter, or null to omit it
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.AuditLogEntry> listSystem(@Nullable String actorId, @Nullable String action, @Nullable String outcome, @Nullable String resourceId, @Nullable String from, @Nullable String to, @Nullable PageRequest page) {
        final String operation = "audit.list_system";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        query.put("actor_id", actorId);
        query.put("action", action);
        query.put("outcome", outcome);
        query.put("resource_id", resourceId);
        query.put("from", from);
        query.put("to", to);
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/audit-logs/system", "/api/v1/audit-logs/system", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.AuditLogEntry.class, operation);
    }

    /**
     * Walks audit.list_system to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param actorId the optional actor_id query filter, or null to omit it
     * @param action the optional action query filter, or null to omit it
     * @param outcome the optional outcome query filter, or null to omit it
     * @param resourceId the optional resource_id query filter, or null to omit it
     * @param from the optional from query filter, or null to omit it
     * @param to the optional to query filter, or null to omit it
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.AuditLogEntry> listSystemAll(@Nullable String actorId, @Nullable String action, @Nullable String outcome, @Nullable String resourceId, @Nullable String from, @Nullable String to, @Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> listSystem(actorId, action, outcome, resourceId, from, to, p));
    }

}
