// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The federation management namespace (CONTRACT §27.1).
 *
 * <p>Upstream IdP configuration and the per-user links it produces.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().federation()...) — one line, rather than 147 more methods to keep in
 * step.
 */
public final class FederationApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    FederationApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/federation-configs.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.FederationConfigResponse> listConfigs(@Nullable PageRequest page) {
        final String operation = "federation.list_configs";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/federation-configs", "/api/v1/federation-configs", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.FederationConfigResponse.class, operation);
    }

    /**
     * Walks federation.list_configs to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.FederationConfigResponse> listConfigsAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> listConfigs(p));
    }

    /**
     * Issues POST /api/v1/federation-configs.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.FederationConfigResponse createConfig(io.axiam.sdk.management.models.CreateFederationConfigRequest body) {
        final String operation = "federation.create_config";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/federation-configs", "/api/v1/federation-configs", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.FederationConfigResponse.class, operation);
    }

    /**
     * Issues GET /api/v1/federation-configs/{id}.
     *
     * @param id the id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.FederationConfigResponse getConfig(java.util.UUID id) {
        final String operation = "federation.get_config";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/federation-configs/{id}", "/api/v1/federation-configs/" + id + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.FederationConfigResponse.class, operation);
    }

    /**
     * Issues PUT /api/v1/federation-configs/{id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.FederationConfigResponse updateConfig(java.util.UUID id, io.axiam.sdk.management.models.UpdateFederationConfigRequest body) {
        final String operation = "federation.update_config";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/federation-configs/{id}", "/api/v1/federation-configs/" + id + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.FederationConfigResponse.class, operation);
    }

    /**
     * Issues DELETE /api/v1/federation-configs/{id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void deleteConfig(java.util.UUID id) {
        final String operation = "federation.delete_config";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/federation-configs/{id}", "/api/v1/federation-configs/" + id + "", query, null);
    }

    /**
     * Issues GET /api/v1/federation-links/user/{user_id}.
     *
     * @param userId the user_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.FederationLinkResponse> listUserLinks(java.util.UUID userId) {
        final String operation = "federation.list_user_links";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/federation-links/user/{user_id}", "/api/v1/federation-links/user/" + userId + "", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.FederationLinkResponse.class, operation);
    }

    /**
     * Issues DELETE /api/v1/federation-links/{id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void deleteLink(java.util.UUID id) {
        final String operation = "federation.delete_link";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/federation-links/{id}", "/api/v1/federation-links/" + id + "", query, null);
    }

    /**
     * Issues POST /api/v1/federation/oidc/authorize.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.OidcAuthorizeResponse oidcAuthorize(io.axiam.sdk.management.models.OidcAuthorizeRequest body) {
        final String operation = "federation.oidc_authorize";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/federation/oidc/authorize", "/api/v1/federation/oidc/authorize", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.OidcAuthorizeResponse.class, operation);
    }

    /**
     * Issues POST /api/v1/federation/oidc/callback.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.OidcCallbackResponse oidcCallback(io.axiam.sdk.management.models.OidcCallbackRequest body) {
        final String operation = "federation.oidc_callback";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/federation/oidc/callback", "/api/v1/federation/oidc/callback", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.OidcCallbackResponse.class, operation);
    }

}
