// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import io.axiam.sdk.internal.ManagementTransport;

/**
 * The CONTRACT §27 management surface: 146 operations across 24 namespaces.
 *
 * <p>§27.2 makes this namespacing normative rather than stylistic: twenty namespaces have a list
 * and fourteen a get, so flattening 146 operations onto the client would need a disambiguating
 * prefix invented once per operation — and would bury the eight §1 methods most callers actually
 * want under five times as many they do not. Grouping them behind one accessor is the same
 * argument taken one step further: AxiamClient gains a single method rather than twenty-four.
 *
 * <p>Every accessor builds its handle on access and performs no I/O (§27.2 rule 1), so holding one
 * costs nothing and none of them runs at construction.
 */
public final class ManagementApi {

    private final ManagementTransport transport;

    /**
     * Binds the surface to a transport.
     *
     * <p>Called by AxiamClient; there is no reason for an application to construct one.
     *
     * @param transport the client's management transport
     */
    public ManagementApi(ManagementTransport transport) {
        this.transport = transport;
    }

    /**
     * Organizations an SDK client may read and configure. Creation and deletion are outside the
     * SDK boundary (§27.0).
     *
     * @return the organizations namespace handle
     */
    public OrganizationsApi organizations() {
        return new OrganizationsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Tenants within an organization -- the isolation boundary every other namespace is scoped to.
     *
     * @return the tenants namespace handle
     */
    public TenantsApi tenants() {
        return new TenantsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Users within the client's tenant, and the administrative side of their second factor and
     * lockout state.
     *
     * @return the users namespace handle
     */
    public UsersApi users() {
        return new UsersApi(transport, NamespaceScope.inherited());
    }

    /**
     * Named collections of users. Roles assigned to a group are inherited by every member.
     *
     * @return the groups namespace handle
     */
    public GroupsApi groups() {
        return new GroupsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Roles, their permission sets, and their assignment to users and groups.
     *
     * @return the roles namespace handle
     */
    public RolesApi roles() {
        return new RolesApi(transport, NamespaceScope.inherited());
    }

    /**
     * Permissions -- an action on a resource, optionally narrowed by a scope.
     *
     * @return the permissions namespace handle
     */
    public PermissionsApi permissions() {
        return new PermissionsApi(transport, NamespaceScope.inherited());
    }

    /**
     * The resource hierarchy role assignments cascade down.
     *
     * @return the resources namespace handle
     */
    public ResourcesApi resources() {
        return new ResourcesApi(transport, NamespaceScope.inherited());
    }

    /**
     * Sub-resource granularity, always addressed under their resource.
     *
     * @return the scopes namespace handle
     */
    public ScopesApi scopes() {
        return new ScopesApi(transport, NamespaceScope.inherited());
    }

    /**
     * Machine identities, their secrets, and the certificate a device-bound one authenticates
     * with.
     *
     * @return the service_accounts namespace handle
     */
    public ServiceAccountsApi serviceAccounts() {
        return new ServiceAccountsApi(transport, NamespaceScope.inherited());
    }

    /**
     * End-entity X.509 certificates -- the ones issued to users, services and IoT devices.
     *
     * @return the certificates namespace handle
     */
    public CertificatesApi certificates() {
        return new CertificatesApi(transport, NamespaceScope.inherited());
    }

    /**
     * Organization CAs and the per-tenant signing CAs chained beneath them.
     *
     * @return the ca_certificates namespace handle
     */
    public CaCertificatesApi caCertificates() {
        return new CaCertificatesApi(transport, NamespaceScope.inherited());
    }

    /**
     * OpenPGP keys used for audit signing and encrypted data export.
     *
     * @return the pgp_keys namespace handle
     */
    public PgpKeysApi pgpKeys() {
        return new PgpKeysApi(transport, NamespaceScope.inherited());
    }

    /**
     * Outbound event notifications. Delivery signatures are verified with the §13 helper, which
     * this namespace configures.
     *
     * @return the webhooks namespace handle
     */
    public WebhooksApi webhooks() {
        return new WebhooksApi(transport, NamespaceScope.inherited());
    }

    /**
     * Registered OAuth2/OIDC clients -- the registration half of what §12, §21 and §26 then speak
     * to.
     *
     * @return the oauth2_clients namespace handle
     */
    public Oauth2ClientsApi oauth2Clients() {
        return new Oauth2ClientsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Upstream IdP configuration and the per-user links it produces.
     *
     * @return the federation namespace handle
     */
    public FederationApi federation() {
        return new FederationApi(transport, NamespaceScope.inherited());
    }

    /**
     * Which events raise a notification, and to whom.
     *
     * @return the notification_rules namespace handle
     */
    public NotificationRulesApi notificationRules() {
        return new NotificationRulesApi(transport, NamespaceScope.inherited());
    }

    /**
     * Transactional-mail transport, configurable at organization level and overridable per tenant.
     *
     * @return the email_config namespace handle
     */
    public EmailConfigApi emailConfig() {
        return new EmailConfigApi(transport, NamespaceScope.inherited());
    }

    /**
     * Effective settings, and the organization/tenant layers they resolve from.
     *
     * @return the settings namespace handle
     */
    public SettingsApi settings() {
        return new SettingsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Bearer tokens for the SCIM 2.0 provisioning endpoint.
     *
     * @return the scim_tokens namespace handle
     */
    public ScimTokensApi scimTokens() {
        return new ScimTokensApi(transport, NamespaceScope.inherited());
    }

    /**
     * Registration of §22 AMQP extension actors -- the admin surface §22.9 describes, which no SDK
     * could previously reach.
     *
     * @return the reactors namespace handle
     */
    public ReactorsApi reactors() {
        return new ReactorsApi(transport, NamespaceScope.inherited());
    }

    /**
     * Per-tenant attestation policy governing the §24 ceremonies, and the compliance report over
     * it.
     *
     * @return the webauthn_policy namespace handle
     */
    public WebauthnPolicyApi webauthnPolicy() {
        return new WebauthnPolicyApi(transport, NamespaceScope.inherited());
    }

    /**
     * Append-only audit log, read-only by construction.
     *
     * @return the audit namespace handle
     */
    public AuditApi audit() {
        return new AuditApi(transport, NamespaceScope.inherited());
    }

    /**
     * GDPR self-service: the authenticated account's own export and erasure. Scoped to the caller,
     * never to another user.
     *
     * @return the privacy namespace handle
     */
    public PrivacyApi privacy() {
        return new PrivacyApi(transport, NamespaceScope.inherited());
    }

    /**
     * Deployment-level probes and FIDO metadata state. Unauthenticated where the server leaves
     * them so.
     *
     * @return the platform namespace handle
     */
    public PlatformApi platform() {
        return new PlatformApi(transport, NamespaceScope.inherited());
    }

    /**
     * The declarative layer (§27.6): plan what a manifest would change, then apply it.
     *
     * @return the manifest handle
     */
    public ManifestApi manifest() {
        return new ManifestApi(this);
    }
}
