// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The pgp_keys management namespace (CONTRACT §27.1).
 *
 * <p>OpenPGP keys used for audit signing and encrypted data export.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().pgpKeys()...) — one line, rather than 147 more methods to keep in
 * step.
 */
public final class PgpKeysApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    PgpKeysApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/pgp-keys.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.PgpKey> list(@Nullable PageRequest page) {
        final String operation = "pgp_keys.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/pgp-keys", "/api/v1/pgp-keys", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.PgpKey.class, operation);
    }

    /**
     * Walks pgp_keys.list to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.PgpKey> listAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> list(p));
    }

    /**
     * Issues POST /api/v1/pgp-keys.
     *
     * <p>Returns secret material, once. private_key_armored is returned by this call and by no
     * other; no later get will return it again, and the get projection has no field where it was.
     * Discarding the result destroys the credential (§27.5 rule 3).
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.GeneratedPgpKey generate(io.axiam.sdk.management.models.CreatePgpKeyRequest body) {
        final String operation = "pgp_keys.generate";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/pgp-keys", "/api/v1/pgp-keys", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.GeneratedPgpKey.class, operation);
    }

    /**
     * Issues GET /api/v1/pgp-keys/{id}.
     *
     * @param id the id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.PgpKey get(java.util.UUID id) {
        final String operation = "pgp_keys.get";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/pgp-keys/{id}", "/api/v1/pgp-keys/" + id + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.PgpKey.class, operation);
    }

    /**
     * Issues POST /api/v1/pgp-keys/{id}/revoke.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void revoke(java.util.UUID id) {
        final String operation = "pgp_keys.revoke";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "POST",
                "/api/v1/pgp-keys/{id}/revoke", "/api/v1/pgp-keys/" + id + "/revoke", query, null);
    }

    /**
     * Issues POST /api/v1/pgp-keys/{id}/encrypt.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.EncryptedExport encrypt(java.util.UUID id, io.axiam.sdk.management.models.EncryptRequest body) {
        final String operation = "pgp_keys.encrypt";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/pgp-keys/{id}/encrypt", "/api/v1/pgp-keys/" + id + "/encrypt", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.EncryptedExport.class, operation);
    }

    /**
     * Issues POST /api/v1/pgp-keys/sign-audit-batch.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.SignedAuditBatch signAuditBatch(io.axiam.sdk.management.models.SignAuditBatchRequest body) {
        final String operation = "pgp_keys.sign_audit_batch";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/pgp-keys/sign-audit-batch", "/api/v1/pgp-keys/sign-audit-batch", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.SignedAuditBatch.class, operation);
    }

}
