// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The privacy management namespace (CONTRACT §27.1).
 *
 * <p>GDPR self-service: the authenticated account's own export and erasure. Scoped to the caller,
 * never to another user.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().privacy()...) — one line, rather than 146 more methods to keep in
 * step.
 */
public final class PrivacyApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    PrivacyApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues POST /api/v1/account/export.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body, as raw JSON
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void requestExport(com.fasterxml.jackson.databind.JsonNode body) {
        final String operation = "privacy.request_export";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "POST",
                "/api/v1/account/export", "/api/v1/account/export", query, body);
    }

    /**
     * Issues GET /api/v1/account/export/{token}.
     *
     * @param token the token path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void downloadExport(String token) {
        final String operation = "privacy.download_export";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "GET",
                "/api/v1/account/export/{token}", "/api/v1/account/export/" + java.net.URLEncoder.encode(token, java.nio.charset.StandardCharsets.UTF_8) + "", query, null);
    }

    /**
     * Issues POST /api/v1/account/delete.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body, as raw JSON
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void requestDelete(com.fasterxml.jackson.databind.JsonNode body) {
        final String operation = "privacy.request_delete";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "POST",
                "/api/v1/account/delete", "/api/v1/account/delete", query, body);
    }

    /**
     * Issues GET /api/v1/auth/account/delete/cancel.
     *
     * @param token the required token query parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void cancelDelete(String token) {
        final String operation = "privacy.cancel_delete";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        query.put("token", token);
        transport.send(operation, "GET",
                "/api/v1/auth/account/delete/cancel", "/api/v1/auth/account/delete/cancel", query, null);
    }

}
