// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The scim_targets management namespace (CONTRACT §27.1).
 *
 * <p>A tenant's outbound SCIM targets (CONTRACT §31): the downstream SCIM 2.0 service providers
 * AXIAM pushes the tenant's users and groups to, each with its delivery state. The credential
 * AXIAM pushes with is write-only. Deleting a target does not deprovision anything downstream.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().scimTargets()...) — one line, rather than 147 more methods to keep in
 * step.
 */
public final class ScimTargetsApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    ScimTargetsApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/scim-targets.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.ScimTargetResponse> list(@Nullable PageRequest page) {
        final String operation = "scim_targets.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/scim-targets", "/api/v1/scim-targets", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.ScimTargetResponse.class, operation);
    }

    /**
     * Walks scim_targets.list to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.ScimTargetResponse> listAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> list(p));
    }

    /**
     * Issues POST /api/v1/scim-targets.
     *
     * <p>{@code credential} is required here (§31.3 rule 2). It is write-only: no response ever
     * carries it, and the SDK keeps no copy.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ScimTargetResponse create(io.axiam.sdk.management.models.ScimTargetInput body) {
        final String operation = "scim_targets.create";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/scim-targets", "/api/v1/scim-targets", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ScimTargetResponse.class, operation);
    }

    /**
     * Issues GET /api/v1/scim-targets/{id}.
     *
     * @param id the id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ScimTargetResponse get(java.util.UUID id) {
        final String operation = "scim_targets.get";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/scim-targets/{id}", "/api/v1/scim-targets/" + id + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ScimTargetResponse.class, operation);
    }

    /**
     * Issues PUT /api/v1/scim-targets/{id}.
     *
     * <p><strong>The credential is bound to its URL</strong> (§31.3 rule 2): absent {@code credential} keeps the
     * stored one — except that changing {@code base_url} of a bearer target, {@code
     * auth.token_url} or {@code base_url} of a client-credentials target, or {@code auth.type},
     * without {@code credential} in the same write is refused {@code 400} and changes nothing. The
     * SDK holds no credential to re-send. Every other member left out takes its default ({@code
     * ReplacementBodies.from(ScimTargetResponse)} turns a read into the body). An update overtaken
     * by another administrator's write is {@code 409} (§31.3 rule 4): reload, then retry yourself.
     *
     * <p>This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the body is required,
     * and what you do not carry over from a prior read is not preserved -- it is overwritten. Read
     * first, change the field you mean, send the whole thing back.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ScimTargetResponse update(java.util.UUID id, io.axiam.sdk.management.models.ScimTargetInput body) {
        final String operation = "scim_targets.update";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/scim-targets/{id}", "/api/v1/scim-targets/" + id + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ScimTargetResponse.class, operation);
    }

    /**
     * Issues DELETE /api/v1/scim-targets/{id}.
     *
     * <p><strong>Deprovisions nothing downstream</strong> (§31.3 rule 8): the users and groups AXIAM created in
     * the service provider stay there, and AXIAM no longer knows them. To remove them, set {@code
     * deprovision} to {@code delete}, let AXIAM push, and only then delete the target.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void delete(java.util.UUID id) {
        final String operation = "scim_targets.delete";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/scim-targets/{id}", "/api/v1/scim-targets/" + id + "", query, null);
    }

    /**
     * Issues POST /api/v1/scim-targets/{id}/reconcile.
     *
     * <p>Starts a reconciliation in the background and answers {@code 202}; its outcome is on the
     * target's {@code state} (§31.3 rule 7). {@code 409} while a run holds the claim, within five
     * minutes of the last one, or for a disabled target.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ScimReconcileAccepted reconcile(java.util.UUID id) {
        final String operation = "scim_targets.reconcile";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/scim-targets/{id}/reconcile", "/api/v1/scim-targets/" + id + "/reconcile", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ScimReconcileAccepted.class, operation);
    }

}
