// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The scim_tokens management namespace (CONTRACT §27.1).
 *
 * <p>Bearer tokens for the SCIM 2.0 provisioning endpoint.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().scimTokens()...) — one line, rather than 146 more methods to keep in
 * step.
 */
public final class ScimTokensApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    ScimTokensApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/scim-tokens.
     *
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.ScimTokenResponse> list() {
        final String operation = "scim_tokens.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/scim-tokens", "/api/v1/scim-tokens", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.ScimTokenResponse.class, operation);
    }

    /**
     * Issues POST /api/v1/scim-tokens.
     *
     * <p>Returns secret material, once. provisioning_token is returned by this call and by no
     * other; no later get will return it again, and the get projection has no field where it was.
     * Discarding the result destroys the credential (§27.5 rule 3).
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.CreateScimTokenResponse create(io.axiam.sdk.management.models.CreateScimTokenRequest body) {
        final String operation = "scim_tokens.create";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/scim-tokens", "/api/v1/scim-tokens", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.CreateScimTokenResponse.class, operation);
    }

    /**
     * Issues DELETE /api/v1/scim-tokens/{id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param id the id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void revoke(java.util.UUID id) {
        final String operation = "scim_tokens.revoke";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/scim-tokens/{id}", "/api/v1/scim-tokens/" + id + "", query, null);
    }

}
