// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The scopes management namespace (CONTRACT §27.1).
 *
 * <p>Sub-resource granularity, always addressed under their resource.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().scopes()...) — one line, rather than 147 more methods to keep in step.
 */
public final class ScopesApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    ScopesApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/resources/{resource_id}/scopes.
     *
     * @param resourceId the resource_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.Scope> list(java.util.UUID resourceId) {
        final String operation = "scopes.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/resources/{resource_id}/scopes", "/api/v1/resources/" + resourceId + "/scopes", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.Scope.class, operation);
    }

    /**
     * Issues POST /api/v1/resources/{resource_id}/scopes.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param resourceId the resource_id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Scope create(java.util.UUID resourceId, io.axiam.sdk.management.models.CreateScopeRequest body) {
        final String operation = "scopes.create";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/resources/{resource_id}/scopes", "/api/v1/resources/" + resourceId + "/scopes", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Scope.class, operation);
    }

    /**
     * Issues GET /api/v1/resources/{resource_id}/scopes/{scope_id}.
     *
     * @param resourceId the resource_id path parameter
     * @param scopeId the scope_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Scope get(java.util.UUID resourceId, java.util.UUID scopeId) {
        final String operation = "scopes.get";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/resources/{resource_id}/scopes/{scope_id}", "/api/v1/resources/" + resourceId + "/scopes/" + scopeId + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Scope.class, operation);
    }

    /**
     * Issues PUT /api/v1/resources/{resource_id}/scopes/{scope_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param resourceId the resource_id path parameter
     * @param scopeId the scope_id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Scope update(java.util.UUID resourceId, java.util.UUID scopeId, io.axiam.sdk.management.models.UpdateScopeRequest body) {
        final String operation = "scopes.update";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/resources/{resource_id}/scopes/{scope_id}", "/api/v1/resources/" + resourceId + "/scopes/" + scopeId + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Scope.class, operation);
    }

    /**
     * Issues DELETE /api/v1/resources/{resource_id}/scopes/{scope_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param resourceId the resource_id path parameter
     * @param scopeId the scope_id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void delete(java.util.UUID resourceId, java.util.UUID scopeId) {
        final String operation = "scopes.delete";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/resources/{resource_id}/scopes/{scope_id}", "/api/v1/resources/" + resourceId + "/scopes/" + scopeId + "", query, null);
    }

}
