// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The service_accounts management namespace (CONTRACT §27.1).
 *
 * <p>Machine identities, their secrets, and the certificate a device-bound one authenticates with.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().serviceAccounts()...) — one line, rather than 147 more methods to keep
 * in step.
 */
public final class ServiceAccountsApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    ServiceAccountsApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Issues GET /api/v1/service-accounts.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.ServiceAccountResponse> list(@Nullable PageRequest page) {
        final String operation = "service_accounts.list";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/service-accounts", "/api/v1/service-accounts", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.ServiceAccountResponse.class, operation);
    }

    /**
     * Walks service_accounts.list to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.ServiceAccountResponse> listAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> list(p));
    }

    /**
     * Issues POST /api/v1/service-accounts.
     *
     * <p>Returns secret material, once. client_secret is returned by this call and by no other; no
     * later get will return it again, and the get projection has no field where it was. Discarding
     * the result destroys the credential (§27.5 rule 3).
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ServiceAccountCreatedResponse create(io.axiam.sdk.management.models.CreateServiceAccountRequest body) {
        final String operation = "service_accounts.create";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/service-accounts", "/api/v1/service-accounts", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ServiceAccountCreatedResponse.class, operation);
    }

    /**
     * Issues GET /api/v1/service-accounts/{sa_id}.
     *
     * @param saId the sa_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ServiceAccountResponse get(java.util.UUID saId) {
        final String operation = "service_accounts.get";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/service-accounts/{sa_id}", "/api/v1/service-accounts/" + saId + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ServiceAccountResponse.class, operation);
    }

    /**
     * Issues PUT /api/v1/service-accounts/{sa_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param saId the sa_id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.ServiceAccountResponse update(java.util.UUID saId, io.axiam.sdk.management.models.UpdateServiceAccount body) {
        final String operation = "service_accounts.update";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/service-accounts/{sa_id}", "/api/v1/service-accounts/" + saId + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.ServiceAccountResponse.class, operation);
    }

    /**
     * Issues DELETE /api/v1/service-accounts/{sa_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param saId the sa_id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void delete(java.util.UUID saId) {
        final String operation = "service_accounts.delete";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/service-accounts/{sa_id}", "/api/v1/service-accounts/" + saId + "", query, null);
    }

    /**
     * Issues POST /api/v1/service-accounts/{sa_id}/rotate-secret.
     *
     * <p>Returns secret material, once. client_secret is returned by this call and by no other; no
     * later get will return it again, and the get projection has no field where it was. Discarding
     * the result destroys the credential (§27.5 rule 3).
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param saId the sa_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.RotateSecretResponse rotateSecret(java.util.UUID saId) {
        final String operation = "service_accounts.rotate_secret";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/service-accounts/{sa_id}/rotate-secret", "/api/v1/service-accounts/" + saId + "/rotate-secret", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.RotateSecretResponse.class, operation);
    }

    /**
     * Issues POST /api/v1/service-accounts/{sa_id}/bind-certificate.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param saId the sa_id path parameter
     * @param body the request body
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void bindCertificate(java.util.UUID saId, io.axiam.sdk.management.models.BindCertificate body) {
        final String operation = "service_accounts.bind_certificate";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "POST",
                "/api/v1/service-accounts/{sa_id}/bind-certificate", "/api/v1/service-accounts/" + saId + "/bind-certificate", query, body);
    }

    /**
     * Issues GET /api/v1/service-accounts/{service_account_id}/roles.
     *
     * @param serviceAccountId the service_account_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.RoleAssignment> listRoles(java.util.UUID serviceAccountId) {
        final String operation = "service_accounts.list_roles";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/service-accounts/{service_account_id}/roles", "/api/v1/service-accounts/" + serviceAccountId + "/roles", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.RoleAssignment.class, operation);
    }

    /**
     * Issues GET /api/v1/service-accounts/{service_account_id}/groups.
     *
     * @param serviceAccountId the service_account_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.Group> listGroups(java.util.UUID serviceAccountId) {
        final String operation = "service_accounts.list_groups";
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/service-accounts/{service_account_id}/groups", "/api/v1/service-accounts/" + serviceAccountId + "/groups", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.Group.class, operation);
    }

}
