// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The ssf management namespace (CONTRACT §27.1).
 *
 * <p>A tenant's Shared Signals Framework streams (CONTRACT §32): which receiver -- an OAuth2
 * client of the tenant -- receives which CAEP and RISC security events, as SETs pushed to its
 * endpoint or polled. The receiver's own protocol (transmitter metadata, the SSF stream management
 * API, polling) is not in this registry.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().ssf()...) — one line, rather than 147 more methods to keep in step.
 */
public final class SsfApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    SsfApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Addresses a different tenant than the client's own (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a new handle; this one is unchanged
     */
    public SsfApi forTenant(UUID tenantId) {
        return new SsfApi(transport, scope.withTenant(tenantId));
    }

    /**
     * Issues GET /api/v1/tenants/{tenant_id}/ssf/streams.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.SsfStream> listStreams(@Nullable PageRequest page) {
        final String operation = "ssf.list_streams";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/tenants/{tenant_id}/ssf/streams", "/api/v1/tenants/" + tenantId + "/ssf/streams", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.SsfStream.class, operation);
    }

    /**
     * Walks ssf.list_streams to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.SsfStream> listStreamsAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> listStreams(p));
    }

    /**
     * Issues POST /api/v1/tenants/{tenant_id}/ssf/streams.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.SsfStream createStream(io.axiam.sdk.management.models.SsfStreamInput body) {
        final String operation = "ssf.create_stream";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/tenants/{tenant_id}/ssf/streams", "/api/v1/tenants/" + tenantId + "/ssf/streams", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.SsfStream.class, operation);
    }

    /**
     * Issues GET /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
     *
     * @param streamId the stream_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.SsfStream getStream(java.util.UUID streamId) {
        final String operation = "ssf.get_stream";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}", "/api/v1/tenants/" + tenantId + "/ssf/streams/" + streamId + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.SsfStream.class, operation);
    }

    /**
     * Issues PUT /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
     *
     * <p>An omitted optional member takes its default (§32.2) — <strong>except {@code
     * authorization_header}, which absent keeps the stored one</strong> — unless the update moves {@code
     * endpoint_url} to another scheme, host or port while a header is stored: then it must carry
     * {@code authorization_header} again or {@code clear_authorization_header: true}, else {@code
     * 400} (§32.3 rule 5). An update overtaken by the receiver's own write is {@code 409}: read
     * the stream again. {@code ReplacementBodies.from(SsfStream)} turns a read into the body.
     *
     * <p>This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the body is required,
     * and what you do not carry over from a prior read is not preserved -- it is overwritten. Read
     * first, change the field you mean, send the whole thing back.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param streamId the stream_id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.SsfStream updateStream(java.util.UUID streamId, io.axiam.sdk.management.models.SsfStreamInput body) {
        final String operation = "ssf.update_stream";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}", "/api/v1/tenants/" + tenantId + "/ssf/streams/" + streamId + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.SsfStream.class, operation);
    }

    /**
     * Issues DELETE /api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param streamId the stream_id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void deleteStream(java.util.UUID streamId) {
        final String operation = "ssf.delete_stream";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/tenants/{tenant_id}/ssf/streams/{stream_id}", "/api/v1/tenants/" + tenantId + "/ssf/streams/" + streamId + "", query, null);
    }

}
