// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The tenants management namespace (CONTRACT §27.1).
 *
 * <p>Tenants within an organization -- the isolation boundary every other namespace is scoped to.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().tenants()...) — one line, rather than 146 more methods to keep in
 * step.
 */
public final class TenantsApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    TenantsApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Addresses a different organization than the client's own.
     *
     * <p>§27.4 rule 3: the client's organization is the default, and a platform-admin token
     * legitimately overrides it.
     *
     * @param orgId the organization to address
     * @return a new handle; this one is unchanged
     */
    public TenantsApi inOrg(UUID orgId) {
        return new TenantsApi(transport, scope.withOrg(orgId));
    }

    /**
     * Issues GET /api/v1/organizations/{org_id}/tenants.
     *
     * @param page where the page starts and how big it is, or null for the server's default
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public Page<io.axiam.sdk.management.models.Tenant> list(@Nullable PageRequest page) {
        final String operation = "tenants.list";
        UUID orgId = ManagementSupport.resolveOrg(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        ManagementSupport.pageQuery(query, page);
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/organizations/{org_id}/tenants", "/api/v1/organizations/" + orgId + "/tenants", query, null);
        return ManagementSupport.convertPage(node, io.axiam.sdk.management.models.Tenant.class, operation);
    }

    /**
     * Walks tenants.list to exhaustion, concatenating every page.
     *
     * <p>The auto-paging form §27.4 rule 4 requires. It stops on an empty page even if the total
     * disagrees, so a misreporting server costs one wasted request rather than an unbounded loop.
     *
     * @param start where the walk begins, or null to start at the top
     * @return every item in the set, across as many requests as it takes
     */
    public java.util.List<io.axiam.sdk.management.models.Tenant> listAll(@Nullable PageRequest start) {
        return ManagementSupport.collectPages(start, p -> list(p));
    }

    /**
     * Issues POST /api/v1/organizations/{org_id}/tenants.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Tenant create(io.axiam.sdk.management.models.CreateTenantRequest body) {
        final String operation = "tenants.create";
        UUID orgId = ManagementSupport.resolveOrg(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "POST",
                "/api/v1/organizations/{org_id}/tenants", "/api/v1/organizations/" + orgId + "/tenants", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Tenant.class, operation);
    }

    /**
     * Issues GET /api/v1/organizations/{org_id}/tenants/{tenant_id}.
     *
     * @param tenantId the tenant_id path parameter
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Tenant get(java.util.UUID tenantId) {
        final String operation = "tenants.get";
        UUID orgId = ManagementSupport.resolveOrg(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/organizations/{org_id}/tenants/{tenant_id}", "/api/v1/organizations/" + orgId + "/tenants/" + tenantId + "", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Tenant.class, operation);
    }

    /**
     * Issues PUT /api/v1/organizations/{org_id}/tenants/{tenant_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param tenantId the tenant_id path parameter
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.Tenant update(java.util.UUID tenantId, io.axiam.sdk.management.models.UpdateTenant body) {
        final String operation = "tenants.update";
        UUID orgId = ManagementSupport.resolveOrg(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/organizations/{org_id}/tenants/{tenant_id}", "/api/v1/organizations/" + orgId + "/tenants/" + tenantId + "", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.Tenant.class, operation);
    }

    /**
     * Issues DELETE /api/v1/organizations/{org_id}/tenants/{tenant_id}.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param tenantId the tenant_id path parameter
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public void delete(java.util.UUID tenantId) {
        final String operation = "tenants.delete";
        UUID orgId = ManagementSupport.resolveOrg(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        transport.send(operation, "DELETE",
                "/api/v1/organizations/{org_id}/tenants/{tenant_id}", "/api/v1/organizations/" + orgId + "/tenants/" + tenantId + "", query, null);
    }

}
