// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.internal.ManagementTransport;
import org.jspecify.annotations.Nullable;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * The webauthn_policy management namespace (CONTRACT §27.1).
 *
 * <p>Per-tenant attestation policy governing the §24 ceremonies, and the compliance report over
 * it.
 *
 * <p>Acquiring a handle performs no I/O and allocates nothing meaningful (§27.2 rule 1); it holds
 * the transport and cannot be constructed without one.
 *
 * <p>Every operation here is synchronous. The SDK's CompletableFuture twins exist only on the §1
 * core operations, so the async form of a management call is CompletableFuture.supplyAsync(()
 * -&gt; client.management().webauthnPolicy()...) — one line, rather than 147 more methods to keep
 * in step.
 */
public final class WebauthnPolicyApi {

    private final ManagementTransport transport;
    private final NamespaceScope scope;

    WebauthnPolicyApi(ManagementTransport transport, NamespaceScope scope) {
        this.transport = transport;
        this.scope = scope;
    }

    /**
     * Addresses a different tenant than the client's own (§27.4 rule 3).
     *
     * @param tenantId the tenant to address
     * @return a new handle; this one is unchanged
     */
    public WebauthnPolicyApi forTenant(UUID tenantId) {
        return new WebauthnPolicyApi(transport, scope.withTenant(tenantId));
    }

    /**
     * Issues GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy.
     *
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.PolicyResponse get() {
        final String operation = "webauthn_policy.get";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy", "/api/v1/tenants/" + tenantId + "/webauthn/attestation-policy", query, null);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.PolicyResponse.class, operation);
    }

    /**
     * Issues PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy.
     *
     * <p>This is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the body is required,
     * and what you do not carry over from a prior read is not preserved -- it is overwritten. Read
     * first, change the field you mean, send the whole thing back.
     *
     * <p>Not retried on failure (§27.4 rule 8): every write on this surface is issued exactly
     * once, including the ones that look idempotent.
     *
     * @param body the request body
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public io.axiam.sdk.management.models.WebauthnAttestationPolicy set(io.axiam.sdk.management.models.WebauthnAttestationPolicy body) {
        final String operation = "webauthn_policy.set";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "PUT",
                "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy", "/api/v1/tenants/" + tenantId + "/webauthn/attestation-policy", query, body);
        return ManagementSupport.convert(node, io.axiam.sdk.management.models.WebauthnAttestationPolicy.class, operation);
    }

    /**
     * Issues GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report.
     *
     * @return the server's response
     * @throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)
     * @throws io.axiam.sdk.errors.NotFoundError if the server answers 404
     * @throws io.axiam.sdk.errors.ConflictError if the server answers 409
     * @throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422
     * @throws io.axiam.sdk.errors.NetworkError on a transport failure or any other unsuccessful
     *     status
     */
    public java.util.List<io.axiam.sdk.management.models.ComplianceReportEntry> complianceReport() {
        final String operation = "webauthn_policy.compliance_report";
        UUID tenantId = ManagementSupport.resolveTenant(transport, scope, operation);
        Map<String, @Nullable String> query = new LinkedHashMap<>();
        JsonNode node = transport.send(operation, "GET",
                "/api/v1/tenants/{tenant_id}/webauthn/compliance-report", "/api/v1/tenants/" + tenantId + "/webauthn/compliance-report", query, null);
        return ManagementSupport.convertList(node, io.axiam.sdk.management.models.ComplianceReportEntry.class, operation);
    }

}
