#!/usr/bin/env python3
"""Generate the CONTRACT §27 management surface for the Java SDK.

Reads ``management-registry.json`` (the 147 operations across 24 namespaces,
maintained in ``ilpanich/axiam`` and vendored here) plus ``openapi.json`` for the
schemas those operations carry, and writes:

- ``src/main/java/io/axiam/sdk/management/models/*.java`` — one record per
  request and response type;
- ``src/main/java/io/axiam/sdk/management/<Namespace>Api.java`` — one namespace
  handle per namespace;
- ``src/main/java/io/axiam/sdk/management/ManagementApi.java`` — the accessors;
- ``src/test/java/io/axiam/sdk/management/ManagementSurfaceGeneratedTest.java``
- ``src/test/java/io/axiam/sdk/management/ManagementSparseBodiesGeneratedTest.java``
  — one conformance case per operation, plus the §27.9 assertion that all 147
  are reached.

Run with ``--check`` to verify the committed output is current; that is what CI
runs, so a registry change that is not regenerated fails the build rather than
shipping a surface that disagrees with the contract.

Everything this emits must satisfy the repository's Javadoc gate, which runs
``-Xdoclint:all`` with ``failOnWarnings``: every public type, method, parameter,
return value and record component needs a doc comment, and every description
carried over from ``openapi.json`` has to be HTML-escaped on the way in.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY: dict[str, Any] = json.loads((ROOT / "management-registry.json").read_text())
SPEC: dict[str, Any] = json.loads((ROOT / "openapi.json").read_text())
SCHEMAS: dict[str, Any] = SPEC["components"]["schemas"]

BANNER = """// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.

"""

# §27.4 rule 3: `{org_id}` always defaults from the client. `{tenant_id}`
# defaults from the client only where it names the *context*; in `tenants` and
# the signing-CA routes it names the object being acted on.
IMPLICIT_TENANT_NAMESPACES = {"email_config", "settings", "webauthn_policy"}

# Schema names that would collide with a type this SDK already exports from its
# package root. The generated surface is re-exported, so a duplicate name makes
# one of the two unreachable.
RENAMED_SCHEMAS: dict[str, str] = {
    # Empty on purpose. The Java surface lives in its own package
    # (io.axiam.sdk.management.models), so a schema name cannot collide with a
    # type the SDK root already exports the way it can in a flat namespace.
}

PY_KEYWORDS = {
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "none",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
}

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def pascal(text: str) -> str:
    """``service_accounts`` -> ``ServiceAccounts``; already-Pascal input is kept.

    Deliberately does NOT normalise initialisms. Java is not consistent about
    them itself -- ``HttpClient`` sits beside ``HttpURLConnection`` in the JDK --
    and keeping ``openapi.json``'s own spelling means every generated type name
    can be grepped straight out of the spec.
    """
    if "_" not in text and "-" not in text and text[:1].isupper():
        return RENAMED_SCHEMAS.get(text, text)
    parts = [p for p in text.replace("-", "_").replace(" ", "_").split("_") if p]
    joined = "".join(p[0].upper() + p[1:] for p in parts)
    return RENAMED_SCHEMAS.get(joined, joined)


def camel(text: str) -> str:
    """``service_accounts`` -> ``serviceAccounts``; the Java member spelling."""
    out = pascal(text)
    return out[0].lower() + out[1:] if out else out


JAVA_KEYWORDS = {
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "extends", "final", "finally", "float", "for", "goto", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "native", "new",
    "package", "private", "protected", "public", "return", "short", "static",
    "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while", "record", "var", "yield",
}


def member(name: str) -> str:
    """A Java-legal member name for ``name``, keywords suffixed."""
    ident = camel(name)
    return f"{ident}Value" if ident in JAVA_KEYWORDS else ident


def snake(text: str) -> str:
    """``ServiceAccounts`` -> ``service_accounts``; already-snake input is kept."""
    out: list[str] = []
    for i, ch in enumerate(text):
        boundary = not text[i - 1].isupper() or (i + 1 < len(text) and text[i + 1].islower())
        if ch.isupper() and i and boundary:
            out.append("_")
        out.append(ch.lower())
    return "".join(out).replace("-", "_").replace("__", "_")


def safe(name: str) -> str:
    """A Python-legal identifier for ``name``, keywords suffixed."""
    ident = snake(name)
    return f"{ident}_" if ident in PY_KEYWORDS else ident


def wrap(text: str, width: int = 76) -> list[str]:
    """Reflow ``text`` into paragraph-preserving lines; ruff does not reflow docstrings."""
    out: list[str] = []
    for para in str(text).strip().split("\n\n"):
        words = para.split()
        if not words:
            continue
        line = ""
        for word in words:
            if line and len(line) + 1 + len(word) > width:
                out.append(line)
                line = word
            else:
                line = f"{line} {word}" if line else word
        if line:
            out.append(line)
        out.append("")
    while out and out[-1] == "":
        out.pop()
    return out


def escape(text: str) -> str:
    """HTML-escape a server description for a Javadoc comment.

    The Javadoc gate runs ``-Xdoclint:all`` with ``failOnWarnings``, so a bare
    ``<``, ``>`` or ``&`` carried over from ``openapi.json`` is a build failure
    rather than a rendering nit. ``@`` is escaped too: a description mentioning
    an email address or an annotation would otherwise start a block tag.
    """
    out = (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("@", "&#64;")
    )
    # Markdown backticks are common in the spec's prose and mean nothing to
    # Javadoc; {@code} is the equivalent that renders.
    parts = out.split("`")
    if len(parts) > 1 and len(parts) % 2 == 1:
        out = parts[0]
        for i in range(1, len(parts), 2):
            out += "{@code " + parts[i] + "}" + parts[i + 1]
    else:
        out = out.replace("`", "")
    return out


def javadoc(text: str, indent: str = "", tags: list[str] | None = None) -> list[str]:
    """A Javadoc block for ``text`` at ``indent``, with optional block tags."""
    paragraphs = [p for p in str(text).strip().split("\n\n") if p.strip()]
    lines: list[str] = [f"{indent}/**"]
    for i, para in enumerate(paragraphs):
        body = escape(" ".join(para.split()))
        prefix = "" if i == 0 else "<p>"
        for j, line in enumerate(wrap(prefix + body, 96 - len(indent))):
            lines.append(f"{indent} * {line}" if line else f"{indent} *")
        if i < len(paragraphs) - 1:
            lines.append(f"{indent} *")
    # Block tags run contiguously after one blank line, which is how javadoc
    # renders them and how every hand-written comment in this SDK is laid out.
    for i, tag in enumerate(tags or []):
        if i == 0:
            lines.append(f"{indent} *")
        for j, line in enumerate(wrap(tag, 96 - len(indent))):
            lines.append(f"{indent} * {line}" if j == 0 else f"{indent} *     {line}")
    lines.append(f"{indent} */")
    return lines


def inline_javadoc(text: str, indent: str = "") -> list[str]:
    """A one-line Javadoc block where the text fits, else a full block."""
    body = escape(" ".join(str(text).split()))
    if len(indent) + len(body) + 7 <= 110 and "\n" not in str(text).strip():
        return [f"{indent}/** {body} */"]
    return javadoc(text, indent)


# Types this SDK maps the spec's primitives onto.
def java_type(schema: Any, *, boxed: bool = True) -> str:
    """The Java type for ``schema``.

    ``boxed`` is always true on this surface: every optional field is nullable,
    and a primitive cannot be. Keeping the parameter explicit documents that the
    choice was made rather than defaulted into.
    """
    if not schema:
        return "JsonNode"
    if "$ref" in schema:
        return pascal(schema["$ref"].split("/")[-1])
    inner = nullable_ref(schema)
    if inner:
        return pascal(inner)
    if "oneOf" in schema or "anyOf" in schema:
        return "JsonNode"

    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)

    if kind == "string":
        if schema.get("format") == "uuid":
            return "UUID"
        if schema.get("format") == "date-time":
            return "OffsetDateTime"
        return "String"
    if kind == "integer":
        return "Long" if schema.get("format") == "int64" else "Integer"
    if kind == "number":
        return "Double"
    if kind == "boolean":
        return "Boolean"
    if kind == "array":
        return f"List<{java_type(schema.get('items') or {})}>"
    if kind == "object":
        return "JsonNode"
    return "JsonNode"


def resolve_ref(schema: Any) -> Any:
    """Follow ``$ref`` chains to the schema they name."""
    node = schema
    while isinstance(node, dict) and "$ref" in node:
        node = SCHEMAS.get(node["$ref"].split("/")[-1], {})
    return node


def nullable_ref(schema: Any) -> str | None:
    """``{oneOf: [{type: null}, {$ref: X}]}`` -- utoipa's optional-enum shape."""
    variants = schema.get("oneOf") if isinstance(schema, dict) else None
    if not isinstance(variants, list) or len(variants) != 2:
        return None
    nulls = [v for v in variants if v.get("type") == "null"]
    refs = [v for v in variants if "$ref" in v]
    return refs[0]["$ref"].split("/")[-1] if len(nulls) == 1 and len(refs) == 1 else None


def flatten(name: str) -> tuple[dict[str, Any], set[str], str | None]:
    """Properties, required set and description of ``name``, ``allOf`` resolved."""
    props: dict[str, Any] = {}
    required: set[str] = set()

    def absorb(node: Any) -> None:
        """Merge one ``allOf`` member's properties into the accumulator."""
        resolved = resolve_ref(node) if "$ref" in node else node
        props.update(resolved.get("properties") or {})
        required.update(resolved.get("required") or [])
        for sub in resolved.get("allOf") or []:
            absorb(sub)

    schema = SCHEMAS.get(name, {})
    absorb(schema)
    return props, required, schema.get("description")


def discriminated(schema: Any) -> tuple[str, list[tuple[str, Any]]] | None:
    """Detect an internally-tagged union and return ``(tag, [(value, payload)])``."""
    variants = schema.get("oneOf")
    if not isinstance(variants, list) or len(variants) < 2:
        return None
    tag: str | None = None
    arms: list[tuple[str, Any]] = []
    for variant in variants:
        parts = variant.get("allOf") or [variant]
        value: str | None = None
        payload: Any = None
        leftovers: dict[str, Any] = {"type": "object", "properties": {}, "required": []}
        for part in parts:
            if "$ref" in part:
                payload = part
                continue
            for pname, prop in (part.get("properties") or {}).items():
                enum = prop.get("enum")
                if prop.get("type") == "string" and isinstance(enum, list) and len(enum) == 1:
                    if tag and tag != pname:
                        return None
                    tag = pname
                    value = enum[0]
                else:
                    leftovers["properties"][pname] = prop
                    if pname in (part.get("required") or []):
                        leftovers["required"].append(pname)
        if value is None:
            return None
        arms.append((value, payload if payload is not None else leftovers))
    return (tag or "", arms)


def sensitive_map() -> dict[str, set[str]]:
    """Which fields of which schemas carry a secret, per the registry."""
    out: dict[str, set[str]] = {}
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"] and op["sensitive_request_fields"]:
                key = op["request_schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_request_fields"])
            if op["response"]["schema"] and op["sensitive_response_fields"]:
                key = op["response"]["schema"].lstrip("[]")
                out.setdefault(key, set()).update(op["sensitive_response_fields"])
    return out


def schema_closure() -> list[str]:
    """Every schema reachable from an operation, transitively, sorted."""
    seeds: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["request_schema"]:
                seeds.add(op["request_schema"].lstrip("[]"))
            if op["response"]["schema"]:
                seeds.add(op["response"]["schema"].lstrip("[]"))

    def refs_in(node: Any, found: set[str]) -> None:
        """Collect every ``$ref`` target name appearing anywhere under ``node``."""
        if isinstance(node, list):
            for item in node:
                refs_in(item, found)
        elif isinstance(node, dict):
            if "$ref" in node:
                found.add(node["$ref"].split("/")[-1])
            for value in node.values():
                refs_in(value, found)

    seen: set[str] = set()
    frontier = list(seeds)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in SCHEMAS:
            continue
        seen.add(name)
        found: set[str] = set()
        refs_in(SCHEMAS[name], found)
        frontier.extend(f for f in found if f not in seen)
    return sorted(seen)




# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

def model_imports(rendered: str) -> list[str]:
    """The imports a generated model file needs, from what it actually renders."""
    wanted = [
        ("com.fasterxml.jackson.databind.JsonNode", "JsonNode"),
        ("java.time.OffsetDateTime", "OffsetDateTime"),
        ("java.util.List", "List<"),
        ("java.util.UUID", "UUID"),
        ("io.axiam.sdk.Sensitive", "Sensitive"),
    ]
    return [fqn for fqn, token in wanted if token in rendered]


MODELS_PACKAGE = "io.axiam.sdk.management.models"
MODELS_DIR = "src/main/java/io/axiam/sdk/management/models"
API_PACKAGE = "io.axiam.sdk.management"
API_DIR = "src/main/java/io/axiam/sdk/management"


def enum_constant(value: str) -> str:
    """``no_op_refresh`` -> ``NO_OP_REFRESH``; ``Active`` -> ``ACTIVE``."""
    out: list[str] = []
    for i, ch in enumerate(value):
        if ch in "-_ ":
            out.append("_")
            continue
        if ch.isupper() and i and value[i - 1].islower():
            out.append("_")
        out.append(ch.upper())
    ident = "".join(out)
    return f"_{ident}" if ident[:1].isdigit() else ident


def replacement_schemas() -> set[str]:
    """The request bodies whose PUT replaces rather than patches (§27.4 rule 5).

    Read from the registry's ``update_style`` rather than inferred from "every
    field is required", which is also true of most response types.
    """
    out: set[str] = set()
    for ns in REGISTRY["namespaces"].values():
        for op in ns["operations"].values():
            if op["update_style"] == "replace" and op["request_schema"]:
                out.add(op["request_schema"].lstrip("[]"))
    return out


def extra_query_params(op: dict[str, Any]) -> list[dict[str, Any]]:
    """Query parameters that become method arguments, rather than ``PageRequest``.

    ``offset`` and ``limit`` have always come from ``PageRequest``. ``search``
    joins them on paginated operations (CONTRACT §27.4 rule 4): the term is part
    of which page this is, and putting it on the page request rather than on each
    of the twenty generated ``list`` methods is what makes ``collectPages`` carry
    it across the whole walk instead of filtering only the first request.

    The ``paginated`` guard matters. A *non*-paginated operation that grew a
    ``search`` parameter would have no ``PageRequest`` to carry it, so it keeps
    its own argument -- none exists in the registry today, and this is what keeps
    that from silently dropping the parameter if one ever does.
    """
    owned = ("offset", "limit", "search") if op["paginated"] else ("offset", "limit")
    return [q for q in op["query_params"] if q["name"] not in owned]


def projection_map() -> dict[str, list[dict[str, Any]]]:
    """Schema name -> the fields a list projection adds on top of it.

    ``certificates.list`` answers ``Certificate`` plus ``bound_service_account_id``,
    a graph edge the server resolves for the whole page in one query. CONTRACT
    §27.11 rule 4 lets an SDK carry that as an optional component on the base
    record, which is what this does: the field is ``null`` on ``get``, and the SDK
    never synthesizes it there with a second request.
    """
    out: dict[str, list[dict[str, Any]]] = {}
    for nsdef in REGISTRY["namespaces"].values():
        for op in nsdef["operations"].values():
            adds = op["response"].get("projected_fields")
            if not adds or not op["response"].get("schema"):
                continue
            base = op["response"]["schema"].removeprefix("[]")
            out.setdefault(base, []).extend(adds)
    return out


PROJECTIONS: dict[str, list[dict[str, Any]]] = {}
"""Filled in from :func:`projection_map` at start-up; see §27.11 rule 4."""


def emit_enum(name: str, schema: Any) -> str:
    """A Java enum for a string-enum schema, with its wire spelling attached."""
    type_name = pascal(name)
    lines = [BANNER.rstrip("\n"), f"package {MODELS_PACKAGE};", "",
             "import com.fasterxml.jackson.annotation.JsonCreator;",
             "import com.fasterxml.jackson.annotation.JsonValue;", ""]
    lines.extend(javadoc(
        (schema.get("description") or f"The {type_name} values the server defines.")
        + "\n\nThe wire spelling is carried on each constant rather than derived "
          "from its name, because the server's vocabulary is not uniformly cased "
          "and a derivation that worked for every value today would break on the "
          "first one that did not fit."))
    lines.append(f"public enum {type_name} {{")
    values = [v for v in schema["enum"] if isinstance(v, str)]
    for value in values:
        lines.extend(inline_javadoc(f"The server's {value!r} value.", "    "))
        lines.append(f'    {enum_constant(value)}("{value}"),')
    lines.extend(javadoc(
        "A value this SDK's copy of the spec does not list.\n\n"
        "CONTRACT §27.11 rule 1: an unrecognised value MUST decode rather than "
        "failing the response it arrived in. A closed enum turns the next value "
        "the server adds into a parse error on the whole `list`, taking down "
        "every record on the page over one field of one of them -- including the "
        "records the caller was actually after.\n\n"
        "A Java enum constant cannot carry the string it was decoded from, so "
        "this one does not pretend to. Its wire spelling is the empty string, "
        "which no server value is: fifteen of these enums appear in request "
        "bodies, and a read-modify-write that carried an unrecognised value back "
        "is refused by the server with a 400 rather than silently writing a "
        "spelling it never used. Do not send it deliberately -- read the field, "
        "and if it is {@code UNKNOWN}, leave it out of the update.",
        "    "))
    lines.append('    UNKNOWN("");')
    lines.append("")
    lines.append("    /** The spelling this value has on the wire. */")
    lines.append("    private final String wire;")
    lines.append("")
    lines.append(f"    {type_name}(String wire) {{")
    lines.append("        this.wire = wire;")
    lines.append("    }")
    lines.append("")
    lines.extend(javadoc(
        "Returns the spelling this value has on the wire.\n\n"
        "{@link #UNKNOWN} answers the empty string, which is not a value any "
        "server sends. That is deliberate: it is what makes carrying an "
        "unrecognised value back into an update a 400 from the server rather "
        "than a silent rewrite into a spelling it never used. This accessor "
        "cannot throw, because Jackson calls it on every constant while building "
        "its deserializer -- a throwing one would break decoding for the whole "
        "enum, which is the failure this type exists to avoid.",
        "    ",
        ["@return the server's own spelling of this value, or the empty string "
         "for {@link #UNKNOWN}"]))
    lines.append("    @JsonValue")
    lines.append("    public String wire() {")
    lines.append("        return wire;")
    lines.append("    }")
    lines.append("")
    lines.extend(javadoc(
        "Parses a wire value into a constant.\n\nAn unrecognised value yields "
        "{@link #UNKNOWN} rather than throwing (CONTRACT §27.11 rule 1). Failing "
        "here would fail the whole response, so one field of one record the "
        "caller did not ask about would take down the page. A caller that cares "
        "compares against {@code UNKNOWN}; one that does not gets the rest of "
        "the record intact.",
        "    ",
        ["@param value the server's spelling",
         f"@return the matching {type_name}, or {{@link #UNKNOWN}}"]))
    lines.append("    @JsonCreator")
    lines.append(f"    public static {type_name} fromWire(String value) {{")
    lines.append(f"        for ({type_name} candidate : values()) {{")
    lines.append("            if (candidate != UNKNOWN && candidate.wire.equals(value)) {")
    lines.append("                return candidate;")
    lines.append("            }")
    lines.append("        }")
    lines.append("        return UNKNOWN;")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def component_lines(fields: list[dict[str, Any]]) -> list[str]:
    """The record components, one per line, with their Jackson names."""
    out: list[str] = []
    for i, f in enumerate(fields):
        tail = "," if i < len(fields) - 1 else ""
        out.append(f'        @JsonProperty("{f["wire"]}") {f["type"]} {f["name"]}{tail}')
    return out


def field_list(schema_name: str, secrets: set[str]) -> tuple[list[dict[str, Any]], set[str], str | None]:
    """The fields of a schema, in a stable order, with Java names and types."""
    props, required, description = flatten(schema_name)
    props = dict(props)
    for add in PROJECTIONS.get(schema_name, []):
        if add["name"] in props:
            continue
        required.discard(add["name"])
        props[add["name"]] = {
            "type": add.get("type"),
            "format": add.get("format"),
            "description": (
                "resolved by the list projection only. The server resolves this for a "
                "whole page in one query, so it is populated by the list operation and "
                "is null on get (CONTRACT §27.11 rule 4). Null there means \"this read "
                "does not carry it\", not \"there is nothing bound\" — the SDK does not "
                "issue a second request to fill it in"
            ),
        }
    fields = []
    for wire in sorted(props):
        fields.append({
            "wire": wire,
            "name": member(wire),
            "type": "Sensitive" if wire in secrets else java_type(props[wire]),
            "required": wire in required,
            "doc": props[wire].get("description") or f"the server's {wire} field",
            "secret": wire in secrets,
        })
    return fields, required, description


def emit_record(name: str, secrets: set[str], replacement: bool) -> str:
    """A Java record for an object schema, plus a builder when it is sparse."""
    type_name = pascal(name)
    fields, required, description = field_list(name, secrets)
    all_optional = bool(fields) and not required

    text = description or f"The {type_name} schema from the server's OpenAPI document."
    if all_optional:
        text += ("\n\nEvery component is optional, so this is a SPARSE body: what you leave "
                 "null is left unchanged, and is omitted from the wire request entirely rather "
                 "than sent as null (§27.4 rule 5). Use the builder — a canonical constructor "
                 "call with six nulls in it is not something a reader can check.")
    elif replacement:
        text += ("\n\nThis body REPLACES rather than patches (§27.4 rule 5): what you do not "
                 "carry over from a prior read is not preserved, it is overwritten. The "
                 "canonical constructor takes every component, so forgetting one is a compile "
                 "error rather than a silent null on the wire.")

    tags = []
    for f in fields:
        doc = f["doc"]
        if f["secret"]:
            doc += " -- SECRET: redacted from toString and from every JSON rendering except " \
                   "the one request body it is sent in"
        tags.append(f"@param {f['name']} {escape(' '.join(str(doc).split()))}")

    body: list[str] = []
    body.extend(javadoc(text, "", tags))
    body.append("@JsonIgnoreProperties(ignoreUnknown = true)")
    body.append("@JsonInclude(JsonInclude.Include.NON_NULL)")
    if not fields:
        body.append(f"public record {type_name}() {{")
        body.append("}")
    else:
        body.append(f"public record {type_name}(")
        for f in fields:
            if not f["required"]:
                f["type"] = f"@Nullable {f['type']}"
        body.extend(component_lines(fields))
        body.append(") {")
        if all_optional:
            body.extend(emit_builder(type_name, fields))
        body.append("}")

    rendered = "\n".join(body)
    header = [BANNER.rstrip("\n"), f"package {MODELS_PACKAGE};", "",
              "import com.fasterxml.jackson.annotation.JsonIgnoreProperties;",
              "import com.fasterxml.jackson.annotation.JsonInclude;",
              "import com.fasterxml.jackson.annotation.JsonProperty;"]
    if "@Nullable" in rendered:
        header.append("import org.jspecify.annotations.Nullable;")
    imports = model_imports(rendered)
    if imports:
        header.append("")
        header.extend(f"import {fqn};" for fqn in imports)
    header.append("")
    return "\n".join(header + [rendered]) + "\n"


def emit_builder(type_name: str, fields: list[dict[str, Any]]) -> list[str]:
    """A nested builder for a sparse body, so unset stays unset."""
    lines = ["", ]
    lines.extend(javadoc(
        f"Starts a {type_name} with nothing set.\n\nEvery field left unset is "
        f"omitted from the wire body entirely, so a builder that sets one field "
        f"changes one field (§27.4 rule 5).",
        "    ", [f"@return a fresh {type_name}.Builder"]))
    lines.append("    public static Builder builder() {")
    lines.append("        return new Builder();")
    lines.append("    }")
    lines.append("")
    lines.extend(javadoc(
        f"Builds a sparse {type_name}.\n\nWhat you do not set is not sent — not "
        f"sent as null, absent from the body altogether.", "    "))
    lines.append("    public static final class Builder {")
    lines.append("")
    # javadoc's doclint flags an implicit default constructor as undocumented,
    # so the builder declares its own rather than inheriting one it cannot
    # comment.
    lines.append("        /** Starts with every field unset. */")
    lines.append("        private Builder() {")
    lines.append("        }")
    lines.append("")
    for f in fields:
        bare = f["type"].replace("@Nullable ", "")
        lines.append(f"        private @Nullable {bare} {f['name']};")
    lines.append("")
    for f in fields:
        bare = f["type"].replace("@Nullable ", "")
        lines.extend(javadoc(
            f"Sets {escape(f['wire'])}.",
            "        ",
            [f"@param {f['name']} the value to send", "@return this builder"]))
        lines.append(f"        public Builder {f['name']}({bare} {f['name']}) {{")
        lines.append(f"            this.{f['name']} = {f['name']};")
        lines.append("            return this;")
        lines.append("        }")
        lines.append("")
    lines.extend(javadoc(
        "Builds the body.", "        ",
        [f"@return a {type_name} carrying exactly the fields that were set"]))
    lines.append(f"        public {type_name} build() {{")
    joined = ", ".join(f["name"] for f in fields)
    lines.append(f"            return new {type_name}({joined});")
    lines.append("        }")
    lines.append("    }")
    return lines


def emit_union(name: str, schema: Any, tag: str, arms: list[tuple[str, Any]]) -> dict[str, str]:
    """A sealed interface plus one record per arm, Jackson-tagged."""
    type_name = pascal(name)
    files: dict[str, str] = {}
    arm_names = [f"{type_name}{pascal(value)}" for value, _ in arms]

    lines = [BANNER.rstrip("\n"), f"package {MODELS_PACKAGE};", "",
             "import com.fasterxml.jackson.annotation.JsonSubTypes;",
             "import com.fasterxml.jackson.annotation.JsonTypeInfo;", ""]
    lines.extend(javadoc(
        (schema.get("description") or f"A {type_name} value.")
        + f"\n\nA closed set of shapes discriminated by the {tag} field. Sealed, so "
          f"a switch over the permitted records is exhaustive and the compiler says "
          f"so — which is what makes adding an arm a compile error at every call "
          f"site rather than a silent fall-through."))
    lines.append(f'@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY,')
    lines.append(f'        property = "{tag}", visible = true)')
    lines.append("@JsonSubTypes({")
    for (value, _), arm in zip(arms, arm_names):
        lines.append(f'        @JsonSubTypes.Type(value = {arm}.class, name = "{value}"),')
    lines.append("})")
    lines.append(f"public sealed interface {type_name} permits " + ", ".join(arm_names) + " {")
    lines.append("")
    lines.extend(javadoc(
        f"Returns the discriminator this arm carries.", "    ",
        [f"@return the server's {escape(tag)} value for this arm"]))
    lines.append(f"    String {member(tag)}();")
    lines.append("}")
    files[f"{MODELS_DIR}/{type_name}.java"] = "\n".join(lines) + "\n"

    for (value, payload), arm in zip(arms, arm_names):
        if "$ref" in payload:
            props, required, desc = flatten(payload["$ref"].split("/")[-1])
        else:
            props = payload.get("properties") or {}
            required = set(payload.get("required") or [])
            desc = payload.get("description")
        fields = [{
            "wire": w, "name": member(w), "type": java_type(props[w]),
            "required": w in required, "doc": props[w].get("description") or f"the server's {w} field",
            "secret": False,
        } for w in sorted(props) if w != tag]

        arm_lines: list[str] = []
        tags = [f"@param {member(tag)} the discriminator, always {value!r}"]
        for f in fields:
            tags.append(f"@param {f['name']} {escape(' '.join(str(f['doc']).split()))}")
        arm_lines.extend(javadoc(
            (desc or f"The {value!r} arm of {type_name}."), "", tags))
        arm_lines.append("@JsonIgnoreProperties(ignoreUnknown = true)")
        arm_lines.append("@JsonInclude(JsonInclude.Include.NON_NULL)")
        arm_lines.append(f"public record {arm}(")
        components = [f'        @JsonProperty("{tag}") String {member(tag)}'] + [
            f'        @JsonProperty("{f["wire"]}") '
            + ("" if f["required"] else "@Nullable ") + f'{f["type"]} {f["name"]}'
            for f in fields
        ]
        arm_lines.append(",\n".join(components))
        arm_lines.append(f") implements {type_name} {{")
        arm_lines.append("}")
        arm_body = "\n".join(arm_lines)
        arm_header = [BANNER.rstrip("\n"), f"package {MODELS_PACKAGE};", "",
                      "import com.fasterxml.jackson.annotation.JsonIgnoreProperties;",
                      "import com.fasterxml.jackson.annotation.JsonInclude;",
                      "import com.fasterxml.jackson.annotation.JsonProperty;"]
        if "@Nullable" in arm_body:
            arm_header.append("import org.jspecify.annotations.Nullable;")
        arm_imports = model_imports(arm_body)
        if arm_imports:
            arm_header.append("")
            arm_header.extend(f"import {fqn};" for fqn in arm_imports)
        arm_header.append("")
        files[f"{MODELS_DIR}/{arm}.java"] = "\n".join(arm_header + [arm_body]) + "\n"
    return files


def emit_models() -> dict[str, str]:
    """Every generated model file, keyed by repository-relative path."""
    secrets = sensitive_map()
    replacements = replacement_schemas()
    files: dict[str, str] = {}
    for name in schema_closure():
        schema = SCHEMAS[name]
        if "enum" in schema and schema.get("type") == "string":
            files[f"{MODELS_DIR}/{pascal(name)}.java"] = emit_enum(name, schema)
            continue
        union = discriminated(schema)
        if union:
            files.update(emit_union(name, schema, union[0], union[1]))
            continue
        files[f"{MODELS_DIR}/{pascal(name)}.java"] = emit_record(
            name, secrets.get(name, set()), name in replacements)
    return files


# ---------------------------------------------------------------------------
# Namespace handles
# ---------------------------------------------------------------------------


def implicit_params(namespace: str, op: dict[str, Any]) -> set[str]:
    """Which of this operation's path params default from the client (§27.4 rule 3)."""
    names = {p["name"] for p in op["path_params"]}
    out: set[str] = set()
    if "org_id" in names:
        out.add("org_id")
    if "tenant_id" in names and namespace in IMPLICIT_TENANT_NAMESPACES:
        out.add("tenant_id")
    return out


def split_query(op: dict[str, Any]) -> tuple[list[Any], list[Any]]:
    """This operation's non-paging query params, split required / optional."""
    extra = extra_query_params(op)
    return [q for q in extra if q["required"]], [q for q in extra if not q["required"]]


def operation_params(namespace: str, opname: str, op: dict[str, Any]) -> list[dict[str, str]]:
    """This operation's caller-facing parameters, in signature order."""
    implicit = implicit_params(namespace, op)
    params: list[dict[str, str]] = []
    for p in op["path_params"]:
        if p["name"] in implicit:
            continue
        java = "java.util.UUID" if p.get("format") == "uuid" else "String"
        params.append({"name": member(p["name"]), "type": java, "wire": p["name"],
                       "doc": f"the {escape(p['name'])} path parameter"})
    required_q, optional_q = split_query(op)
    for q in required_q:
        params.append({"name": member(q["name"]), "type": "String", "wire": q["name"],
                       "doc": f"the required {escape(q['name'])} query parameter"})
    if op["request_body"] == "schema":
        params.append({"name": "body", "type": f"{MODELS_PACKAGE}.{pascal(op['request_schema'])}",
                       "wire": "", "doc": "the request body"})
    elif op["request_body"] == "untyped":
        params.append({"name": "body", "type": "com.fasterxml.jackson.databind.JsonNode",
                       "wire": "", "doc": "the request body, as raw JSON"})
    for q in optional_q:
        params.append({"name": member(q["name"]), "type": "@Nullable String", "wire": q["name"],
                       "doc": f"the optional {escape(q['name'])} query filter, or null to omit it"})
    if op["paginated"]:
        params.append({"name": "page", "type": "@Nullable PageRequest", "wire": "",
                       "doc": "where the page starts and how big it is, or null for the "
                              "server's default"})
    return params


def response_java(op: dict[str, Any]) -> tuple[str, str]:
    """The declared return type and the expression producing it from ``node``."""
    kind, schema = op["response"]["kind"], op["response"]["schema"]
    if kind == "none":
        return "void", ""
    model = f"{MODELS_PACKAGE}.{pascal(schema)}"
    if kind == "array":
        return (f"java.util.List<{model}>",
                f"ManagementSupport.convertList(node, {model}.class, operation)")
    if kind == "page":
        return (f"Page<{model}>",
                f"ManagementSupport.convertPage(node, {model}.class, operation)")
    return model, f"ManagementSupport.convert(node, {model}.class, operation)"


def operation_doc(op: dict[str, Any]) -> str:
    """The Javadoc body for one generated operation."""
    text = f"Issues {op['method']} {op['path']}."
    if op["update_style"] == "replace":
        text += ("\n\nThis is a REPLACEMENT, not a patch (§27.4 rule 5). Every field of the "
                 "body is required, and what you do not carry over from a prior read is not "
                 "preserved -- it is overwritten. Read first, change the field you mean, send "
                 "the whole thing back.")
    if op["sensitive_response_fields"]:
        joined = ", ".join(op["sensitive_response_fields"])
        text += (f"\n\nReturns secret material, once. {joined} is returned by this call and by "
                 f"no other; no later get will return it again, and the get projection has no "
                 f"field where it was. Discarding the result destroys the credential "
                 f"(§27.5 rule 3).")
    if op["method"] != "GET":
        text += ("\n\nNot retried on failure (§27.4 rule 8): every write on this surface is "
                 "issued exactly once, including the ones that look idempotent.")
    return text


def emit_namespace(namespace: str, nsdef: dict[str, Any]) -> str:
    """One namespace handle class."""
    handle = f"{pascal(namespace)}Api"
    ops = nsdef["operations"]
    has_org = any("org_id" in implicit_params(namespace, o) for o in ops.values())
    has_tenant = any("tenant_id" in implicit_params(namespace, o) for o in ops.values())

    lines = [BANNER.rstrip("\n"), f"package {API_PACKAGE};", "",
             "import com.fasterxml.jackson.databind.JsonNode;",
             "import io.axiam.sdk.internal.ManagementTransport;",
             "import org.jspecify.annotations.Nullable;", "",
             "import java.util.LinkedHashMap;", "import java.util.Map;", "import java.util.UUID;", ""]
    lines.extend(javadoc(
        f"The {namespace} management namespace (CONTRACT §27.1).\n\n{nsdef['doc']}\n\n"
        f"Acquiring a handle performs no I/O and allocates nothing meaningful "
        f"(§27.2 rule 1); it holds the transport and cannot be constructed "
        f"without one.\n\nEvery operation here is synchronous. The SDK's "
        f"CompletableFuture twins exist only on the §1 core operations, so the "
        f"async form of a management call is "
        f"CompletableFuture.supplyAsync(() -> client.management().{camel(namespace)}()...) "
        f"— one line, rather than 147 more methods to keep in step."))
    lines.append(f"public final class {handle} {{")
    lines.append("")
    lines.append("    private final ManagementTransport transport;")
    lines.append("    private final NamespaceScope scope;")
    lines.append("")
    lines.append(f"    {handle}(ManagementTransport transport, NamespaceScope scope) {{")
    lines.append("        this.transport = transport;")
    lines.append("        this.scope = scope;")
    lines.append("    }")
    lines.append("")

    if has_org:
        lines.extend(javadoc(
            "Addresses a different organization than the client's own.\n\n§27.4 rule 3: the "
            "client's organization is the default, and a platform-admin token legitimately "
            "overrides it.",
            "    ", ["@param orgId the organization to address",
                    "@return a new handle; this one is unchanged"]))
        lines.append(f"    public {handle} inOrg(UUID orgId) {{")
        lines.append(f"        return new {handle}(transport, scope.withOrg(orgId));")
        lines.append("    }")
        lines.append("")
    if has_tenant:
        lines.extend(javadoc(
            "Addresses a different tenant than the client's own (§27.4 rule 3).",
            "    ", ["@param tenantId the tenant to address",
                    "@return a new handle; this one is unchanged"]))
        lines.append(f"    public {handle} forTenant(UUID tenantId) {{")
        lines.append(f"        return new {handle}(transport, scope.withTenant(tenantId));")
        lines.append("    }")
        lines.append("")

    for opname, op in ops.items():
        lines.extend(emit_operation(namespace, opname, op))
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_operation(namespace: str, opname: str, op: dict[str, Any]) -> list[str]:
    """One generated operation, plus its auto-paging form where it has one."""
    canonical = f"{namespace}.{opname}"
    method_name = member(opname)
    implicit = implicit_params(namespace, op)
    params = operation_params(namespace, opname, op)
    ret, expr = response_java(op)

    signature = ", ".join(f"{p['type']} {p['name']}" for p in params)
    tags = [f"@param {p['name']} {p['doc']}" for p in params]
    if ret != "void":
        tags.append("@return the server's response")
    tags.extend([
        "@throws io.axiam.sdk.errors.AuthError if there is no active session (§27.4 rule 1)",
        "@throws io.axiam.sdk.errors.NotFoundError if the server answers 404",
        "@throws io.axiam.sdk.errors.ConflictError if the server answers 409",
        "@throws io.axiam.sdk.errors.ValidationError if the server answers 400 or 422",
        "@throws io.axiam.sdk.errors.NetworkError on a transport failure or any other "
        "unsuccessful status",
    ])

    lines: list[str] = []
    lines.extend(javadoc(operation_doc(op), "    ", tags))
    lines.append(f"    public {ret} {method_name}({signature}) {{")
    lines.append(f'        final String operation = "{canonical}";')

    route = op["path"]
    for p in op["path_params"]:
        name = p["name"]
        if name in implicit:
            fn = "resolveOrg" if name == "org_id" else "resolveTenant"
            lines.append(f"        UUID {member(name)} = ManagementSupport.{fn}("
                         f"transport, scope, operation);")
            route = route.replace(f"{{{name}}}", f'" + {member(name)} + "')
        elif p.get("format") == "uuid":
            route = route.replace(f"{{{name}}}", f'" + {member(name)} + "')
        else:
            route = route.replace(
                f"{{{name}}}",
                f'" + java.net.URLEncoder.encode({member(name)}, '
                f'java.nio.charset.StandardCharsets.UTF_8) + "')

    required_q, optional_q = split_query(op)
    lines.append("        Map<String, @Nullable String> query = new LinkedHashMap<>();")
    for q in required_q:
        lines.append(f'        query.put("{q["name"]}", {member(q["name"])});')
    for q in optional_q:
        lines.append(f'        query.put("{q["name"]}", {member(q["name"])});')
    if op["paginated"]:
        lines.append("        ManagementSupport.pageQuery(query, page);")

    body_expr = "body" if op["request_body"] != "none" else "null"
    assign = "" if ret == "void" else "JsonNode node = "
    lines.append(f'        {assign}transport.send(operation, "{op["method"]}",')
    lines.append(f'                "{op["path"]}", "{route}", query, {body_expr});')
    if ret != "void":
        lines.append(f"        return {expr};")
    lines.append("    }")
    lines.append("")

    if op["paginated"]:
        inner = ret[len("Page<"):-1]
        lead = [p for p in params if p["name"] != "page"]
        lead_sig = ", ".join(f"{p['type']} {p['name']}" for p in lead)
        lead_sig = (lead_sig + ", " if lead_sig else "") + "@Nullable PageRequest start"
        forward = "".join(f"{p['name']}, " for p in lead)
        all_tags = [f"@param {p['name']} {p['doc']}" for p in lead]
        all_tags.append("@param start where the walk begins, or null to start at the top")
        all_tags.append("@return every item in the set, across as many requests as it takes")
        lines.extend(javadoc(
            f"Walks {canonical} to exhaustion, concatenating every page.\n\nThe auto-paging "
            f"form §27.4 rule 4 requires. It stops on an empty page even if the total "
            f"disagrees, so a misreporting server costs one wasted request rather than an "
            f"unbounded loop.",
            "    ", all_tags))
        lines.append(f"    public java.util.List<{inner}> {method_name}All({lead_sig}) {{")
        lines.append(f"        return ManagementSupport.collectPages(start, p -> "
                     f"{method_name}({forward}p));")
        lines.append("    }")
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# The accessors, and main
# ---------------------------------------------------------------------------


def emit_api() -> str:
    """The ManagementApi facade, one accessor per namespace."""
    names = list(REGISTRY["namespaces"].keys())
    lines = [BANNER.rstrip("\n"), f"package {API_PACKAGE};", "",
             "import io.axiam.sdk.internal.ManagementTransport;", ""]
    lines.extend(javadoc(
        "The CONTRACT §27 management surface: 147 operations across 24 namespaces.\n\n"
        "§27.2 makes this namespacing normative rather than stylistic: twenty namespaces "
        "have a list and fourteen a get, so flattening 147 operations onto the client "
        "would need a disambiguating prefix invented once per operation — and would bury "
        "the eight §1 methods most callers actually want under five times as many they do "
        "not. Grouping them behind one accessor is the same argument taken one step "
        "further: AxiamClient gains a single method rather than twenty-four.\n\n"
        "Every accessor builds its handle on access and performs no I/O (§27.2 rule 1), "
        "so holding one costs nothing and none of them runs at construction."))
    lines.append("public final class ManagementApi {")
    lines.append("")
    lines.append("    private final ManagementTransport transport;")
    lines.append("")
    lines.extend(javadoc(
        "Binds the surface to a transport.\n\nCalled by AxiamClient; there is no reason "
        "for an application to construct one.",
        "    ", ["@param transport the client's management transport"]))
    lines.append("    public ManagementApi(ManagementTransport transport) {")
    lines.append("        this.transport = transport;")
    lines.append("    }")
    lines.append("")
    for ns in names:
        handle = f"{pascal(ns)}Api"
        lines.extend(javadoc(
            REGISTRY["namespaces"][ns]["doc"], "    ",
            [f"@return the {escape(ns)} namespace handle"]))
        lines.append(f"    public {handle} {member(ns)}() {{")
        lines.append(f"        return new {handle}(transport, NamespaceScope.inherited());")
        lines.append("    }")
        lines.append("")
    lines.extend(javadoc(
        "The declarative layer (§27.6): plan what a manifest would change, then apply it.",
        "    ", ["@return the manifest handle"]))
    lines.append("    public ManifestApi manifest() {")
    lines.append("        return new ManifestApi(this);")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# The generated conformance test
# ---------------------------------------------------------------------------

EXAMPLE_UUID = "11111111-1111-4111-8111-111111111111"
EXAMPLE_TIME = "2026-08-26T00:00:00Z"


def example_json(schema: Any, depth: int = 0) -> Any:
    """A minimal server response body satisfying ``schema``."""
    if depth > 6 or not schema:
        return None
    if "$ref" in schema:
        return example_json(resolve_ref(schema), depth + 1)
    inner = nullable_ref(schema)
    if inner:
        return example_json(SCHEMAS.get(inner, {}), depth + 1)
    if "enum" in schema:
        return schema["enum"][0]
    variants = schema.get("oneOf") or schema.get("anyOf")
    if variants:
        first = next((v for v in variants if v.get("type") != "null"), None)
        return example_json(first, depth + 1) if first else None
    if "allOf" in schema:
        merged: dict[str, Any] = {}
        for part in schema["allOf"]:
            got = example_json(part, depth + 1)
            if isinstance(got, dict):
                merged.update(got)
        required = set(schema.get("required") or [])
        for name, prop in (schema.get("properties") or {}).items():
            if name in required:
                merged[name] = example_json(prop, depth + 1)
        return merged
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)
    if kind == "object" or (not kind and "properties" in schema):
        required = set(schema.get("required") or [])
        return {n: example_json(p, depth + 1)
                for n, p in (schema.get("properties") or {}).items() if n in required}
    if kind == "array":
        return []
    if kind in ("integer", "number"):
        return 1
    if kind == "boolean":
        return True
    if kind == "string":
        if schema.get("format") == "uuid":
            return EXAMPLE_UUID
        if schema.get("format") == "date-time":
            return EXAMPLE_TIME
        return "example"
    return {}


def example_response(op: dict[str, Any]) -> str:
    """A Java string literal for the response body the conformance test mounts."""
    kind, schema = op["response"]["kind"], op["response"]["schema"]
    if kind == "none":
        return '""'
    one = example_json(SCHEMAS.get(schema, {}))
    payload: Any = one
    if kind == "array":
        payload = [one]
    elif kind == "page":
        payload = {"items": [one], "total": 1, "offset": 0, "limit": 50}
    return json.dumps(json.dumps(payload))


def java_literal(schema: Any, secrets: set[str], field: str | None = None, depth: int = 0) -> str:
    """A Java expression building a minimal valid value for a schema."""
    if depth > 6:
        return "null"
    if field and field in secrets:
        return 'io.axiam.sdk.Sensitive.of("example")'
    if "$ref" in schema:
        return literal_for(schema["$ref"].split("/")[-1], set(), depth + 1)
    if nullable_ref(schema) or "oneOf" in schema or "anyOf" in schema:
        return "null"
    kind = schema.get("type")
    if isinstance(kind, list):
        if "null" in kind:
            return "null"
        kind = next(iter(kind), None)
    if "enum" in schema:
        return "null"
    if kind == "array":
        return "java.util.List.of()"
    if kind == "integer":
        return "1L" if schema.get("format") == "int64" else "1"
    if kind == "number":
        return "1.0"
    if kind == "boolean":
        return "true"
    if kind == "string":
        if schema.get("format") == "uuid":
            return "EXAMPLE_ID"
        if schema.get("format") == "date-time":
            return f'java.time.OffsetDateTime.parse("{EXAMPLE_TIME}")'
        return '"example"'
    return "null"


def literal_for(name: str, secrets: set[str], depth: int = 0) -> str:
    """A Java expression constructing a minimal valid instance of ``name``."""
    schema = SCHEMAS.get(name, {})
    type_name = f"{MODELS_PACKAGE}.{pascal(name)}"
    if "enum" in schema and schema.get("type") == "string":
        return f"{type_name}.{enum_constant(schema['enum'][0])}"
    union = discriminated(schema)
    if union:
        tag, arms = union
        value, payload = arms[0]
        arm = f"{type_name}{pascal(value)}"
        if "$ref" in payload:
            aprops, arequired, _ = flatten(payload["$ref"].split("/")[-1])
        else:
            aprops = payload.get("properties") or {}
            arequired = set(payload.get("required") or [])
        args = [f'"{value}"']
        for wire in sorted(aprops):
            if wire == tag:
                continue
            args.append(java_literal(aprops[wire], set(), wire, depth + 1)
                        if wire in arequired else "null")
        return f"new {arm}({', '.join(args)})"
    props, required, _ = flatten(name)
    args = []
    for wire in sorted(props):
        if wire in secrets:
            args.append('io.axiam.sdk.Sensitive.of("example")')
        elif wire in required:
            args.append(java_literal(props[wire], secrets, wire, depth + 1))
        else:
            args.append("null")
    return f"new {type_name}({', '.join(args)})"


def call_arguments(namespace: str, opname: str, op: dict[str, Any],
                   secrets: dict[str, set[str]]) -> tuple[list[str], str]:
    """The conformance test's positional arguments, and the route it mounts."""
    implicit = implicit_params(namespace, op)
    args: list[str] = []
    route = op["path"]
    for p in op["path_params"]:
        name = p["name"]
        if name in implicit:
            token = "ORG_ID" if name == "org_id" else "TENANT_ID"
            route = route.replace(f"{{{name}}}", f'" + {token} + "')
            continue
        if p.get("format") == "uuid":
            args.append("EXAMPLE_ID")
            route = route.replace(f"{{{name}}}", '" + EXAMPLE_ID + "')
        else:
            args.append('"example"')
            route = route.replace(f"{{{name}}}", "example")
    required_q, optional_q = split_query(op)
    args.extend('"example"' for _ in required_q)
    if op["request_body"] == "schema":
        args.append(literal_for(op["request_schema"], secrets.get(op["request_schema"], set())))
    elif op["request_body"] == "untyped":
        args.append("io.axiam.sdk.internal.ManagementTransport.reader().createObjectNode()")
    args.extend("null" for _ in optional_q)
    if op["paginated"]:
        args.append("PageRequest.of(50)")
    return args, route


TEST_DIR = "src/test/java/io/axiam/sdk/management"


def emit_test() -> str:
    """The generated conformance test."""
    secrets = sensitive_map()
    canonical_all: list[str] = []
    lines = [BANNER.rstrip("\n"), "package io.axiam.sdk.management;", "",
             "import org.junit.jupiter.api.Test;", "",
             "import static org.junit.jupiter.api.Assertions.assertEquals;", ""]
    lines.extend(javadoc(
        "Generated §27 surface conformance: every operation is reached once.\n\n"
        "Per operation: the SDK issues the registry's method against the registry's path "
        "and parses the response shape openapi.json declares. Semantics that are not "
        "per-operation — sparse-update key sets, secret redaction, error mapping, "
        "pagination walks, the manifest — are tested by hand in ManagementSemanticsTest "
        "and its neighbours."))
    lines.append("class ManagementSurfaceGeneratedTest extends ManagementTestBase {")
    lines.append("")

    for namespace, nsdef in REGISTRY["namespaces"].items():
        for opname, op in nsdef["operations"].items():
            canonical = f"{namespace}.{opname}"
            canonical_all.append(canonical)
            args, route = call_arguments(namespace, opname, op, secrets)
            joined = ", ".join(args)
            call = f"client.management().{member(namespace)}().{member(opname)}({joined})"
            test_name = f"{member(namespace)}{pascal(opname)}"
            lines.extend(inline_javadoc(f"Exercises {canonical}.", "    "))
            lines.append("    @Test")
            lines.append(f"    void {test_name}() throws Exception {{")
            lines.append(f'        mount("{op["method"]}", "{route}", {op["response"]["status"]}, '
                         f'{example_response(op)});')
            lines.append(f"        {call};")
            if op["paginated"]:
                lead = ", ".join(a for a in args if a != "PageRequest.of(50)")
                tail = f"{lead}, " if lead else ""
                lines.append(f"        client.management().{member(namespace)}()."
                             f"{member(opname)}All({tail}PageRequest.of(50));")
            lines.append("    }")
            lines.append("")

    lines.extend(javadoc(
        "§27.9: a partial regeneration must fail here, not ship 140 of 147.\n\nAsserting "
        "the whole set rather than the count catches a regeneration that dropped one "
        "operation and gained another.",
        "    ", ["@throws Exception if the vendored registry cannot be read"]))
    lines.append("    @Test")
    lines.append("    void generatedSurfaceCoversTheRegistry() throws Exception {")
    lines.append("        java.util.List<String> exercised = java.util.List.of(")
    sorted_all = sorted(canonical_all)
    for i, name in enumerate(sorted_all):
        tail = "," if i < len(sorted_all) - 1 else ");"
        lines.append(f'                "{name}"{tail}')
    lines.append(f"        assertEquals({REGISTRY['operation_count']}, exercised.size(),")
    lines.append('                "the generated surface must reach every operation the registry declares");')
    lines.append("        assertEquals(expectedSurface(), exercised,")
    lines.append('                "the generated surface and the registry must name the same operations");')
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def sparse_models() -> list[tuple[str, list[dict[str, Any]]]]:
    """Every schema whose components are all optional -- the sparse bodies."""
    secrets = sensitive_map()
    out: list[tuple[str, list[dict[str, Any]]]] = []
    for name in schema_closure():
        schema = SCHEMAS[name]
        if "enum" in schema and schema.get("type") == "string":
            continue
        if discriminated(schema):
            continue
        fields, required, _ = field_list(name, secrets.get(name, set()))
        if fields and not required:
            out.append((name, fields))
    return out


def builder_literal(schema: Any, wire: str, secrets: set[str]) -> str:
    """A NON-null Java literal for a sparse field.

    ``java_literal`` is allowed to answer ``null`` -- it fills optional
    components of a request the surface test only needs to be well-formed. Here
    null is the one answer that cannot be used: the whole assertion is that a
    field which WAS set reaches the wire, and a null one is omitted by design.
    """
    if wire in secrets:
        return 'io.axiam.sdk.Sensitive.of("example")'
    ref = schema["$ref"].split("/")[-1] if "$ref" in schema else nullable_ref(schema)
    if ref and ref in SCHEMAS:
        return literal_for(ref, set())
    rendered = java_type(schema)
    if rendered.startswith("List<"):
        return "java.util.List.of()"
    return {
        "UUID": "EXAMPLE_ID",
        "OffsetDateTime": f'java.time.OffsetDateTime.parse("{EXAMPLE_TIME}")',
        "String": '"example"',
        "Long": "1L",
        "Integer": "1",
        "Double": "1.0",
        "Boolean": "true",
        "JsonNode": "JSON.createObjectNode()",
    }[rendered]


def emit_sparse_test() -> str:
    """The generated §27.4 rule 5 conformance test, one case per sparse body."""
    secrets = sensitive_map()
    models = sparse_models()
    lines: list[str] = []
    lines.extend(javadoc(
        "Generated §27.4 rule 5 conformance: a sparse body sends what was set, and "
        "nothing else.\n\nRule 5 draws the line between a sparse update and a "
        "replacement at ABSENCE, not at null: a field the caller did not set must not "
        "appear in the body at all, because a null on the wire is a request to CLEAR "
        "the field. One hand-written example proves that for one model; the failure "
        "this guards against is a generator that gets it right for the model somebody "
        "wrote a test for and wrong for the other seventeen.\n\nEach case sets one "
        "field at a time and asserts the body carries exactly that one wire key, then "
        "sets every field and asserts the body carries exactly all of them. Bodies are "
        "rendered through {@link ManagementTransport#encodeBody}, the writer the SDK "
        "actually sends with."))
    lines.append("class ManagementSparseBodiesGeneratedTest {")
    lines.append("")
    lines.append("    /** Reads back what the wire writer produced. */")
    lines.append("    private static final ObjectMapper JSON = "
                 "new ObjectMapper().registerModule(new JavaTimeModule());")
    lines.append("")
    lines.append("    /** Stands in for any {@code uuid}-formatted component. */")
    lines.append("    private static final UUID EXAMPLE_ID = "
                 'UUID.fromString("11111111-1111-4111-8111-111111111111");')
    lines.append("")

    for name, fields in models:
        props, _, _ = flatten(name)
        type_name = pascal(name)
        model_secrets = secrets.get(name, set())
        test_name = camel(name)
        lines.extend(inline_javadoc(
            f"§27.4 rule 5 for {type_name}: each setter sets exactly its own key.", "    "))
        lines.append("    @Test")
        lines.append(f"    void {test_name}SendsOnlyWhatWasSet() throws Exception {{")
        for f in fields:
            literal = builder_literal(props[f["wire"]], f["wire"], model_secrets)
            lines.append(f"        assertKeys({MODELS_PACKAGE}.{type_name}.builder()")
            lines.append("                ." + f["name"] + "(" + literal
                         + ').build(), "' + f["wire"] + '");')
        lines.append(f"        assertKeys({MODELS_PACKAGE}.{type_name}.builder()")
        for f in fields:
            literal = builder_literal(props[f["wire"]], f["wire"], model_secrets)
            lines.append(f"                .{f['name']}({literal})")
        lines.append("                .build(),")
        row: list[str] = []
        for i, f in enumerate(fields):
            row.append(f'"{f["wire"]}"' + (");" if i == len(fields) - 1 else ","))
            if len(" ".join(row)) > 60 or i == len(fields) - 1:
                lines.append("                " + " ".join(row))
                row = []
        lines.append(f"        assertKeys({MODELS_PACKAGE}.{type_name}.builder().build());")
        lines.append("    }")
        lines.append("")

    lines.extend(javadoc(
        "§27.9: a regeneration that stopped emitting builders must fail here.\n\nThe "
        "count is asserted rather than left implicit so that dropping a sparse model "
        "from the closure is a failure, not a quietly shorter suite.", "    "))
    lines.append("    @Test")
    lines.append("    void everySparseBodyIsCovered() {")
    lines.append("        long cases = java.util.Arrays.stream("
                 "ManagementSparseBodiesGeneratedTest.class.getDeclaredMethods())")
    lines.append('                .filter(m -> m.getName().endsWith("SendsOnlyWhatWasSet")).count();')
    lines.append(f"        assertEquals({len(models)}L, cases,")
    lines.append('                "one case per sparse body the schema closure declares");')
    lines.append("    }")
    lines.append("")
    lines.extend(javadoc(
        "Asserts the encoded body's key set is exactly {@code expected}, in any order.",
        "    ", ["@param body the request body to render", "@param expected the wire keys it must carry",
              "@throws Exception if the encoded body is not readable JSON"]))
    lines.append("    private static void assertKeys(Object body, String... expected) throws Exception {")
    lines.append('        JsonNode node = JSON.readTree(ManagementTransport.encodeBody("test", body));')
    lines.append("        List<String> actual = new ArrayList<>();")
    lines.append("        node.fieldNames().forEachRemaining(actual::add);")
    lines.append("        actual.sort(String::compareTo);")
    lines.append("        List<String> want = new ArrayList<>(List.of(expected));")
    lines.append("        want.sort(String::compareTo);")
    lines.append("        assertEquals(want, actual,")
    lines.append('                body.getClass().getSimpleName()')
    lines.append('                        + ": a sparse body must carry exactly the fields that were set");')
    lines.append("    }")
    lines.append("}")

    # Fully-qualified names keep the emitter simple but the output unreadable,
    # so the model references are collapsed to simple names and the imports
    # they need are derived from what actually got rendered.
    rendered = "\n".join(lines)
    used = sorted(set(re.findall(r"io\.axiam\.sdk\.management\.models\.(\w+)", rendered)))
    rendered = rendered.replace(f"{MODELS_PACKAGE}.", "")
    imports = [
        "com.fasterxml.jackson.databind.JsonNode",
        "com.fasterxml.jackson.databind.ObjectMapper",
        "com.fasterxml.jackson.datatype.jsr310.JavaTimeModule",
        "io.axiam.sdk.internal.ManagementTransport",
        "org.junit.jupiter.api.Test",
    ]
    if "Sensitive.of(" in rendered:
        rendered = rendered.replace("io.axiam.sdk.Sensitive.of(", "Sensitive.of(")
        imports.append("io.axiam.sdk.Sensitive")
    imports.extend(f"{MODELS_PACKAGE}.{name}" for name in used)
    header = [BANNER.rstrip("\n"), "package io.axiam.sdk.management;", ""]
    header.extend(f"import {fqn};" for fqn in sorted(imports))
    header.extend(["", "import java.util.ArrayList;", "import java.util.List;",
                   "import java.util.UUID;", "",
                   "import static org.junit.jupiter.api.Assertions.assertEquals;", ""])
    return "\n".join(header + [rendered]) + "\n"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def build() -> dict[Path, str]:
    """Every file this generator owns, mapped to its current content."""
    files: dict[Path, str] = {}
    for path, body in emit_models().items():
        files[ROOT / path] = body
    for ns, nsdef in REGISTRY["namespaces"].items():
        files[ROOT / f"{API_DIR}/{pascal(ns)}Api.java"] = emit_namespace(ns, nsdef)
    files[ROOT / f"{API_DIR}/ManagementApi.java"] = emit_api()
    files[ROOT / f"{TEST_DIR}/ManagementSurfaceGeneratedTest.java"] = emit_test()
    files[ROOT / f"{TEST_DIR}/ManagementSparseBodiesGeneratedTest.java"] = emit_sparse_test()
    return files


def prune(files: dict[Path, str]) -> list[Path]:
    """Generated files on disk that this run no longer produces.

    A schema removed upstream would otherwise leave a stale record behind that
    still compiles, still looks generated, and no longer corresponds to
    anything — the one failure mode a per-file generator has that a
    single-file one does not.
    """
    stale: list[Path] = []
    for directory in (ROOT / MODELS_DIR, ROOT / API_DIR):
        if not directory.exists():
            continue
        for existing in directory.glob("*.java"):
            if existing in files:
                continue
            if existing.read_text().startswith("// @generated by scripts/gen_management.py"):
                stale.append(existing)
    return stale


def main() -> int:
    """Write the generated surface, or verify it is current under ``--check``."""
    PROJECTIONS.update(projection_map())
    files = build()
    stale_extra = prune(files)

    if "--check" in sys.argv:
        stale = [p for p, body in files.items() if not p.exists() or p.read_text() != body]
        stale.extend(stale_extra)
        if stale:
            for path in stale:
                print(f"FAIL: {path.relative_to(ROOT)} is stale", file=sys.stderr)
            print("run `python3 scripts/gen_management.py`", file=sys.stderr)
            return 1
        print(f"OK: {len(files)} generated files are current "
              f"({REGISTRY['operation_count']} operations)")
        return 0

    for path in stale_extra:
        path.unlink()
    for path, body in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    print(f"wrote {len(files)} files: {REGISTRY['operation_count']} operations across "
          f"{REGISTRY['namespace_count']} namespaces")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
