// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * API-based provider configuration (SendGrid, Postmark, Resend, Brevo).
 *
 * <p>{@code api_key} follows the same write-only + omit-preserving contract as [{@code
 * SmtpConfig::password}] (D-01/D-02).
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param apiUrl Override base URL (useful for testing / self-hosted instances).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ApiProviderConfig(
        @JsonProperty("api_url") @Nullable String apiUrl
) {

    /**
     * Starts a ApiProviderConfig with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh ApiProviderConfig.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse ApiProviderConfig.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable String apiUrl;

        /**
         * Sets api_url.
         *
         * @param apiUrl the value to send
         * @return this builder
         */
        public Builder apiUrl(String apiUrl) {
            this.apiUrl = apiUrl;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a ApiProviderConfig carrying exactly the fields that were set
         */
        public ApiProviderConfig build() {
            return new ApiProviderConfig(apiUrl);
        }
    }
}
