// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.UUID;

/**
 * The AssignRoleToServiceAccountRequest schema from the server's OpenAPI document.
 *
 * @param inherit Whether the assignment also reaches the descendants of {@code resource_id}.
 *     Omitted — the default — or {@code true} is today's behaviour: a resource-scoped assignment
 *     applies at its resource and everywhere below it. {@code false} applies it at {@code resource_id}
 *     only, "here and no further", for allow and deny grants alike. Refused with 400 when {@code
 *     false} is sent with no {@code resource_id} (a tenant-wide assignment has no node to stop at) or
 *     for a role with {@code is_global: true} (a global role applies everywhere by definition). The
 *     flag is part of the assignment: to change it, unassign and assign again.
 * @param resourceId the server's resource_id field
 * @param serviceAccountId the server's service_account_id field
 * @param tenantScope The tenants this assignment reaches. Only meaningful for an assignment made
 *     in an organization's scope, whose global roles otherwise reach every tenant of the organization;
 *     naming tenants here confines the assignment to those and to nothing else, the organization's own
 *     scope included. Omitted — the default — reaches wherever the role does. Refused with 400 outside
 *     an organization scope, when empty, and when it names a tenant of another organization or the
 *     organization's own scope tenant.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AssignRoleToServiceAccountRequest(
        @JsonProperty("inherit") @Nullable Boolean inherit,
        @JsonProperty("resource_id") @Nullable UUID resourceId,
        @JsonProperty("service_account_id") UUID serviceAccountId,
        @JsonProperty("tenant_scope") @Nullable List<UUID> tenantScope
) {

    /**
     * CONTRACT.md §5.2.3 rule 1: {@code tenant_scope: []} is refused with 400.
     *
     * <p>An assignment that reaches no tenant contributes nothing anywhere, so it is a
     * grant that does not exist rather than a restriction, and the server declines to
     * guess which was meant. Normalising to {@code null} here means both spellings of
     * absent travel the same way — by not appearing, via {@code JsonInclude.NON_NULL}.
     */
    public AssignRoleToServiceAccountRequest {
        if (tenantScope != null && tenantScope.isEmpty()) {
            tenantScope = null;
        }
    }

    /**
     * Whether this binding inherits to descendants, defaulting to {@code true} when the server
     * omitted {@code inherit} (CONTRACT.md §27.13 S-10 rule 3 — a server older than contract 1.51
     * never sends it, and absence means what every assignment has always meant).
     *
     * @return {@code inherit}, or {@code true} when it was absent
     */
    public boolean inherits() {
        return inherit == null || inherit;
    }
}
