// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * What attestation conveyance a registration ceremony requests, and whether the policy is enforced
 * at all.
 *
 * <p>{@code None} is the default and reproduces today's behavior byte-for-byte: {@code evaluate}
 * allows every registration unconditionally, with no MDS lookup (D8 step 1).
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum AttestationMode {
    /** The server's 'none' value. */
    NONE("none"),
    /** The server's 'indirect' value. */
    INDIRECT("indirect"),
    /** The server's 'direct_required' value. */
    DIRECT_REQUIRED("direct_required");

    /** The spelling this value has on the wire. */
    private final String wire;

    AttestationMode(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * @return the server's own spelling of this value
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value is a hard failure rather than a silent null: a newer server sending
     * a value this SDK has never heard of is something a caller needs to know about, not something
     * to swallow.
     *
     * @param value the server's spelling
     * @return the matching AttestationMode
     * @throws IllegalArgumentException if no constant carries that spelling
     */
    @JsonCreator
    public static AttestationMode fromWire(String value) {
        for (AttestationMode candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("unknown AttestationMode value: " + value);
    }
}
