// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * One entry of an SP's attribute mapping table.
 *
 * @param nameFormat The {@code NameFormat}, one of [{@code ATTRIBUTE_NAME_FORMATS}]. {@code None}
 *     leaves the attribute unqualified ({@code unspecified}).
 * @param samlName The {@code Name} of the emitted {@code &lt;saml:Attribute&gt;}. Unique within
 *     one SP, compared exactly (SAML attribute names are case-sensitive).
 * @param source Where the value comes from.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AttributeMapping(
        @JsonProperty("name_format") @Nullable String nameFormat,
        @JsonProperty("saml_name") String samlName,
        @JsonProperty("source") AttributeSource source
) {
}
