// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * The AuditLogEntry schema from the server's OpenAPI document.
 *
 * @param action the server's action field
 * @param actorId the server's actor_id field
 * @param actorType the server's actor_type field
 * @param id the server's id field
 * @param ipAddress the server's ip_address field
 * @param metadata the server's metadata field
 * @param outcome the server's outcome field
 * @param resourceId the server's resource_id field
 * @param tenantId the server's tenant_id field
 * @param timestamp the server's timestamp field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record AuditLogEntry(
        @JsonProperty("action") String action,
        @JsonProperty("actor_id") UUID actorId,
        @JsonProperty("actor_type") ActorType actorType,
        @JsonProperty("id") UUID id,
        @JsonProperty("ip_address") @Nullable String ipAddress,
        @JsonProperty("metadata") JsonNode metadata,
        @JsonProperty("outcome") AuditOutcome outcome,
        @JsonProperty("resource_id") @Nullable UUID resourceId,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("timestamp") OffsetDateTime timestamp
) {
}
