// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FIDO certification level, as recorded in an MDS {@code statusReports} entry's {@code
 * FIDO_CERTIFIED*} status.
 *
 * <p>Variant order is significant: {@code derive(PartialOrd, Ord)} gives {@code L1 &lt; L1Plus
 * &lt; L2 &lt; L2Plus &lt; L3 &lt; L3Plus}, which {@code WebauthnAttestationPolicy::evaluate} (D8
 * step 9) relies on directly for the {@code min_certification} boundary check ({@code entry_level
 * &gt;= policy_min}).
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum CertificationLevel {
    /** The server's 'L1' value. */
    L1("L1"),
    /** The server's 'L1Plus' value. */
    L1PLUS("L1Plus"),
    /** The server's 'L2' value. */
    L2("L2"),
    /** The server's 'L2Plus' value. */
    L2PLUS("L2Plus"),
    /** The server's 'L3' value. */
    L3("L3"),
    /** The server's 'L3Plus' value. */
    L3PLUS("L3Plus");

    /** The spelling this value has on the wire. */
    private final String wire;

    CertificationLevel(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * @return the server's own spelling of this value
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value is a hard failure rather than a silent null: a newer server sending
     * a value this SDK has never heard of is something a caller needs to know about, not something
     * to swallow.
     *
     * @param value the server's spelling
     * @return the matching CertificationLevel
     * @throws IllegalArgumentException if no constant carries that spelling
     */
    @JsonCreator
    public static CertificationLevel fromWire(String value) {
        for (CertificationLevel candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("unknown CertificationLevel value: " + value);
    }
}
