// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Certificate issuance constraints.
 *
 * @param defaultCertValidityDays the server's default_cert_validity_days field
 * @param maxCertValidityDays the server's max_cert_validity_days field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CertificatePolicy(
        @JsonProperty("default_cert_validity_days") Integer defaultCertValidityDays,
        @JsonProperty("max_cert_validity_days") Integer maxCertValidityDays
) {
}
