// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;

/**
 * Whether, and on what terms, a {@code client_id} that is a URL is resolved by fetching the
 * document it names (T21.5, {@code draft-ietf-oauth-client-id-metadata-document}).
 *
 * <p># Why this is one nested policy rather than nine fields
 *
 * <p>Every field here is a term of a single decision — *do we fetch a stranger's URL and make a
 * client out of what comes back* — and none of them means anything without [{@code
 * Self::enabled}]. A tenant that states a CIMD posture states all of it; a tenant that states none
 * inherits its organization's whole posture rather than half of one, which is the only merge that
 * cannot produce a combination neither party wrote.
 *
 * <p># The two fields that can widen, and the seven that cannot
 *
 * <p>[{@code Self::enabled}] and [{@code Self::allow_http}] are **ordered**: a tenant may turn
 * either off but never on, exactly as {@code dynamic_registration} may only move down its ladder.
 * Everything else names *this tenant's* domains or *this tenant's* bounds, and there is no sense
 * in which one tenant's list of trusted publishers is stricter than another's — the same argument
 * [{@code OidcPolicy}] already makes for {@code dcr_allowed_redirect_hosts}.
 *
 * <p># Every bound here is a security control
 *
 * <p>[{@code Self::max_metadata_bytes}], [{@code Self::min_cache_secs}] and [{@code
 * Self::max_cache_secs}] are not tuning knobs. They are, respectively, the ceiling on a read from
 * an attacker-chosen URL, the floor under how often that read may be repeated, and the ceiling on
 * how long its result may be trusted. Each is clamped again in code against the three constants
 * above, so a settings row written by hand cannot lift them.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param allowHttp Permit an {@code http://} {@code client_id} and an {@code http://} fetch.
 *     **Development only, and it does more than its name says.** AXIAM's shared SSRF guard couples the
 *     scheme rule to the address rule — the same seam that lets an integration test point a fetch at a
 *     loopback mock server — so a tenant that allows {@code http} also allows the first hop to resolve
 *     to a private address. Redirect hops are validated strictly whatever this says, and a public
 *     deployment that sets it has removed the control that makes {@code 169.254.169.254} unreachable.
 * @param confidentialOnly Refuse a document whose {@code token_endpoint_auth_method} is {@code
 *     none}. Off by default, because {@code none} is what every MCP desktop client is. A tenant that
 *     turns it on accepts only {@code private_key_jwt} documents, which is the posture for a
 *     deployment whose CIMD clients are servers rather than desktops.
 * @param enabled **Off unless somebody turns it on** (I1). With this {@code false}, a URL-shaped
 *     {@code client_id} is exactly today's unknown client: nothing is fetched, nothing is
 *     materialised, and the ordinary repository lookup answers as it always has.
 * @param maxCacheSecs The ceiling on a document's cache lifetime, in seconds. Clamped to [{@code
 *     CIMD_MAX_CACHE_CEILING_SECS}].
 * @param maxMetadataBytes The hard cap on how many bytes of a document are read, before it is
 *     parsed. Clamped to [{@code CIMD_MAX_METADATA_BYTES_CEILING}].
 * @param minCacheSecs The floor under a document's cache lifetime, in seconds. Clamped to [{@code
 *     CIMD_MIN_CACHE_FLOOR_SECS}].
 * @param restrictSameDomain Require every {@code redirect_uris} host in the document to equal the
 *     host of the {@code client_id} URL itself. **On by default**, because the document says who the
 *     client is and a redirect to somewhere else is the one thing a stolen or mirrored document would
 *     want to change. It is turned **off** for the desktop MCP clients, whose callbacks are on
 *     loopback and therefore can never share a host with a {@code https://} {@code client_id}; {@code
 *     docs/admin/client-id-metadata-documents.md} says so and says why.
 * @param trustedClientIdDomains The hosts whose documents this tenant will fetch at all, as globs
 *     ({@code mcp.example.com}, or {@code *.example.com} for every host under one domain). **An empty
 *     list resolves nothing**, and enabling CIMD while it is empty is refused — see [{@code
 *     validate_cimd_policy}]. That is a deliberate departure from "a URL is a client identifier, so
 *     any URL will do": the fetch is triggered by an unauthenticated request naming the URL, so an
 *     unrestricted list is a request-forgery primitive offered to strangers, bounded only by the SSRF
 *     guard's address rules. Naming the publishers a tenant actually fronts costs one settings field
 *     and removes the class. **{@code *} is refused here, and so is a wildcard over a whole top-level
 *     domain** ({@code *.com}): both are the posture the empty list is refused for, spelled
 *     differently, and a control with no second control behind it cannot have a one-character bypass
 *     and still be the control. It is a floor and not a public-suffix check — {@code *.github.io}
 *     passes, and trusting shared hosting stays the operator's decision, bounded by the per-tenant
 *     quota rather than by this field. {@code *} remains valid in [{@code
 *     CimdPolicy::trusted_redirect_domains}], whose entries are not fetch targets.
 * @param trustedRedirectDomains The hosts a document's {@code redirect_uris} may point at, as
 *     globs. The loopback hosts ({@code 127.0.0.1}, {@code [::1]}, {@code localhost}) are always
 *     allowed, because RFC 8252 §7.3 is how every desktop MCP client receives its callback — so an
 *     empty list is not a refusal of everything, it is "loopback only", which is exactly the Claude
 *     Code and VS Code profile.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CimdPolicy(
        @JsonProperty("allow_http") @Nullable Boolean allowHttp,
        @JsonProperty("confidential_only") @Nullable Boolean confidentialOnly,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("max_cache_secs") @Nullable Long maxCacheSecs,
        @JsonProperty("max_metadata_bytes") @Nullable Long maxMetadataBytes,
        @JsonProperty("min_cache_secs") @Nullable Long minCacheSecs,
        @JsonProperty("restrict_same_domain") @Nullable Boolean restrictSameDomain,
        @JsonProperty("trusted_client_id_domains") @Nullable List<String> trustedClientIdDomains,
        @JsonProperty("trusted_redirect_domains") @Nullable List<String> trustedRedirectDomains
) {

    /**
     * Starts a CimdPolicy with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh CimdPolicy.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse CimdPolicy.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable Boolean allowHttp;
        private @Nullable Boolean confidentialOnly;
        private @Nullable Boolean enabled;
        private @Nullable Long maxCacheSecs;
        private @Nullable Long maxMetadataBytes;
        private @Nullable Long minCacheSecs;
        private @Nullable Boolean restrictSameDomain;
        private @Nullable List<String> trustedClientIdDomains;
        private @Nullable List<String> trustedRedirectDomains;

        /**
         * Sets allow_http.
         *
         * @param allowHttp the value to send
         * @return this builder
         */
        public Builder allowHttp(Boolean allowHttp) {
            this.allowHttp = allowHttp;
            return this;
        }

        /**
         * Sets confidential_only.
         *
         * @param confidentialOnly the value to send
         * @return this builder
         */
        public Builder confidentialOnly(Boolean confidentialOnly) {
            this.confidentialOnly = confidentialOnly;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets max_cache_secs.
         *
         * @param maxCacheSecs the value to send
         * @return this builder
         */
        public Builder maxCacheSecs(Long maxCacheSecs) {
            this.maxCacheSecs = maxCacheSecs;
            return this;
        }

        /**
         * Sets max_metadata_bytes.
         *
         * @param maxMetadataBytes the value to send
         * @return this builder
         */
        public Builder maxMetadataBytes(Long maxMetadataBytes) {
            this.maxMetadataBytes = maxMetadataBytes;
            return this;
        }

        /**
         * Sets min_cache_secs.
         *
         * @param minCacheSecs the value to send
         * @return this builder
         */
        public Builder minCacheSecs(Long minCacheSecs) {
            this.minCacheSecs = minCacheSecs;
            return this;
        }

        /**
         * Sets restrict_same_domain.
         *
         * @param restrictSameDomain the value to send
         * @return this builder
         */
        public Builder restrictSameDomain(Boolean restrictSameDomain) {
            this.restrictSameDomain = restrictSameDomain;
            return this;
        }

        /**
         * Sets trusted_client_id_domains.
         *
         * @param trustedClientIdDomains the value to send
         * @return this builder
         */
        public Builder trustedClientIdDomains(List<String> trustedClientIdDomains) {
            this.trustedClientIdDomains = trustedClientIdDomains;
            return this;
        }

        /**
         * Sets trusted_redirect_domains.
         *
         * @param trustedRedirectDomains the value to send
         * @return this builder
         */
        public Builder trustedRedirectDomains(List<String> trustedRedirectDomains) {
            this.trustedRedirectDomains = trustedRedirectDomains;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a CimdPolicy carrying exactly the fields that were set
         */
        public CimdPolicy build() {
            return new CimdPolicy(allowHttp, confidentialOnly, enabled, maxCacheSecs, maxMetadataBytes, minCacheSecs, restrictSameDomain, trustedClientIdDomains, trustedRedirectDomains);
        }
    }
}
