// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Which security posture a client is registered under (X5.1).
 *
 * <p>This is the FAPI "one switch". FAPI 2.0 is not a single feature but a bundle of constraints —
 * mandatory PAR, mandatory PKCE with {@code S256}, mandatory strong client authentication,
 * mandatory sender-constrained tokens, and a refusal of every relaxation the base specs permit.
 * Encoding them as one profile rather than a dozen independent booleans means an operator cannot
 * register a client that is *nearly* FAPI, and a reviewer can answer "is this client
 * financial-grade?" by reading one field.
 *
 * <p>The same philosophy as the rate-limit postures: ordinary clients see no behaviour change at
 * all, because [{@code Standard}](Self::Standard) is the serde default and every row written
 * before schema v38 decodes to it.
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum ClientProfile {
    /** The server's 'standard' value. */
    STANDARD("standard"),
    /** The server's 'fapi2' value. */
    FAPI2("fapi2"),
    /**
     * A value this SDK's copy of the spec does not list.
     *
     * <p>CONTRACT §27.11 rule 1: an unrecognised value MUST decode rather than failing the
     * response it arrived in. A closed enum turns the next value the server adds into a parse
     * error on the whole {@code list}, taking down every record on the page over one field of one
     * of them -- including the records the caller was actually after.
     *
     * <p>A Java enum constant cannot carry the string it was decoded from, so this one does not
     * pretend to. Its wire spelling is the empty string, which no server value is: fifteen of
     * these enums appear in request bodies, and a read-modify-write that carried an unrecognised
     * value back is refused by the server with a 400 rather than silently writing a spelling it
     * never used. Do not send it deliberately -- read the field, and if it is {&#64;code UNKNOWN},
     * leave it out of the update.
     */
    UNKNOWN("");

    /** The spelling this value has on the wire. */
    private final String wire;

    ClientProfile(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * <p>{&#64;link #UNKNOWN} answers the empty string, which is not a value any server sends.
     * That is deliberate: it is what makes carrying an unrecognised value back into an update a
     * 400 from the server rather than a silent rewrite into a spelling it never used. This
     * accessor cannot throw, because Jackson calls it on every constant while building its
     * deserializer -- a throwing one would break decoding for the whole enum, which is the failure
     * this type exists to avoid.
     *
     * @return the server's own spelling of this value, or the empty string for {@link #UNKNOWN}
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value yields {&#64;link #UNKNOWN} rather than throwing (CONTRACT §27.11
     * rule 1). Failing here would fail the whole response, so one field of one record the caller
     * did not ask about would take down the page. A caller that cares compares against {&#64;code
     * UNKNOWN}; one that does not gets the rest of the record intact.
     *
     * @param value the server's spelling
     * @return the matching ClientProfile, or {@link #UNKNOWN}
     */
    @JsonCreator
    public static ClientProfile fromWire(String value) {
        for (ClientProfile candidate : values()) {
            if (candidate != UNKNOWN && candidate.wire.equals(value)) {
                return candidate;
            }
        }
        return UNKNOWN;
    }
}
