// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC Core §9 naming).
 *
 * <p>Only the methods AXIAM actually implements are representable. There is deliberately no {@code
 * none} variant: every AXIAM client is confidential today (see {@code handle_authorization_code}),
 * and adding a public-client value here before the rest of the server understands one would let an
 * operator register a client whose authentication is silently skipped.
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum ClientAuthMethod {
    /** The server's 'client_secret_post' value. */
    CLIENT_SECRET_POST("client_secret_post"),
    /** The server's 'tls_client_auth' value. */
    TLS_CLIENT_AUTH("tls_client_auth"),
    /** The server's 'self_signed_tls_client_auth' value. */
    SELF_SIGNED_TLS_CLIENT_AUTH("self_signed_tls_client_auth"),
    /** The server's 'private_key_jwt' value. */
    PRIVATE_KEY_JWT("private_key_jwt"),
    /**
     * A value this SDK's copy of the spec does not list.
     *
     * <p>CONTRACT §27.11 rule 1: an unrecognised value MUST decode rather than failing the
     * response it arrived in. A closed enum turns the next value the server adds into a parse
     * error on the whole {@code list}, taking down every record on the page over one field of one
     * of them -- including the records the caller was actually after.
     *
     * <p>A Java enum constant cannot carry the string it was decoded from, so this one does not
     * pretend to. Its wire spelling is the empty string, which no server value is: fifteen of
     * these enums appear in request bodies, and a read-modify-write that carried an unrecognised
     * value back is refused by the server with a 400 rather than silently writing a spelling it
     * never used. Do not send it deliberately -- read the field, and if it is {&#64;code UNKNOWN},
     * leave it out of the update.
     */
    UNKNOWN("");

    /** The spelling this value has on the wire. */
    private final String wire;

    ClientAuthMethod(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * <p>{&#64;link #UNKNOWN} answers the empty string, which is not a value any server sends.
     * That is deliberate: it is what makes carrying an unrecognised value back into an update a
     * 400 from the server rather than a silent rewrite into a spelling it never used. This
     * accessor cannot throw, because Jackson calls it on every constant while building its
     * deserializer -- a throwing one would break decoding for the whole enum, which is the failure
     * this type exists to avoid.
     *
     * @return the server's own spelling of this value, or the empty string for {@link #UNKNOWN}
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value yields {&#64;link #UNKNOWN} rather than throwing (CONTRACT §27.11
     * rule 1). Failing here would fail the whole response, so one field of one record the caller
     * did not ask about would take down the page. A caller that cares compares against {&#64;code
     * UNKNOWN}; one that does not gets the rest of the record intact.
     *
     * @param value the server's spelling
     * @return the matching ClientAuthMethod, or {@link #UNKNOWN}
     */
    @JsonCreator
    public static ClientAuthMethod fromWire(String value) {
        for (ClientAuthMethod candidate : values()) {
            if (candidate != UNKNOWN && candidate.wire.equals(value)) {
                return candidate;
            }
        }
        return UNKNOWN;
    }
}
