// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;

/**
 * One consent record, as the subject sees it.
 *
 * @param acceptedAt the server's accepted_at field
 * @param consentType What was consented to, e.g. {@code terms_of_service} or {@code
 *     oidc_scope_release:&lt;client_id&gt;}.
 * @param version The document version or, for a scope release, the consented scopes.
 * @param withdrawable Whether this record can be withdrawn here. {@code false} for {@code
 *     terms_of_service}: withdrawing it is not a consent operation but an erasure, and it has its own
 *     endpoint with its own grace period. Reported rather than silently absent so the self-service
 *     page can show the record and explain it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ConsentView(
        @JsonProperty("accepted_at") OffsetDateTime acceptedAt,
        @JsonProperty("consent_type") String consentType,
        @JsonProperty("version") String version,
        @JsonProperty("withdrawable") Boolean withdrawable
) {
}
