// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

/**
 * The CreateResourceRequest schema from the server's OpenAPI document.
 *
 * @param metadata the server's metadata field
 * @param name the server's name field
 * @param parentId the server's parent_id field
 * @param resourceType the server's resource_type field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateResourceRequest(
        @JsonProperty("metadata") @Nullable JsonNode metadata,
        @JsonProperty("name") String name,
        @JsonProperty("parent_id") @Nullable UUID parentId,
        @JsonProperty("resource_type") String resourceType
) {
}
