// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * Body of {@code POST .../tenants/{tenant_id}/signing-cas}.
 *
 * @param keyAlgorithm the server's key_algorithm field
 * @param parentCaId The organization CA that signs it.
 * @param subject Subject for the signing CA, e.g. {@code CN=ACME R&amp;D Signing CA}.
 * @param validityDays Validity duration in days, capped to the parent's own expiry.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateIntermediateCaRequest(
        @JsonProperty("key_algorithm") KeyAlgorithm keyAlgorithm,
        @JsonProperty("parent_ca_id") UUID parentCaId,
        @JsonProperty("subject") String subject,
        @JsonProperty("validity_days") Integer validityDays
) {
}
