// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;

/**
 * The CreateOAuth2ClientRequest schema from the server's OpenAPI document.
 *
 * @param backchannelLogoutUri B5 — where OIDC back-channel logout tokens are delivered. Omit for a
 *     client that does not participate.
 * @param dpopBoundAccessTokens RFC 9449 §5.2 — issue DPoP-bound (sender-constrained) access tokens
 *     to this client. Independent of both the authentication method and {@code
 *     tls_client_certificate_bound_access_tokens}; a client may ask for both constraints, and a token
 *     carrying both must satisfy both.
 * @param dpopRequireNonce RFC 9449 §8 — require this client's DPoP proofs to carry a server-issued
 *     nonce. **Not implemented in this build (SEC-097).** {@code true} is refused with {@code 400};
 *     only {@code false} (the default) is accepted. Nothing reads the stored value, so accepting
 *     {@code true} would persist and echo back a security switch that does nothing. DPoP proofs are
 *     made single-use at the token endpoint by {@code jti} replay detection instead — see {@code
 *     docs/security-profiles.md}.
 * @param grantTypes Grant types this client is authorized to use.
 * @param jwks RFC 7591 §2 — the client's public key set, inline, for {@code private_key_jwt}.
 *     Exactly one of {@code jwks} and {@code jwks_uri} may be set.
 * @param jwksUri RFC 7591 §2 — where the client publishes its public key set. Must be an absolute
 *     {@code https} URL, and is fetched through the SSRF-guarded JWKS cache, which refuses private and
 *     loopback addresses.
 * @param name Human-readable name for the client.
 * @param postLogoutRedirectUris B5 — allow-list for RP-initiated logout's {@code
 *     post_logout_redirect_uri}. Separate from {@code redirect_uris} on purpose: that list receives
 *     authorization codes, this one receives a browser after logout.
 * @param profile X5.1 — the security posture this client is registered under. {@code "standard"}
 *     (the default) is every AXIAM client that has ever existed. {@code "fapi2"} turns on the whole
 *     FAPI 2.0 constraint bundle at once, and the registration is refused unless it also sets {@code
 *     require_par}, a strong {@code token_endpoint_auth_method} (either mTLS method or {@code
 *     private_key_jwt}), and at least one sender-constraining mechanism ({@code
 *     tls_client_certificate_bound_access_tokens} or {@code dpop_bound_access_tokens}). See the FAPI
 *     operator guide.
 * @param redirectUris Allowed redirect URIs (must be HTTPS, except localhost for dev). SEC-089:
 *     this list doubles as the token-exchange audience allow-list — adding a URI here also authorises
 *     it as a token audience for this client, so review additions on exchange-capable clients with
 *     that in mind (see {@code docs/api/token-exchange.md#audience}).
 * @param requirePar B5 — require this client to push its authorization parameters to {@code
 *     /oauth2/par} (RFC 9126) rather than sending them through the browser.
 * @param scopes Scopes the client may request.
 * @param selfSignedTlsClientAuthThumbprints Accepted certificate thumbprints for {@code
 *     self_signed_tls_client_auth}, as base64url-unpadded SHA-256 digests of the DER certificate (the
 *     same {@code x5t#S256} encoding as the {@code cnf} claim). More than one permits an overlapping
 *     rotation.
 * @param tlsClientAuthSanDns RFC 8705 §2.1.2 — expected {@code dNSName} SAN.
 * @param tlsClientAuthSanUri RFC 8705 §2.1.2 — expected {@code uniformResourceIdentifier} SAN.
 * @param tlsClientAuthSubjectDn RFC 8705 §2.1.2 — expected certificate subject DN, RFC 4514 form.
 *     Exactly one of the three {@code tls_client_auth_*} parameters may be set.
 * @param tlsClientCertificateBoundAccessTokens RFC 8705 §3.4 — issue certificate-bound
 *     (sender-constrained) access tokens to this client. Independent of the authentication method.
 * @param tokenEndpointAuthMethod X5.1 — how this client authenticates at the token endpoint (RFC
 *     8705 §2). Defaults to {@code client_secret_post}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateOAuth2ClientRequest(
        @JsonProperty("backchannel_logout_uri") @Nullable String backchannelLogoutUri,
        @JsonProperty("dpop_bound_access_tokens") @Nullable Boolean dpopBoundAccessTokens,
        @JsonProperty("dpop_require_nonce") @Nullable Boolean dpopRequireNonce,
        @JsonProperty("grant_types") List<String> grantTypes,
        @JsonProperty("jwks") @Nullable String jwks,
        @JsonProperty("jwks_uri") @Nullable String jwksUri,
        @JsonProperty("name") String name,
        @JsonProperty("post_logout_redirect_uris") @Nullable List<String> postLogoutRedirectUris,
        @JsonProperty("profile") @Nullable ClientProfile profile,
        @JsonProperty("redirect_uris") List<String> redirectUris,
        @JsonProperty("require_par") @Nullable Boolean requirePar,
        @JsonProperty("scopes") List<String> scopes,
        @JsonProperty("self_signed_tls_client_auth_thumbprints") @Nullable List<String> selfSignedTlsClientAuthThumbprints,
        @JsonProperty("tls_client_auth_san_dns") @Nullable String tlsClientAuthSanDns,
        @JsonProperty("tls_client_auth_san_uri") @Nullable String tlsClientAuthSanUri,
        @JsonProperty("tls_client_auth_subject_dn") @Nullable String tlsClientAuthSubjectDn,
        @JsonProperty("tls_client_certificate_bound_access_tokens") @Nullable Boolean tlsClientCertificateBoundAccessTokens,
        @JsonProperty("token_endpoint_auth_method") @Nullable ClientAuthMethod tokenEndpointAuthMethod
) {
}
