// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

/**
 * The CreateCertificateRequest schema from the server's OpenAPI document.
 *
 * @param certType the server's cert_type field
 * @param issuerCaId the server's issuer_ca_id field
 * @param keyAlgorithm the server's key_algorithm field
 * @param metadata the server's metadata field
 * @param subject the server's subject field
 * @param validityDays Validity duration in days.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateCertificateRequest(
        @JsonProperty("cert_type") CertificateType certType,
        @JsonProperty("issuer_ca_id") UUID issuerCaId,
        @JsonProperty("key_algorithm") KeyAlgorithm keyAlgorithm,
        @JsonProperty("metadata") @Nullable JsonNode metadata,
        @JsonProperty("subject") String subject,
        @JsonProperty("validity_days") Integer validityDays
) {
}
