// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import io.axiam.sdk.Sensitive;

/**
 * The CreateUserRequest schema from the server's OpenAPI document.
 *
 * @param email the server's email field
 * @param metadata the server's metadata field
 * @param opaque the server's opaque field
 * @param password the server's password field -- SECRET: redacted from toString and from every
 *     JSON rendering except the one request body it is sent in
 * @param username the server's username field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateUserRequest(
        @JsonProperty("email") String email,
        @JsonProperty("metadata") @Nullable JsonNode metadata,
        @JsonProperty("opaque") @Nullable OpaqueEnrollment opaque,
        @JsonProperty("password") Sensitive password,
        @JsonProperty("username") String username
) {
}
