// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The CreateCaCertificateRequest schema from the server's OpenAPI document.
 *
 * @param intermediateSubject Common name for the signing intermediate — {@code vault_pki} custody
 *     only. Under that custodian Vault generates a root and an intermediate beneath it, and this names
 *     the second. Defaults to the root's subject with {@code Intermediate Authority} appended. Ignored
 *     by every other custodian, which produces one self-signed CA and has no second certificate to
 *     name.
 * @param intermediateValidityDays Validity of the signing intermediate, in days. Defaults to the
 *     root's.
 * @param issueFromRoot Issue leaves straight from the generated root instead of creating an
 *     intermediate. {@code vault_pki} custody only, and off by default. The default is the safer one:
 *     a root that signs only an intermediate can have that intermediate revoked and replaced without
 *     redistributing the trust anchor, and a root that signs leaves cannot.
 * @param keyAlgorithm the server's key_algorithm field
 * @param subject the server's subject field
 * @param validityDays Validity duration in days.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateCaCertificateRequest(
        @JsonProperty("intermediate_subject") @Nullable String intermediateSubject,
        @JsonProperty("intermediate_validity_days") @Nullable Integer intermediateValidityDays,
        @JsonProperty("issue_from_root") @Nullable Boolean issueFromRoot,
        @JsonProperty("key_algorithm") KeyAlgorithm keyAlgorithm,
        @JsonProperty("subject") String subject,
        @JsonProperty("validity_days") Integer validityDays
) {
}
