// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * Request body for [{@code create_registration_token}].
 *
 * @param expiresInHours Lifetime in hours. Defaults to 24 and is refused above 168 (a week) — see
 *     {@code axiam_core::models::oauth2_registration_token}.
 * @param name Operator-facing label, e.g. {@code "mcp-inspector-demo"}, so a tenant with several
 *     outstanding tokens can tell them apart.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateRegistrationTokenRequest(
        @JsonProperty("expires_in_hours") @Nullable Integer expiresInHours,
        @JsonProperty("name") String name
) {
}
