// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.UUID;

/**
 * The CreateScimTokenRequest schema from the server's OpenAPI document.
 *
 * @param expiresInDays Lifetime in days. Defaults to the deployment maximum, and is refused above
 *     it.
 * @param name Operator-facing label, e.g. {@code "okta-production"}.
 * @param userId The tenant user the token authenticates as. Must already hold {@code
 *     scim:provision} — see [{@code create}].
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record CreateScimTokenRequest(
        @JsonProperty("expires_in_days") @Nullable Long expiresInDays,
        @JsonProperty("name") String name,
        @JsonProperty("user_id") UUID userId
) {
}
