// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Email verification requirements.
 *
 * @param emailVerificationGracePeriodHours the server's email_verification_grace_period_hours
 *     field
 * @param emailVerificationRequired the server's email_verification_required field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record EmailVerificationPolicy(
        @JsonProperty("email_verification_grace_period_hours") Integer emailVerificationGracePeriodHours,
        @JsonProperty("email_verification_required") Boolean emailVerificationRequired
) {
}
