// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * Result of encrypting data with a PGP public key.
 *
 * @param ciphertextArmored ASCII-armored PGP encrypted data.
 * @param recipientKeyId the server's recipient_key_id field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record EncryptedExport(
        @JsonProperty("ciphertext_armored") String ciphertextArmored,
        @JsonProperty("recipient_key_id") UUID recipientKeyId
) {
}
