// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Federation config response -- omits client_secret.
 *
 * @param attributeMap the server's attribute_map field
 * @param clientId the server's client_id field
 * @param createdAt the server's created_at field
 * @param enabled the server's enabled field
 * @param id the server's id field
 * @param metadataUrl the server's metadata_url field
 * @param protocol the server's protocol field
 * @param provider the server's provider field
 * @param tenantId the server's tenant_id field
 * @param tokenExchange X4 external token-exchange trust.
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record FederationConfigResponse(
        @JsonProperty("attribute_map") JsonNode attributeMap,
        @JsonProperty("client_id") String clientId,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("id") UUID id,
        @JsonProperty("metadata_url") @Nullable String metadataUrl,
        @JsonProperty("protocol") String protocol,
        @JsonProperty("provider") String provider,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("token_exchange") TokenExchangeTrustResponse tokenExchange,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
