// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * One row of the group-mapping table (G-3, T23.3.4, D-30): a directory group, named by its
 * distinguished name, and the AXIAM group a member of it is put into.
 *
 * <p>**The table is the only way a directory group reaches an AXIAM group.** There is no match by
 * name, no prefix or wildcard, and no AXIAM group is ever created from a directory one: a
 * directory administrator who names a group {@code admins} gains nothing unless a tenant
 * administrator mapped it here.
 *
 * <p>The DN is stored as the administrator typed it and compared after RFC 4514 normalisation
 * ({@code axiam_directory::dn}), so {@code CN=Staff, OU=Groups} and {@code cn=staff,ou=groups} are
 * the same row. One DN may map to several AXIAM groups; the same (DN, group) pair twice is refused
 * as redundant.
 *
 * @param directoryGroupDn The directory group's distinguished name.
 * @param groupId The AXIAM group of the same tenant a member of that directory group is put into.
 *     Checked to exist in the tenant when the configuration is written.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record GroupMapping(
        @JsonProperty("directory_group_dn") String directoryGroupDn,
        @JsonProperty("group_id") UUID groupId
) {
}
