// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A group of users that can access resources based on their roles and permissions. Groups simplify
 * role management by allowing roles to be assigned to a group rather than individual users.
 *
 * @param createdAt the server's created_at field
 * @param description the server's description field
 * @param id the server's id field
 * @param metadata the server's metadata field
 * @param name the server's name field
 * @param tenantId the server's tenant_id field
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Group(
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("description") String description,
        @JsonProperty("id") UUID id,
        @JsonProperty("metadata") JsonNode metadata,
        @JsonProperty("name") String name,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
