// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.UUID;

/**
 * {@code POST …/saml/idp-credentials} body.
 *
 * @param issuerCaId An active signing CA the caller may issue from.
 * @param slot The slot to fill; it must be empty.
 * @param validityDays 1 to 730, default 365; never beyond the CA's own expiry.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record IssueSamlIdpCredential(
        @JsonProperty("issuer_ca_id") UUID issuerCaId,
        @JsonProperty("slot") SamlIdpSlot slot,
        @JsonProperty("validity_days") @Nullable Long validityDays
) {
}
