// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The 'rollback_rejected' arm of MdsRefreshOutcome.
 *
 * @param outcome the discriminator, always 'rollback_rejected'
 * @param attemptedNo the server's attempted_no field
 * @param storedNo the server's stored_no field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MdsRefreshOutcomeRollbackRejected(
        @JsonProperty("outcome") String outcome,
        @JsonProperty("attempted_no") Long attemptedNo,
        @JsonProperty("stored_no") Long storedNo
) implements MdsRefreshOutcome {
}
