// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The 'no_op_refresh' arm of MdsRefreshOutcome.
 *
 * @param outcome the discriminator, always 'no_op_refresh'
 * @param no the server's no field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MdsRefreshOutcomeNoOpRefresh(
        @JsonProperty("outcome") String outcome,
        @JsonProperty("no") Long no
) implements MdsRefreshOutcome {
}
