// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;

/**
 * {@code GET /api/v1/mds/status} response. {@code no}/{@code next_update}/{@code
 * last_refreshed_at} are {@code None} and {@code stale} is {@code false} when MDS has never been
 * ingested — a meaningful, valid answer ("nothing ingested yet"), not an error.
 *
 * @param entryCount the server's entry_count field
 * @param lastRefreshedAt the server's last_refreshed_at field
 * @param nextUpdate the server's next_update field
 * @param no the server's no field
 * @param stale the server's stale field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MdsStatusResponse(
        @JsonProperty("entry_count") Long entryCount,
        @JsonProperty("last_refreshed_at") @Nullable OffsetDateTime lastRefreshedAt,
        @JsonProperty("next_update") @Nullable String nextUpdate,
        @JsonProperty("no") @Nullable Long no,
        @JsonProperty("stale") Boolean stale
) {
}
