// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.UUID;

/**
 * The acknowledgement, which is mostly about the restart.
 *
 * @param caCertificateId The CA this is about.
 * @param message A sentence an operator can act on, rather than a bare boolean.
 * @param mtlsTrustAnchor The flag as now stored.
 * @param restartRequired Whether the change still needs a restart to take effect. {@code false}
 *     when the live listener accepted the new anchor set — the ordinary case on a TLS deployment.
 *     {@code true} only when there was no listener to reload into (plaintext, or {@code client_auth =
 *     off}), where the flag is stored and applies at the next start.
 * @param trustedAnchors How many CAs the listener now trusts for client authentication, when it
 *     was reloaded. {@code None} when nothing was reloaded.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MtlsTrustAnchorResponse(
        @JsonProperty("ca_certificate_id") UUID caCertificateId,
        @JsonProperty("message") String message,
        @JsonProperty("mtls_trust_anchor") Boolean mtlsTrustAnchor,
        @JsonProperty("restart_required") Boolean restartRequired,
        @JsonProperty("trusted_anchors") @Nullable Integer trustedAnchors
) {
}
