// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * The acknowledgement, which is mostly about the restart.
 *
 * @param caCertificateId The CA this is about.
 * @param message A sentence an operator can act on, rather than a bare boolean.
 * @param mtlsTrustAnchor The flag as now stored.
 * @param restartRequired Always {@code true}: rustls builds its client trust store once, when the
 *     listener is constructed, so this takes effect at the next start.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record MtlsTrustAnchorResponse(
        @JsonProperty("ca_certificate_id") UUID caCertificateId,
        @JsonProperty("message") String message,
        @JsonProperty("mtls_trust_anchor") Boolean mtlsTrustAnchor,
        @JsonProperty("restart_required") Boolean restartRequired
) {
}
