// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Events that can trigger an admin notification.
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum NotificationEventType {
    /** The server's 'login_failure' value. */
    LOGIN_FAILURE("login_failure"),
    /** The server's 'account_locked' value. */
    ACCOUNT_LOCKED("account_locked"),
    /** The server's 'mfa_enrollment_changed' value. */
    MFA_ENROLLMENT_CHANGED("mfa_enrollment_changed"),
    /** The server's 'password_changed' value. */
    PASSWORD_CHANGED("password_changed"),
    /** The server's 'password_reset_requested' value. */
    PASSWORD_RESET_REQUESTED("password_reset_requested"),
    /** The server's 'role_assigned' value. */
    ROLE_ASSIGNED("role_assigned"),
    /** The server's 'role_unassigned' value. */
    ROLE_UNASSIGNED("role_unassigned"),
    /** The server's 'permission_granted' value. */
    PERMISSION_GRANTED("permission_granted"),
    /** The server's 'permission_revoked' value. */
    PERMISSION_REVOKED("permission_revoked"),
    /** The server's 'certificate_issued' value. */
    CERTIFICATE_ISSUED("certificate_issued"),
    /** The server's 'certificate_revoked' value. */
    CERTIFICATE_REVOKED("certificate_revoked"),
    /** The server's 'ca_certificate_revoked' value. */
    CA_CERTIFICATE_REVOKED("ca_certificate_revoked"),
    /** The server's 'user_created' value. */
    USER_CREATED("user_created"),
    /** The server's 'user_deleted' value. */
    USER_DELETED("user_deleted"),
    /** The server's 'user_updated' value. */
    USER_UPDATED("user_updated"),
    /** The server's 'service_account_created' value. */
    SERVICE_ACCOUNT_CREATED("service_account_created"),
    /** The server's 'service_account_deleted' value. */
    SERVICE_ACCOUNT_DELETED("service_account_deleted");

    /** The spelling this value has on the wire. */
    private final String wire;

    NotificationEventType(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * @return the server's own spelling of this value
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value is a hard failure rather than a silent null: a newer server sending
     * a value this SDK has never heard of is something a caller needs to know about, not something
     * to swallow.
     *
     * @param value the server's spelling
     * @return the matching NotificationEventType
     * @throws IllegalArgumentException if no constant carries that spelling
     */
    @JsonCreator
    public static NotificationEventType fromWire(String value) {
        for (NotificationEventType candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("unknown NotificationEventType value: " + value);
    }
}
