// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;
import io.axiam.sdk.Sensitive;

/**
 * Response for client creation -- includes the one-time plaintext secret.
 *
 * @param clientId the server's client_id field
 * @param clientSecret the server's client_secret field -- SECRET: redacted from toString and from
 *     every JSON rendering except the one request body it is sent in
 * @param createdAt the server's created_at field
 * @param grantTypes the server's grant_types field
 * @param id the server's id field
 * @param name the server's name field
 * @param redirectUris the server's redirect_uris field
 * @param scopes the server's scopes field
 * @param tenantId the server's tenant_id field
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record OAuth2ClientCreatedResponse(
        @JsonProperty("client_id") String clientId,
        @JsonProperty("client_secret") Sensitive clientSecret,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("grant_types") List<String> grantTypes,
        @JsonProperty("id") UUID id,
        @JsonProperty("name") String name,
        @JsonProperty("redirect_uris") List<String> redirectUris,
        @JsonProperty("scopes") List<String> scopes,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
