// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * OAuth2 client response -- omits client_secret_hash.
 *
 * @param clientId the server's client_id field
 * @param createdAt the server's created_at field
 * @param dpopBoundAccessTokens the server's dpop_bound_access_tokens field
 * @param dpopRequireNonce the server's dpop_require_nonce field
 * @param grantTypes the server's grant_types field
 * @param id the server's id field
 * @param jwks X5.1 — echoed so an operator can confirm which key source is registered. The
 *     document itself is public key material, so returning it leaks nothing; a {@code jwks_uri} is
 *     likewise public by construction.
 * @param jwksUri the server's jwks_uri field
 * @param name the server's name field
 * @param profile X5.1 — the registered posture and mTLS credentials. Read-back matters: an
 *     operator auditing which clients are financial-grade should be able to answer it from this
 *     endpoint rather than from the database.
 * @param redirectUris the server's redirect_uris field
 * @param requirePar the server's require_par field
 * @param scopes the server's scopes field
 * @param selfSignedTlsClientAuthThumbprints the server's self_signed_tls_client_auth_thumbprints
 *     field
 * @param tenantId the server's tenant_id field
 * @param tlsClientAuthSanDns the server's tls_client_auth_san_dns field
 * @param tlsClientAuthSanUri the server's tls_client_auth_san_uri field
 * @param tlsClientAuthSubjectDn the server's tls_client_auth_subject_dn field
 * @param tlsClientCertificateBoundAccessTokens the server's
 *     tls_client_certificate_bound_access_tokens field
 * @param tokenEndpointAuthMethod the server's token_endpoint_auth_method field
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record OAuth2ClientResponse(
        @JsonProperty("client_id") String clientId,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("dpop_bound_access_tokens") Boolean dpopBoundAccessTokens,
        @JsonProperty("dpop_require_nonce") Boolean dpopRequireNonce,
        @JsonProperty("grant_types") List<String> grantTypes,
        @JsonProperty("id") UUID id,
        @JsonProperty("jwks") @Nullable String jwks,
        @JsonProperty("jwks_uri") @Nullable String jwksUri,
        @JsonProperty("name") String name,
        @JsonProperty("profile") ClientProfile profile,
        @JsonProperty("redirect_uris") List<String> redirectUris,
        @JsonProperty("require_par") Boolean requirePar,
        @JsonProperty("scopes") List<String> scopes,
        @JsonProperty("self_signed_tls_client_auth_thumbprints") List<String> selfSignedTlsClientAuthThumbprints,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("tls_client_auth_san_dns") @Nullable String tlsClientAuthSanDns,
        @JsonProperty("tls_client_auth_san_uri") @Nullable String tlsClientAuthSanUri,
        @JsonProperty("tls_client_auth_subject_dn") @Nullable String tlsClientAuthSubjectDn,
        @JsonProperty("tls_client_certificate_bound_access_tokens") Boolean tlsClientCertificateBoundAccessTokens,
        @JsonProperty("token_endpoint_auth_method") ClientAuthMethod tokenEndpointAuthMethod,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
