// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * The OidcCallbackRequest schema from the server's OpenAPI document.
 *
 * @param code Authorization code returned by the external IdP.
 * @param configId ID of the federation config used in the authorization request.
 * @param nonce Client-supplied nonce (SECHRD-07/D-04: retained for backward compatibility with
 *     older callers, but IGNORED for verification — {@code expected_nonce} always comes from the
 *     server-side {@code FederationLoginState} row looked up via {@code state}, never from this
 *     field).
 * @param redirectUri Redirect URI that was used in the authorization request.
 * @param state CSRF state value from the authorization request. Used to look up the server-side
 *     {@code FederationLoginState} row that holds the real nonce (SECHRD-07/D-04) — required so the
 *     callback can find its login state.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record OidcCallbackRequest(
        @JsonProperty("code") String code,
        @JsonProperty("config_id") UUID configId,
        @JsonProperty("nonce") String nonce,
        @JsonProperty("redirect_uri") String redirectUri,
        @JsonProperty("state") String state
) {
}
