// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * The OidcAuthorizeRequest schema from the server's OpenAPI document.
 *
 * @param configId ID of the federation config to use.
 * @param nonce Nonce for replay protection (generated by the caller).
 * @param redirectUri Redirect URI the external IdP should return the user to.
 * @param state CSRF state value (generated by the caller).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record OidcAuthorizeRequest(
        @JsonProperty("config_id") UUID configId,
        @JsonProperty("nonce") String nonce,
        @JsonProperty("redirect_uri") String redirectUri,
        @JsonProperty("state") String state
) {
}
