// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Secure Remote Password policy.
 *
 * <p>{@code suite} and {@code ksf} are the parameters a *new* registration record is enrolled
 * with. They deliberately do not apply retroactively: an existing record is only valid under the
 * suite and KSF it was created with, so tightening these takes effect as users next set a password
 * rather than invalidating everybody at once.
 *
 * @param opaqueKsf Key-stretching function new records are enrolled under. Both variants are
 *     memory-hard; see [{@code opaque_ksf_is_at_least}] for the tighten-only ordering.
 * @param opaqueMode Whether OPAQUE is offered, and whether password login is still accepted.
 * @param opaqueSuite RFC 9807 ciphersuite new records are enrolled under.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record OpaquePolicy(
        @JsonProperty("opaque_ksf") String opaqueKsf,
        @JsonProperty("opaque_mode") String opaqueMode,
        @JsonProperty("opaque_suite") String opaqueSuite
) {
}
