// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * {@code POST …/saml/parse-sp-metadata} body: **exactly one** of the two members.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param metadataUrl An {@code https} URL the server fetches the document from, once, through its
 *     SSRF guard.
 * @param metadataXml A metadata document, at most 512 KiB.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ParseSamlSpMetadata(
        @JsonProperty("metadata_url") @Nullable String metadataUrl,
        @JsonProperty("metadata_xml") @Nullable String metadataXml
) {

    /**
     * Starts a ParseSamlSpMetadata with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh ParseSamlSpMetadata.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse ParseSamlSpMetadata.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable String metadataUrl;
        private @Nullable String metadataXml;

        /**
         * Sets metadata_url.
         *
         * @param metadataUrl the value to send
         * @return this builder
         */
        public Builder metadataUrl(String metadataUrl) {
            this.metadataUrl = metadataUrl;
            return this;
        }

        /**
         * Sets metadata_xml.
         *
         * @param metadataXml the value to send
         * @return this builder
         */
        public Builder metadataXml(String metadataXml) {
            this.metadataXml = metadataXml;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a ParseSamlSpMetadata carrying exactly the fields that were set
         */
        public ParseSamlSpMetadata build() {
            return new ParseSamlSpMetadata(metadataUrl, metadataXml);
        }
    }
}
