// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whether a grant permits an action or refuses it (B1, deny-override).
 *
 * <p># Precedence
 *
 * <p>Default deny -&gt; an [{@code PermissionEffect::Allow}] grant permits -&gt; a [{@code
 * PermissionEffect::Deny}] grant refuses, **and beats every allow**, wherever either sits in the
 * resource hierarchy. Deny wins; there is no most-specific-wins tie-break.
 *
 * <p>That choice is deliberate and is argued in full in {@code claude_dev/deny-override-design.md}
 * §2.1. The short version: deny-override buys one checkable property — **adding a deny rule can
 * never widen access, and can never be undone by adding allows** — and most-specific-wins buys
 * expressiveness at the cost of making "is X denied?" unanswerable without enumerating every other
 * rule that might out-specify it.
 *
 * <p>[{@code PermissionEffect::Allow}] is the default, so data written before this existed, and
 * clients that send no {@code effect}, both mean "allow". No migration.
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum PermissionEffect {
    /** The server's 'allow' value. */
    ALLOW("allow"),
    /** The server's 'deny' value. */
    DENY("deny");

    /** The spelling this value has on the wire. */
    private final String wire;

    PermissionEffect(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * @return the server's own spelling of this value
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value is a hard failure rather than a silent null: a newer server sending
     * a value this SDK has never heard of is something a caller needs to know about, not something
     * to swallow.
     *
     * @param value the server's spelling
     * @return the matching PermissionEffect
     * @throws IllegalArgumentException if no constant carries that spelling
     */
    @JsonCreator
    public static PermissionEffect fromWire(String value) {
        for (PermissionEffect candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("unknown PermissionEffect value: " + value);
    }
}
