// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.UUID;

/**
 * {@code GET} response: the stored policy plus the unknown-AAGUID action it currently *resolves
 * to*.
 *
 * <p>{@code unknown_aaguid} is nullable, where {@code null} means "use this mode's default" (deny
 * under {@code direct_required}, allow otherwise). A client that only saw the stored {@code null}
 * would have to re-derive that rule itself to display what the policy actually does — and a
 * security rule implemented twice is a security rule that will eventually disagree with itself. So
 * the server resolves it once, here, and reports both: the admin's stored intent and its effect.
 *
 * @param allowedAaguids {@code None} = every AAGUID is allowed except {@code blocked_aaguids}.
 *     {@code Some(vec![])} is a deliberate "nothing may register" policy and is accepted as such:
 *     {@code evaluate} denies every AAGUID against an empty allow-list. Nothing rejects it, precisely
 *     because the failure direction is safe — a client that sends {@code []} when it meant {@code
 *     null} gets a locked-down tenant, which is visible immediately, rather than an open one, which is
 *     not.
 * @param blockRevokedStatus Deny registration if the MDS entry has ever reported {@code REVOKED}
 *     or any {@code *_COMPROMISE} status (sticky — D8 step 7).
 * @param blockedAaguids the server's blocked_aaguids field
 * @param effectiveUnknownAaguid The action actually applied to an AAGUID with no MDS metadata,
 *     with {@code unknown_aaguid: null} resolved against {@code mode}. Read-only — {@code PUT} ignores
 *     it.
 * @param minCertification the server's min_certification field
 * @param mode the server's mode field
 * @param requireFidoCertified Require *some* {@code FIDO_CERTIFIED*} status, any level.
 *     Independent of (and checked before) {@code min_certification}.
 * @param unknownAaguid the server's unknown_aaguid field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record PolicyResponse(
        @JsonProperty("allowed_aaguids") @Nullable List<UUID> allowedAaguids,
        @JsonProperty("block_revoked_status") Boolean blockRevokedStatus,
        @JsonProperty("blocked_aaguids") @Nullable List<UUID> blockedAaguids,
        @JsonProperty("effective_unknown_aaguid") UnknownAaguidAction effectiveUnknownAaguid,
        @JsonProperty("min_certification") @Nullable CertificationLevel minCertification,
        @JsonProperty("mode") AttestationMode mode,
        @JsonProperty("require_fido_certified") Boolean requireFidoCertified,
        @JsonProperty("unknown_aaguid") @Nullable UnknownAaguidAction unknownAaguid
) {
}
