// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SMTP-specific configuration.
 *
 * <p>{@code password} is write-only (D-01): {@code #[serde(skip_serializing)]} means it is never
 * emitted in a GET/serialized response. On the write path (D-02), {@code #[serde(default)]} lets a
 * caller omit the field entirely (deserializing to {@code ""}); an empty string is the sentinel
 * for "no new secret supplied — preserve whatever is already stored" (see {@code
 * SurrealEmailConfigRepository:: set_org_config}). A non-empty value is a real secret to
 * encrypt+replace.
 *
 * @param kind the discriminator, always 'smtp'
 * @param host the server's host field
 * @param port the server's port field
 * @param starttls Use STARTTLS (true) or implicit TLS (false).
 * @param username the server's username field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ProviderConfigSmtp(
        @JsonProperty("kind") String kind,
        @JsonProperty("host") String host,
        @JsonProperty("port") Integer port,
        @JsonProperty("starttls") Boolean starttls,
        @JsonProperty("username") String username
) implements ProviderConfig {
}
