// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * The ReactorResponse schema from the server's OpenAPI document.
 *
 * @param createdAt the server's created_at field
 * @param description the server's description field
 * @param enabled the server's enabled field
 * @param events the server's events field
 * @param failurePolicy the server's failure_policy field
 * @param id the server's id field
 * @param lastSeenAt When this reactor last consumed from its queue. {@code null} means it has
 *     never connected — which the admin UI shows differently from "connected once, silent since".
 * @param mode the server's mode field
 * @param name the server's name field
 * @param priority the server's priority field
 * @param recentTimeoutCount R2.3: dispatch failures against this registration in the last 24h
 *     whose cause was a timeout (as opposed to a rejected reply, a transport failure, or overload),
 *     capped at 100 — a health signal read from the audit trail R2.2 started writing, not a
 *     replacement for the audit log itself ({@code GET /api/v1/audit-log} is that).
 * @param recentVetoCount R2.3: operations this reactor's own reply *denied* in the last 24h,
 *     capped at 100. Distinct from {@code recent_timeout_count}: a veto is the reactor working as
 *     designed; a timeout is the reactor not answering.
 * @param tenantId the server's tenant_id field
 * @param timeoutMs the server's timeout_ms field
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ReactorResponse(
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("description") String description,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("events") List<String> events,
        @JsonProperty("failure_policy") FailurePolicy failurePolicy,
        @JsonProperty("id") UUID id,
        @JsonProperty("last_seen_at") @Nullable OffsetDateTime lastSeenAt,
        @JsonProperty("mode") ReactorMode mode,
        @JsonProperty("name") String name,
        @JsonProperty("priority") Integer priority,
        @JsonProperty("recent_timeout_count") Integer recentTimeoutCount,
        @JsonProperty("recent_veto_count") Integer recentVetoCount,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("timeout_ms") Integer timeoutMs,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
