// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.UUID;

/**
 * A role together with its assignment context (the resource it is scoped to).
 *
 * @param inherit Whether the assignment reaches the descendants of {@code resource_id} as well as
 *     the resource itself ({@code true}, the default, and the value of every assignment written before
 *     the field existed) or applies at that resource only ({@code false}).
 * @param resourceId {@code None} means the role was assigned globally (no resource scope).
 * @param role the server's role field
 * @param tenantScope The tenants this assignment reaches. See [{@code TenantScope}].
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RoleAssignment(
        @JsonProperty("inherit") @Nullable Boolean inherit,
        @JsonProperty("resource_id") @Nullable UUID resourceId,
        @JsonProperty("role") Role role,
        @JsonProperty("tenant_scope") @Nullable List<UUID> tenantScope
) {

    /**
     * CONTRACT.md §5.2.3 rule 1: {@code tenant_scope: []} is refused with 400.
     *
     * <p>An assignment that reaches no tenant contributes nothing anywhere, so it is a
     * grant that does not exist rather than a restriction, and the server declines to
     * guess which was meant. Normalising to {@code null} here means both spellings of
     * absent travel the same way — by not appearing, via {@code JsonInclude.NON_NULL}.
     */
    public RoleAssignment {
        if (tenantScope != null && tenantScope.isEmpty()) {
            tenantScope = null;
        }
    }

    /**
     * Whether this binding inherits to descendants, defaulting to {@code true} when the server
     * omitted {@code inherit} (CONTRACT.md §27.13 S-10 rule 3 — a server older than contract 1.51
     * never sends it, and absence means what every assignment has always meant).
     *
     * @return {@code inherit}, or {@code true} when it was absent
     */
    public boolean inherits() {
        return inherit == null || inherit;
    }
}
