// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.axiam.sdk.Sensitive;

/**
 * Response for secret rotation.
 *
 * @param clientSecret the server's client_secret field -- SECRET: redacted from toString and from
 *     every JSON rendering except the one request body it is sent in
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RotateSecretResponse(
        @JsonProperty("client_secret") Sensitive clientSecret
) {
}
