// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * A registered service provider, as stored.
 *
 * @param acsUrls See [{@code SamlServiceProviderInput::acs_urls}].
 * @param allowIdpInitiated See [{@code SamlServiceProviderInput::allow_idp_initiated}].
 * @param allowedGroups See [{@code SamlServiceProviderInput::allowed_groups}].
 * @param attributeMappings See [{@code SamlServiceProviderInput::attribute_mappings}].
 * @param createdAt When the SP was registered.
 * @param displayName See [{@code SamlServiceProviderInput::display_name}].
 * @param enabled See [{@code SamlServiceProviderInput::enabled}].
 * @param encryptAssertions See [{@code SamlServiceProviderInput::encrypt_assertions}].
 * @param entityId See [{@code SamlServiceProviderInput::entity_id}].
 * @param id Record id.
 * @param nameIdFormat See [{@code SamlServiceProviderInput::name_id_format}].
 * @param signResponses See [{@code SamlServiceProviderInput::sign_responses}].
 * @param sloBinding the server's slo_binding field
 * @param sloUrl See [{@code SamlServiceProviderInput::slo_url}].
 * @param spEncryptionCertPem See [{@code SamlServiceProviderInput::sp_encryption_cert_pem}].
 * @param spSigningCertPem See [{@code SamlServiceProviderInput::sp_signing_cert_pem}].
 * @param tenantId The owning tenant.
 * @param updatedAt When it was last replaced.
 * @param wantAuthnRequestsSigned See [{@code
 *     SamlServiceProviderInput::want_authn_requests_signed}].
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SamlServiceProvider(
        @JsonProperty("acs_urls") List<AcsEndpoint> acsUrls,
        @JsonProperty("allow_idp_initiated") Boolean allowIdpInitiated,
        @JsonProperty("allowed_groups") List<UUID> allowedGroups,
        @JsonProperty("attribute_mappings") List<AttributeMapping> attributeMappings,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("encrypt_assertions") Boolean encryptAssertions,
        @JsonProperty("entity_id") String entityId,
        @JsonProperty("id") UUID id,
        @JsonProperty("name_id_format") NameIdFormat nameIdFormat,
        @JsonProperty("sign_responses") Boolean signResponses,
        @JsonProperty("slo_binding") @Nullable SamlBinding sloBinding,
        @JsonProperty("slo_url") @Nullable String sloUrl,
        @JsonProperty("sp_encryption_cert_pem") @Nullable String spEncryptionCertPem,
        @JsonProperty("sp_signing_cert_pem") @Nullable String spSigningCertPem,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("updated_at") OffsetDateTime updatedAt,
        @JsonProperty("want_authn_requests_signed") Boolean wantAuthnRequestsSigned
) {
}
