// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * The tenant's IdP signing credential, **public facts only**.
 *
 * <p>There is no key on it and no field a key could be put in: the private key is generated by the
 * server, sealed at rest, never returned by any route and destroyed on retirement (D-21).
 *
 * @param certificatePem The leaf certificate, PEM. Public: it is what the metadata publishes.
 * @param createdAt When the credential was issued.
 * @param fingerprint Lower-case hex SHA-256 of the certificate's DER — what an SP administrator
 *     compares out of band.
 * @param id Credential id.
 * @param issuerCaId The signing CA that issued the leaf.
 * @param notAfter End of the certificate's validity (at most 730 days after the start).
 * @param notBefore Start of the certificate's validity.
 * @param retiredAt When it was retired, or null.
 * @param serial The certificate's serial, lower-case hex.
 * @param status {@code active}, {@code next} or {@code retired}. At most one {@code active} and
 *     one {@code next} per tenant.
 * @param tenantId The tenant it signs for.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SamlIdpCredential(
        @JsonProperty("certificate_pem") String certificatePem,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("fingerprint") String fingerprint,
        @JsonProperty("id") UUID id,
        @JsonProperty("issuer_ca_id") UUID issuerCaId,
        @JsonProperty("not_after") OffsetDateTime notAfter,
        @JsonProperty("not_before") OffsetDateTime notBefore,
        @JsonProperty("retired_at") @Nullable OffsetDateTime retiredAt,
        @JsonProperty("serial") String serial,
        @JsonProperty("status") SamlIdpCredentialStatus status,
        @JsonProperty("tenant_id") UUID tenantId
) {
}
