// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.UUID;

/**
 * Everything an administrator supplies when registering or replacing a service provider ({@code
 * create} and {@code update} both take it; {@code update} is a full replacement).
 *
 * <p>Every field but {@code entity_id}, {@code display_name} and {@code acs_urls} has a default,
 * so a client written against a later revision of this struct keeps working.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component
 * positionally. An optional component left null is omitted and takes its default, not the value
 * stored.
 *
 * @param acsUrls The ACS allow-list. At least one, at most one default.
 * @param allowIdpInitiated Whether IdP-initiated SSO is allowed for this SP (D-3). A per-SP
 *     opt-in, off by default: an unsolicited assertion has no {@code InResponseTo} to bind it to a
 *     request the SP made.
 * @param allowedGroups Groups whose members may sign in to this SP. **Empty means every active
 *     user of the tenant may.** Evaluated by the SSO endpoint (T23.2.3).
 * @param attributeMappings Attribute mapping table, at most [{@code MAX_ATTRIBUTE_MAPPINGS}]
 *     entries.
 * @param displayName Human-readable name for the console.
 * @param enabled Whether the SP may sign in at all. A disabled SP stays registered but every SSO
 *     request for it is refused.
 * @param encryptAssertions Encrypt assertions to the SP's encryption certificate (D-2). Off by
 *     default; requires [{@code Self::sp_encryption_cert_pem}].
 * @param entityId The SP's {@code entityID}, unique per tenant. At most [{@code
 *     MAX_ENTITY_ID_BYTES}].
 * @param nameIdFormat {@code NameID} policy. Default: persistent, pairwise.
 * @param signResponses Sign the {@code &lt;samlp:Response&gt;} envelope as well as the assertion
 *     (which is signed always). Default **{@code true}**: it costs nothing and many SPs require it.
 * @param sloBinding the server's slo_binding field
 * @param sloUrl Single-logout endpoint, if the SP supports it.
 * @param spEncryptionCertPem PEM certificate assertions are encrypted to. Required when {@code
 *     encrypt_assertions} is set.
 * @param spSigningCertPem PEM certificate the SP signs its {@code AuthnRequest}s with.
 * @param wantAuthnRequestsSigned Refuse an {@code AuthnRequest} that is not signed by {@code
 *     sp_signing_cert_pem}. Requires that certificate.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SamlServiceProviderInput(
        @JsonProperty("acs_urls") List<AcsEndpoint> acsUrls,
        @JsonProperty("allow_idp_initiated") @Nullable Boolean allowIdpInitiated,
        @JsonProperty("allowed_groups") @Nullable List<UUID> allowedGroups,
        @JsonProperty("attribute_mappings") @Nullable List<AttributeMapping> attributeMappings,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("encrypt_assertions") @Nullable Boolean encryptAssertions,
        @JsonProperty("entity_id") String entityId,
        @JsonProperty("name_id_format") @Nullable NameIdFormat nameIdFormat,
        @JsonProperty("sign_responses") @Nullable Boolean signResponses,
        @JsonProperty("slo_binding") @Nullable SamlBinding sloBinding,
        @JsonProperty("slo_url") @Nullable String sloUrl,
        @JsonProperty("sp_encryption_cert_pem") @Nullable String spEncryptionCertPem,
        @JsonProperty("sp_signing_cert_pem") @Nullable String spSigningCertPem,
        @JsonProperty("want_authn_requests_signed") @Nullable Boolean wantAuthnRequestsSigned
) {
}
