// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.UUID;

/**
 * The tenant's SAML IdP, as the administrator needs to see it before and while switching it on:
 * what an SP will be given, and whether it answers yet.
 *
 * @param activeCredentialId The {@code active} credential, or null.
 * @param entityId The IdP's entity id (the metadata URL itself).
 * @param metadataServed Whether {@code metadata_url} answers now: SAML is available, enabled for
 *     the tenant, and an {@code active} or {@code next} credential exists (D-40).
 * @param metadataUrl Where the IdP metadata is served.
 * @param nextCredentialId The {@code next} credential, or null.
 * @param samlAvailable Whether this server build serves SAML at all (it was built with the {@code
 *     saml} feature).
 * @param samlIdpEnabled The tenant's **effective** {@code saml_idp_enabled} setting (D-20).
 *     Written through the {@code settings} operations, not here.
 * @param sloUrl The single-logout endpoint.
 * @param ssoUrl The single-sign-on endpoint.
 * @param tenantId The tenant.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SamlIdpInfo(
        @JsonProperty("active_credential_id") @Nullable UUID activeCredentialId,
        @JsonProperty("entity_id") String entityId,
        @JsonProperty("metadata_served") Boolean metadataServed,
        @JsonProperty("metadata_url") String metadataUrl,
        @JsonProperty("next_credential_id") @Nullable UUID nextCredentialId,
        @JsonProperty("saml_available") Boolean samlAvailable,
        @JsonProperty("saml_idp_enabled") Boolean samlIdpEnabled,
        @JsonProperty("slo_url") String sloUrl,
        @JsonProperty("sso_url") String ssoUrl,
        @JsonProperty("tenant_id") UUID tenantId
) {
}
