// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * How AXIAM authenticates to the downstream service provider, without the credential itself.
 *
 * <p>Shapes discriminated by the type field. The set is OPEN (CONTRACT §31.2): a type this SDK
 * does not know decodes as {&#64;link ScimTargetAuthUnknown} rather than failing the response, and
 * that arm is never sent. Sealed, so a switch over the permitted records is still exhaustive --
 * the unknown arm is one of them.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type", visible = true, defaultImpl = ScimTargetAuthUnknown.class)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ScimTargetAuthBearer.class, name = "bearer"),
        @JsonSubTypes.Type(value = ScimTargetAuthOauth2ClientCredentials.class, name = "oauth2_client_credentials"),
})
public sealed interface ScimTargetAuth permits ScimTargetAuthBearer, ScimTargetAuthOauth2ClientCredentials, ScimTargetAuthUnknown {

    /**
     * Returns the discriminator this arm carries.
     *
     * @return the server's type value for this arm
     */
    String type();
}
