// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A type this SDK does not know -- an arm of ScimTargetAuth reachable only by decoding.
 *
 * <p>CONTRACT §31.2: an unknown type MUST decode without failing the response it arrived in, and
 * MUST NOT be sent. Only the type itself is kept; any other member it arrived with is dropped.
 * Encoding it in a request body fails before anything reaches the wire -- read the record, and if
 * this is the arm, supply a known one in the write instead.
 *
 * @param type the type value the server sent
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonSerialize(using = ScimTargetAuthUnknown.Refuse.class)
public record ScimTargetAuthUnknown(@JsonProperty("type") String type) implements ScimTargetAuth {

    /** Refuses to encode this arm: an unknown value is never sent (§31.2). */
    public static final class Refuse extends com.fasterxml.jackson.databind.JsonSerializer<ScimTargetAuthUnknown> {
        /** Constructs the serializer Jackson instantiates from the class-level annotation. */
        public Refuse() {
        }

        @Override
        public void serialize(ScimTargetAuthUnknown value, com.fasterxml.jackson.core.JsonGenerator gen,
                com.fasterxml.jackson.databind.SerializerProvider serializers)
                throws java.io.IOException {
            throw refusal(gen, value);
        }

        @Override
        public void serializeWithType(ScimTargetAuthUnknown value, com.fasterxml.jackson.core.JsonGenerator gen,
                com.fasterxml.jackson.databind.SerializerProvider serializers,
                com.fasterxml.jackson.databind.jsontype.TypeSerializer typeSer)
                throws java.io.IOException {
            throw refusal(gen, value);
        }

        private static com.fasterxml.jackson.databind.JsonMappingException refusal(
                com.fasterxml.jackson.core.JsonGenerator gen, ScimTargetAuthUnknown value) {
            return com.fasterxml.jackson.databind.JsonMappingException.from(gen,
                    "ScimTargetAuth type \"" + value.type()
                    + "\" is not one this SDK knows, so it is never sent (CONTRACT §31.2)");
        }
    }
}
