// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import io.axiam.sdk.Sensitive;

/**
 * {@code create} and {@code update} (a **replacement**) body.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component
 * positionally. A required component cannot be null: the constructor refuses it, rather than let
 * it be omitted from the wire and refused by the server. An optional component left null is
 * omitted and takes its default, not the value stored.
 *
 * @param auth {@code bearer}, or {@code oauth2_client_credentials} with {@code token_url} (the
 *     same URL policy), {@code client_id} (1–256 bytes) and an optional {@code scope}.
 * @param baseUrl The downstream's SCIM service root: an {@code https} URL under the outbound
 *     address policy (no credentials or fragment, at most 2 048 bytes, no non-public address, no local
 *     name).
 * @param credential **Write-only.** The bearer token or the OAuth2 client secret, 1–4 096 bytes.
 *     Required on create. On update, absent keeps the stored one — except that moving it to another
 *     URL ({@code base_url} of a bearer target, {@code token_url} or {@code base_url} of a
 *     client-credentials one) or switching {@code auth.type} requires it again. -- SECRET: redacted
 *     from toString and from every JSON rendering except the one request body it is sent in
 * @param deprovision {@code deactivate} (default: {@code PATCH active=false}) or {@code delete}.
 * @param enabled {@code true} by default. A disabled target receives nothing.
 * @param name 1–128 bytes.
 * @param pushGroups Push groups too (every group for {@code all_users}, the listed ones for {@code
 *     groups}). {@code false} by default.
 * @param scope {@code all_users}, or {@code groups} with 1–100 {@code group_ids} of this tenant:
 *     users who are direct members of any listed group.
 * @param userNameFrom {@code username} (default) or {@code email}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScimTargetInput(
        @JsonProperty("auth") ScimTargetAuth auth,
        @JsonProperty("base_url") String baseUrl,
        @JsonProperty("credential") @Nullable Sensitive credential,
        @JsonProperty("deprovision") @Nullable DeprovisionPolicy deprovision,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("name") String name,
        @JsonProperty("push_groups") @Nullable Boolean pushGroups,
        @JsonProperty("scope") ScimTargetScope scope,
        @JsonProperty("user_name_from") @Nullable UserNameSource userNameFrom
) {

    /**
     * Refuses a null for a required member: this body replaces the stored one, and a
     * required member left null would be omitted and refused by the server (§27.4
     * rule 5). Optional members may be null; they are omitted and take their default.
     *
     * @param auth see the record component
     * @param baseUrl see the record component
     * @param credential see the record component
     * @param deprovision see the record component
     * @param enabled see the record component
     * @param name see the record component
     * @param pushGroups see the record component
     * @param scope see the record component
     * @param userNameFrom see the record component
     * @throws NullPointerException naming the first required member that is null
     */
    public ScimTargetInput {
        java.util.Objects.requireNonNull(auth, "auth is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(baseUrl, "base_url is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(name, "name is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(scope, "scope is required (CONTRACT §27.4 rule 5)");
    }
}
