// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A registered SCIM target, as the management API returns it. **The credential is never
 * returned**, and there is no member that says anything about it.
 *
 * @param auth How AXIAM authenticates to it (no credential).
 * @param baseUrl The downstream's SCIM service root.
 * @param createdAt When the target was registered.
 * @param deprovision What happens downstream to a user who leaves scope or is no longer active
 *     (erasure always deletes).
 * @param enabled Whether AXIAM pushes to it.
 * @param id The target id.
 * @param name The name.
 * @param pushGroups Whether groups are pushed too.
 * @param scope Which users it provisions.
 * @param state the server's state field
 * @param tenantId The owning tenant.
 * @param updatedAt When it was last written: the version an update is conditional on.
 * @param userNameFrom Which attribute becomes {@code userName}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScimTargetResponse(
        @JsonProperty("auth") ScimTargetAuth auth,
        @JsonProperty("base_url") String baseUrl,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("deprovision") DeprovisionPolicy deprovision,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("id") UUID id,
        @JsonProperty("name") String name,
        @JsonProperty("push_groups") Boolean pushGroups,
        @JsonProperty("scope") ScimTargetScope scope,
        @JsonProperty("state") @Nullable ScimTargetDeliveryState state,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("updated_at") OffsetDateTime updatedAt,
        @JsonProperty("user_name_from") UserNameSource userNameFrom
) {
}
