// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Metadata only. The handle is never in a list response — it exists in plaintext exactly once, in
 * [{@code CreateScimTokenResponse}].
 *
 * @param createdAt the server's created_at field
 * @param createdBy the server's created_by field
 * @param expiresAt the server's expires_at field
 * @param id the server's id field
 * @param lastUsedAt the server's last_used_at field
 * @param name the server's name field
 * @param revokedAt the server's revoked_at field
 * @param status the server's status field
 * @param tenantId the server's tenant_id field
 * @param userId the server's user_id field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScimTokenResponse(
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("created_by") UUID createdBy,
        @JsonProperty("expires_at") OffsetDateTime expiresAt,
        @JsonProperty("id") UUID id,
        @JsonProperty("last_used_at") @Nullable OffsetDateTime lastUsedAt,
        @JsonProperty("name") String name,
        @JsonProperty("revoked_at") @Nullable OffsetDateTime revokedAt,
        @JsonProperty("status") ScimTokenStatus status,
        @JsonProperty("tenant_id") UUID tenantId,
        @JsonProperty("user_id") UUID userId
) {
}
