// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The 'oauth2_client_credentials' arm of ScimTargetAuth.
 *
 * @param type the discriminator, always 'oauth2_client_credentials'
 * @param clientId The OAuth2 client id.
 * @param scope The scope requested, if any.
 * @param tokenUrl The token endpoint the client secret is sent to.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ScimTargetAuthOauth2ClientCredentials(
        @JsonProperty("type") String type,
        @JsonProperty("client_id") String clientId,
        @JsonProperty("scope") @Nullable String scope,
        @JsonProperty("token_url") String tokenUrl
) implements ScimTargetAuth {
}
