// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Fully resolved security settings (all fields present).
 *
 * @param certificate the server's certificate field
 * @param createdAt the server's created_at field
 * @param email the server's email field
 * @param id the server's id field
 * @param lockout the server's lockout field
 * @param mfa the server's mfa field
 * @param notification the server's notification field
 * @param opaque the server's opaque field
 * @param password the server's password field
 * @param privacy the server's privacy field
 * @param scope the server's scope field
 * @param scopeId the server's scope_id field
 * @param token the server's token field
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SecuritySettings(
        @JsonProperty("certificate") CertificatePolicy certificate,
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("email") EmailVerificationPolicy email,
        @JsonProperty("id") UUID id,
        @JsonProperty("lockout") LockoutPolicy lockout,
        @JsonProperty("mfa") MfaPolicy mfa,
        @JsonProperty("notification") NotificationPolicy notification,
        @JsonProperty("opaque") OpaquePolicy opaque,
        @JsonProperty("password") PasswordPolicy password,
        @JsonProperty("privacy") PrivacyPolicy privacy,
        @JsonProperty("scope") SettingsScope scope,
        @JsonProperty("scope_id") UUID scopeId,
        @JsonProperty("token") TokenPolicy token,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
