// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import io.axiam.sdk.Sensitive;

/**
 * {@code PUT /api/v1/tenants/{tenant_id}/directory} — a **replacement**.
 *
 * <p>Every {@code DirectoryConfig} member except {@code id}, {@code tenant_id} and the two
 * timestamps, plus the write-only {@code bind_secret}. An omitted optional member is **reset to
 * its default**, not kept.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component
 * positionally. A required component cannot be null: the constructor refuses it, rather than let
 * it be omitted from the wire and refused by the server. An optional component left null is
 * omitted and takes its default, not the value stored.
 *
 * @param baseDn Where users are searched for.
 * @param bindDn The service account the search runs as.
 * @param bindSecret The service account's password: **write-only**, 1 to 4096 octets. Required
 *     when the tenant has no configuration yet; on a replacement, absent means *keep the stored
 *     secret* — unless the write moves the connection ({@code url}, {@code start_tls}, {@code bind_dn}
 *     or {@code trust_anchors_pem}), which then requires it ({@code 400}, P23W2-01). -- SECRET:
 *     redacted from toString and from every JSON rendering except the one request body it is sent in
 * @param enabled A disabled directory serves no sign-in and is not synced.
 * @param groupBaseDn Defaults to null.
 * @param groupFilter Defaults to null.
 * @param groupMappings At most 500; every {@code group_id} a group of the tenant. Default empty.
 * @param groupMemberAttribute Defaults by {@code kind}.
 * @param groupNestingDepth {@code 0..=10}, default 5.
 * @param jitProvisioning Default false.
 * @param kind Chooses defaults only.
 * @param startTls Upgrade an {@code ldap://} connection with StartTLS before any bind.
 * @param syncIntervalSecs {@code 300..=86400}, default 3600.
 * @param trustAnchorsPem At most 16 CA certificates in PEM. Default empty (the public roots).
 * @param url {@code ldaps://host[:port]}, or {@code ldap://host[:port]} with {@code start_tls}.
 * @param userAttributeMap the server's user_attribute_map field
 * @param userFilter One {@code {username}} placeholder in value position.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SetDirectoryConfig(
        @JsonProperty("base_dn") String baseDn,
        @JsonProperty("bind_dn") String bindDn,
        @JsonProperty("bind_secret") @Nullable Sensitive bindSecret,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("group_base_dn") @Nullable String groupBaseDn,
        @JsonProperty("group_filter") @Nullable String groupFilter,
        @JsonProperty("group_mappings") @Nullable List<GroupMapping> groupMappings,
        @JsonProperty("group_member_attribute") @Nullable String groupMemberAttribute,
        @JsonProperty("group_nesting_depth") @Nullable Integer groupNestingDepth,
        @JsonProperty("jit_provisioning") @Nullable Boolean jitProvisioning,
        @JsonProperty("kind") DirectoryKind kind,
        @JsonProperty("start_tls") Boolean startTls,
        @JsonProperty("sync_interval_secs") @Nullable Long syncIntervalSecs,
        @JsonProperty("trust_anchors_pem") @Nullable List<String> trustAnchorsPem,
        @JsonProperty("url") String url,
        @JsonProperty("user_attribute_map") @Nullable UserAttributeMap userAttributeMap,
        @JsonProperty("user_filter") String userFilter
) {

    /**
     * Refuses a null for a required member: this body replaces the stored one, and a
     * required member left null would be omitted and refused by the server (§27.4
     * rule 5). Optional members may be null; they are omitted and take their default.
     *
     * @param baseDn see the record component
     * @param bindDn see the record component
     * @param bindSecret see the record component
     * @param enabled see the record component
     * @param groupBaseDn see the record component
     * @param groupFilter see the record component
     * @param groupMappings see the record component
     * @param groupMemberAttribute see the record component
     * @param groupNestingDepth see the record component
     * @param jitProvisioning see the record component
     * @param kind see the record component
     * @param startTls see the record component
     * @param syncIntervalSecs see the record component
     * @param trustAnchorsPem see the record component
     * @param url see the record component
     * @param userAttributeMap see the record component
     * @param userFilter see the record component
     * @throws NullPointerException naming the first required member that is null
     */
    public SetDirectoryConfig {
        java.util.Objects.requireNonNull(baseDn, "base_dn is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(bindDn, "bind_dn is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(enabled, "enabled is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(kind, "kind is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(startTls, "start_tls is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(url, "url is required (CONTRACT §27.4 rule 5)");
        java.util.Objects.requireNonNull(userFilter, "user_filter is required (CONTRACT §27.4 rule 5)");
    }
}
