// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Body for {@code PUT .../ca-certificates/{id}/mtls-trust-anchor}.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component,
 * so forgetting one is a compile error rather than a silent null on the wire.
 *
 * @param enabled Whether this CA should be trusted for client-certificate authentication.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SetMtlsTrustAnchor(
        @JsonProperty("enabled") Boolean enabled
) {
}
