// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;

/**
 * Input for setting organization-level security settings.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component,
 * so forgetting one is a compile error rather than a silent null on the wire.
 *
 * @param accessTokenLifetimeSecs the server's access_token_lifetime_secs field
 * @param adminNotificationsEnabled the server's admin_notifications_enabled field
 * @param cimd T21.5 — defaulted, so an API client written before this task lands on {@code
 *     enabled: false}, which is what every deployment did before client ID metadata documents existed
 *     (I1).
 * @param dcrAllowedRedirectHosts the server's dcr_allowed_redirect_hosts field
 * @param dcrAllowedScopes the server's dcr_allowed_scopes field
 * @param dcrMaxClients the server's dcr_max_clients field
 * @param dcrUnusedClientTtlDays the server's dcr_unused_client_ttl_days field
 * @param defaultCertValidityDays the server's default_cert_validity_days field
 * @param defaultLocale the server's default_locale field
 * @param deletionGracePeriodDays the server's deletion_grace_period_days field
 * @param dynamicRegistration the server's dynamic_registration field
 * @param emailVerificationGracePeriodHours the server's email_verification_grace_period_hours
 *     field
 * @param emailVerificationRequired the server's email_verification_required field
 * @param externalClientAllowedResources the server's external_client_allowed_resources field
 * @param hibpCheckEnabled the server's hibp_check_enabled field
 * @param lockoutBackoffMultiplier the server's lockout_backoff_multiplier field
 * @param lockoutDurationSecs the server's lockout_duration_secs field
 * @param maxCertValidityDays the server's max_cert_validity_days field
 * @param maxFailedLoginAttempts the server's max_failed_login_attempts field
 * @param maxLockoutDurationSecs the server's max_lockout_duration_secs field
 * @param mfaChallengeLifetimeSecs the server's mfa_challenge_lifetime_secs field
 * @param mfaEnforced the server's mfa_enforced field
 * @param minLength the server's min_length field
 * @param opaqueKsf the server's opaque_ksf field
 * @param opaqueMode the server's opaque_mode field
 * @param opaqueSuite the server's opaque_suite field
 * @param passwordHistoryCount the server's password_history_count field
 * @param refreshTokenLifetimeSecs the server's refresh_token_lifetime_secs field
 * @param requireDigits the server's require_digits field
 * @param requireLowercase the server's require_lowercase field
 * @param requireSymbols the server's require_symbols field
 * @param requireUppercase the server's require_uppercase field
 * @param sensitiveScopesEnabled the server's sensitive_scopes_enabled field
 * @param webauthnUserVerification the server's webauthn_user_verification field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SetOrgSettings(
        @JsonProperty("access_token_lifetime_secs") Long accessTokenLifetimeSecs,
        @JsonProperty("admin_notifications_enabled") Boolean adminNotificationsEnabled,
        @JsonProperty("cimd") @Nullable CimdPolicy cimd,
        @JsonProperty("dcr_allowed_redirect_hosts") @Nullable List<String> dcrAllowedRedirectHosts,
        @JsonProperty("dcr_allowed_scopes") @Nullable List<String> dcrAllowedScopes,
        @JsonProperty("dcr_max_clients") @Nullable Integer dcrMaxClients,
        @JsonProperty("dcr_unused_client_ttl_days") @Nullable Integer dcrUnusedClientTtlDays,
        @JsonProperty("default_cert_validity_days") Integer defaultCertValidityDays,
        @JsonProperty("default_locale") @Nullable String defaultLocale,
        @JsonProperty("deletion_grace_period_days") @Nullable Integer deletionGracePeriodDays,
        @JsonProperty("dynamic_registration") @Nullable String dynamicRegistration,
        @JsonProperty("email_verification_grace_period_hours") Integer emailVerificationGracePeriodHours,
        @JsonProperty("email_verification_required") Boolean emailVerificationRequired,
        @JsonProperty("external_client_allowed_resources") @Nullable List<String> externalClientAllowedResources,
        @JsonProperty("hibp_check_enabled") Boolean hibpCheckEnabled,
        @JsonProperty("lockout_backoff_multiplier") Double lockoutBackoffMultiplier,
        @JsonProperty("lockout_duration_secs") Long lockoutDurationSecs,
        @JsonProperty("max_cert_validity_days") Integer maxCertValidityDays,
        @JsonProperty("max_failed_login_attempts") Integer maxFailedLoginAttempts,
        @JsonProperty("max_lockout_duration_secs") Long maxLockoutDurationSecs,
        @JsonProperty("mfa_challenge_lifetime_secs") Long mfaChallengeLifetimeSecs,
        @JsonProperty("mfa_enforced") Boolean mfaEnforced,
        @JsonProperty("min_length") Integer minLength,
        @JsonProperty("opaque_ksf") @Nullable String opaqueKsf,
        @JsonProperty("opaque_mode") @Nullable String opaqueMode,
        @JsonProperty("opaque_suite") @Nullable String opaqueSuite,
        @JsonProperty("password_history_count") Integer passwordHistoryCount,
        @JsonProperty("refresh_token_lifetime_secs") Long refreshTokenLifetimeSecs,
        @JsonProperty("require_digits") Boolean requireDigits,
        @JsonProperty("require_lowercase") Boolean requireLowercase,
        @JsonProperty("require_symbols") Boolean requireSymbols,
        @JsonProperty("require_uppercase") Boolean requireUppercase,
        @JsonProperty("sensitive_scopes_enabled") @Nullable Boolean sensitiveScopesEnabled,
        @JsonProperty("webauthn_user_verification") @Nullable String webauthnUserVerification
) {
}
