// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whether a settings row belongs to an organization or a tenant.
 *
 * <p>The wire spelling is carried on each constant rather than derived from its name, because the
 * server's vocabulary is not uniformly cased and a derivation that worked for every value today
 * would break on the first one that did not fit.
 */
public enum SettingsScope {
    /** The server's 'Org' value. */
    ORG("Org"),
    /** The server's 'Tenant' value. */
    TENANT("Tenant");

    /** The spelling this value has on the wire. */
    private final String wire;

    SettingsScope(String wire) {
        this.wire = wire;
    }

    /**
     * Returns the spelling this value has on the wire.
     *
     * @return the server's own spelling of this value
     */
    @JsonValue
    public String wire() {
        return wire;
    }

    /**
     * Parses a wire value into a constant.
     *
     * <p>An unrecognised value is a hard failure rather than a silent null: a newer server sending
     * a value this SDK has never heard of is something a caller needs to know about, not something
     * to swallow.
     *
     * @param value the server's spelling
     * @return the matching SettingsScope
     * @throws IllegalArgumentException if no constant carries that spelling
     */
    @JsonCreator
    public static SettingsScope fromWire(String value) {
        for (SettingsScope candidate : values()) {
            if (candidate.wire.equals(value)) {
                return candidate;
            }
        }
        throw new IllegalArgumentException("unknown SettingsScope value: " + value);
    }
}
