// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

/**
 * Body of {@code POST /api/v1/certificates/sign-csr}.
 *
 * <p>No {@code subject} and no {@code key_algorithm}: both are read out of the CSR, which is the
 * only place they can be stated without the row and the certificate being able to disagree. No key
 * is returned, so there is no key field anywhere on this exchange.
 *
 * @param certType the server's cert_type field
 * @param csrPem PEM-encoded PKCS#10 request — a {@code BEGIN CERTIFICATE REQUEST} block. The
 *     legacy OpenSSL {@code BEGIN NEW CERTIFICATE REQUEST} header is not accepted.
 * @param issuerCaId the server's issuer_ca_id field
 * @param metadata the server's metadata field
 * @param validityDays Validity duration in days.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SignCertificateCsrRequest(
        @JsonProperty("cert_type") CertificateType certType,
        @JsonProperty("csr_pem") String csrPem,
        @JsonProperty("issuer_ca_id") UUID issuerCaId,
        @JsonProperty("metadata") @Nullable JsonNode metadata,
        @JsonProperty("validity_days") Integer validityDays
) {
}
