// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * A signed batch of audit log entries.
 *
 * @param batchId the server's batch_id field
 * @param entryIds the server's entry_ids field
 * @param signatureArmored ASCII-armored PGP signed message containing the audit batch payload.
 * @param signedAt the server's signed_at field
 * @param signingKeyId the server's signing_key_id field
 * @param tenantId the server's tenant_id field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SignedAuditBatch(
        @JsonProperty("batch_id") UUID batchId,
        @JsonProperty("entry_ids") List<UUID> entryIds,
        @JsonProperty("signature_armored") String signatureArmored,
        @JsonProperty("signed_at") OffsetDateTime signedAt,
        @JsonProperty("signing_key_id") UUID signingKeyId,
        @JsonProperty("tenant_id") UUID tenantId
) {
}
