// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;
import io.axiam.sdk.Sensitive;

/**
 * {@code create_stream} and {@code update_stream} (a **replacement**) body.
 *
 * <p>This body REPLACES rather than patches (§27.4 rule 5): what you do not carry over from a
 * prior read is not preserved, it is overwritten. The canonical constructor takes every component,
 * so forgetting one is a compile error rather than a silent null on the wire.
 *
 * @param audience 1–512 bytes; unique across the deployment.
 * @param authorizationHeader **Write-only.** The {@code Authorization} header value AXIAM sends to
 *     a push endpoint. On update, absent keeps the stored one — except that moving the endpoint to
 *     another origin requires it again. -- SECRET: redacted from toString and from every JSON
 *     rendering except the one request body it is sent in
 * @param clearAuthorizationHeader On update: remove the stored header. Refused together with
 *     {@code authorization_header}.
 * @param deliveryMethod {@code push} or {@code poll}.
 * @param description At most 256 bytes.
 * @param endpointUrl Required for {@code push} (an {@code https} URL under the outbound address
 *     policy), refused for {@code poll}.
 * @param eventsAllowed 1–6 event types.
 * @param eventsRequested A subset of {@code events_allowed}; absent means all of them. The
 *     receiver may narrow it later, never widen it.
 * @param receiverClientId An OAuth2 client of the tenant with the {@code client_credentials} grant
 *     and the {@code ssf.manage} scope.
 * @param status {@code enabled} by default.
 * @param statusReason At most 256 bytes.
 * @param subjectFormat {@code iss_sub} by default.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record SsfStreamInput(
        @JsonProperty("audience") String audience,
        @JsonProperty("authorization_header") @Nullable Sensitive authorizationHeader,
        @JsonProperty("clear_authorization_header") @Nullable Boolean clearAuthorizationHeader,
        @JsonProperty("delivery_method") SsfDeliveryMethod deliveryMethod,
        @JsonProperty("description") @Nullable String description,
        @JsonProperty("endpoint_url") @Nullable String endpointUrl,
        @JsonProperty("events_allowed") List<SsfEventType> eventsAllowed,
        @JsonProperty("events_requested") @Nullable List<SsfEventType> eventsRequested,
        @JsonProperty("receiver_client_id") String receiverClientId,
        @JsonProperty("status") @Nullable SsfStreamStatus status,
        @JsonProperty("status_reason") @Nullable String statusReason,
        @JsonProperty("subject_format") @Nullable SsfSubjectFormat subjectFormat
) {
}
