// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A tenant is an isolated context within an organization.
 *
 * <p>Each tenant has its own set of users, roles, permissions, resources, certificates, and
 * configuration. Tenants can represent environments (dev/staging/prod) or separate business
 * contexts.
 *
 * @param createdAt the server's created_at field
 * @param id the server's id field
 * @param kind Whether this is an ordinary tenant or the organization's own scope. {@code
 *     #[serde(default)]} so every row written before organization scope existed reads back as [{@code
 *     TenantKind::Standard}], which is what it is.
 * @param metadata Arbitrary key-value metadata.
 * @param name Human-readable name.
 * @param organizationId The organization this tenant belongs to.
 * @param slug URL-safe unique identifier within the organization (e.g., {@code production}).
 * @param status Lifecycle status. New tenants default to [{@code TenantStatus::Active}].
 * @param updatedAt the server's updated_at field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Tenant(
        @JsonProperty("created_at") OffsetDateTime createdAt,
        @JsonProperty("id") UUID id,
        @JsonProperty("kind") @Nullable TenantKind kind,
        @JsonProperty("metadata") JsonNode metadata,
        @JsonProperty("name") String name,
        @JsonProperty("organization_id") UUID organizationId,
        @JsonProperty("slug") String slug,
        @JsonProperty("status") TenantStatus status,
        @JsonProperty("updated_at") OffsetDateTime updatedAt
) {
}
