// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * Partial tenant overrides. {@code None} = inherit from org baseline.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param accessTokenLifetimeSecs the server's access_token_lifetime_secs field
 * @param adminNotificationsEnabled the server's admin_notifications_enabled field
 * @param defaultCertValidityDays the server's default_cert_validity_days field
 * @param deletionGracePeriodDays the server's deletion_grace_period_days field
 * @param emailVerificationGracePeriodHours the server's email_verification_grace_period_hours
 *     field
 * @param emailVerificationRequired the server's email_verification_required field
 * @param hibpCheckEnabled the server's hibp_check_enabled field
 * @param lockoutBackoffMultiplier the server's lockout_backoff_multiplier field
 * @param lockoutDurationSecs the server's lockout_duration_secs field
 * @param maxCertValidityDays the server's max_cert_validity_days field
 * @param maxFailedLoginAttempts the server's max_failed_login_attempts field
 * @param maxLockoutDurationSecs the server's max_lockout_duration_secs field
 * @param mfaChallengeLifetimeSecs the server's mfa_challenge_lifetime_secs field
 * @param mfaEnforced the server's mfa_enforced field
 * @param minLength the server's min_length field
 * @param opaqueKsf the server's opaque_ksf field
 * @param opaqueMode the server's opaque_mode field
 * @param opaqueSuite the server's opaque_suite field
 * @param passwordHistoryCount the server's password_history_count field
 * @param refreshTokenLifetimeSecs the server's refresh_token_lifetime_secs field
 * @param requireDigits the server's require_digits field
 * @param requireLowercase the server's require_lowercase field
 * @param requireSymbols the server's require_symbols field
 * @param requireUppercase the server's require_uppercase field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TenantSettingsOverride(
        @JsonProperty("access_token_lifetime_secs") @Nullable Long accessTokenLifetimeSecs,
        @JsonProperty("admin_notifications_enabled") @Nullable Boolean adminNotificationsEnabled,
        @JsonProperty("default_cert_validity_days") @Nullable Integer defaultCertValidityDays,
        @JsonProperty("deletion_grace_period_days") @Nullable Integer deletionGracePeriodDays,
        @JsonProperty("email_verification_grace_period_hours") @Nullable Integer emailVerificationGracePeriodHours,
        @JsonProperty("email_verification_required") @Nullable Boolean emailVerificationRequired,
        @JsonProperty("hibp_check_enabled") @Nullable Boolean hibpCheckEnabled,
        @JsonProperty("lockout_backoff_multiplier") @Nullable Double lockoutBackoffMultiplier,
        @JsonProperty("lockout_duration_secs") @Nullable Long lockoutDurationSecs,
        @JsonProperty("max_cert_validity_days") @Nullable Integer maxCertValidityDays,
        @JsonProperty("max_failed_login_attempts") @Nullable Integer maxFailedLoginAttempts,
        @JsonProperty("max_lockout_duration_secs") @Nullable Long maxLockoutDurationSecs,
        @JsonProperty("mfa_challenge_lifetime_secs") @Nullable Long mfaChallengeLifetimeSecs,
        @JsonProperty("mfa_enforced") @Nullable Boolean mfaEnforced,
        @JsonProperty("min_length") @Nullable Integer minLength,
        @JsonProperty("opaque_ksf") @Nullable String opaqueKsf,
        @JsonProperty("opaque_mode") @Nullable String opaqueMode,
        @JsonProperty("opaque_suite") @Nullable String opaqueSuite,
        @JsonProperty("password_history_count") @Nullable Integer passwordHistoryCount,
        @JsonProperty("refresh_token_lifetime_secs") @Nullable Long refreshTokenLifetimeSecs,
        @JsonProperty("require_digits") @Nullable Boolean requireDigits,
        @JsonProperty("require_lowercase") @Nullable Boolean requireLowercase,
        @JsonProperty("require_symbols") @Nullable Boolean requireSymbols,
        @JsonProperty("require_uppercase") @Nullable Boolean requireUppercase
) {

    /**
     * Starts a TenantSettingsOverride with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh TenantSettingsOverride.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse TenantSettingsOverride.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable Long accessTokenLifetimeSecs;
        private @Nullable Boolean adminNotificationsEnabled;
        private @Nullable Integer defaultCertValidityDays;
        private @Nullable Integer deletionGracePeriodDays;
        private @Nullable Integer emailVerificationGracePeriodHours;
        private @Nullable Boolean emailVerificationRequired;
        private @Nullable Boolean hibpCheckEnabled;
        private @Nullable Double lockoutBackoffMultiplier;
        private @Nullable Long lockoutDurationSecs;
        private @Nullable Integer maxCertValidityDays;
        private @Nullable Integer maxFailedLoginAttempts;
        private @Nullable Long maxLockoutDurationSecs;
        private @Nullable Long mfaChallengeLifetimeSecs;
        private @Nullable Boolean mfaEnforced;
        private @Nullable Integer minLength;
        private @Nullable String opaqueKsf;
        private @Nullable String opaqueMode;
        private @Nullable String opaqueSuite;
        private @Nullable Integer passwordHistoryCount;
        private @Nullable Long refreshTokenLifetimeSecs;
        private @Nullable Boolean requireDigits;
        private @Nullable Boolean requireLowercase;
        private @Nullable Boolean requireSymbols;
        private @Nullable Boolean requireUppercase;

        /**
         * Sets access_token_lifetime_secs.
         *
         * @param accessTokenLifetimeSecs the value to send
         * @return this builder
         */
        public Builder accessTokenLifetimeSecs(Long accessTokenLifetimeSecs) {
            this.accessTokenLifetimeSecs = accessTokenLifetimeSecs;
            return this;
        }

        /**
         * Sets admin_notifications_enabled.
         *
         * @param adminNotificationsEnabled the value to send
         * @return this builder
         */
        public Builder adminNotificationsEnabled(Boolean adminNotificationsEnabled) {
            this.adminNotificationsEnabled = adminNotificationsEnabled;
            return this;
        }

        /**
         * Sets default_cert_validity_days.
         *
         * @param defaultCertValidityDays the value to send
         * @return this builder
         */
        public Builder defaultCertValidityDays(Integer defaultCertValidityDays) {
            this.defaultCertValidityDays = defaultCertValidityDays;
            return this;
        }

        /**
         * Sets deletion_grace_period_days.
         *
         * @param deletionGracePeriodDays the value to send
         * @return this builder
         */
        public Builder deletionGracePeriodDays(Integer deletionGracePeriodDays) {
            this.deletionGracePeriodDays = deletionGracePeriodDays;
            return this;
        }

        /**
         * Sets email_verification_grace_period_hours.
         *
         * @param emailVerificationGracePeriodHours the value to send
         * @return this builder
         */
        public Builder emailVerificationGracePeriodHours(Integer emailVerificationGracePeriodHours) {
            this.emailVerificationGracePeriodHours = emailVerificationGracePeriodHours;
            return this;
        }

        /**
         * Sets email_verification_required.
         *
         * @param emailVerificationRequired the value to send
         * @return this builder
         */
        public Builder emailVerificationRequired(Boolean emailVerificationRequired) {
            this.emailVerificationRequired = emailVerificationRequired;
            return this;
        }

        /**
         * Sets hibp_check_enabled.
         *
         * @param hibpCheckEnabled the value to send
         * @return this builder
         */
        public Builder hibpCheckEnabled(Boolean hibpCheckEnabled) {
            this.hibpCheckEnabled = hibpCheckEnabled;
            return this;
        }

        /**
         * Sets lockout_backoff_multiplier.
         *
         * @param lockoutBackoffMultiplier the value to send
         * @return this builder
         */
        public Builder lockoutBackoffMultiplier(Double lockoutBackoffMultiplier) {
            this.lockoutBackoffMultiplier = lockoutBackoffMultiplier;
            return this;
        }

        /**
         * Sets lockout_duration_secs.
         *
         * @param lockoutDurationSecs the value to send
         * @return this builder
         */
        public Builder lockoutDurationSecs(Long lockoutDurationSecs) {
            this.lockoutDurationSecs = lockoutDurationSecs;
            return this;
        }

        /**
         * Sets max_cert_validity_days.
         *
         * @param maxCertValidityDays the value to send
         * @return this builder
         */
        public Builder maxCertValidityDays(Integer maxCertValidityDays) {
            this.maxCertValidityDays = maxCertValidityDays;
            return this;
        }

        /**
         * Sets max_failed_login_attempts.
         *
         * @param maxFailedLoginAttempts the value to send
         * @return this builder
         */
        public Builder maxFailedLoginAttempts(Integer maxFailedLoginAttempts) {
            this.maxFailedLoginAttempts = maxFailedLoginAttempts;
            return this;
        }

        /**
         * Sets max_lockout_duration_secs.
         *
         * @param maxLockoutDurationSecs the value to send
         * @return this builder
         */
        public Builder maxLockoutDurationSecs(Long maxLockoutDurationSecs) {
            this.maxLockoutDurationSecs = maxLockoutDurationSecs;
            return this;
        }

        /**
         * Sets mfa_challenge_lifetime_secs.
         *
         * @param mfaChallengeLifetimeSecs the value to send
         * @return this builder
         */
        public Builder mfaChallengeLifetimeSecs(Long mfaChallengeLifetimeSecs) {
            this.mfaChallengeLifetimeSecs = mfaChallengeLifetimeSecs;
            return this;
        }

        /**
         * Sets mfa_enforced.
         *
         * @param mfaEnforced the value to send
         * @return this builder
         */
        public Builder mfaEnforced(Boolean mfaEnforced) {
            this.mfaEnforced = mfaEnforced;
            return this;
        }

        /**
         * Sets min_length.
         *
         * @param minLength the value to send
         * @return this builder
         */
        public Builder minLength(Integer minLength) {
            this.minLength = minLength;
            return this;
        }

        /**
         * Sets opaque_ksf.
         *
         * @param opaqueKsf the value to send
         * @return this builder
         */
        public Builder opaqueKsf(String opaqueKsf) {
            this.opaqueKsf = opaqueKsf;
            return this;
        }

        /**
         * Sets opaque_mode.
         *
         * @param opaqueMode the value to send
         * @return this builder
         */
        public Builder opaqueMode(String opaqueMode) {
            this.opaqueMode = opaqueMode;
            return this;
        }

        /**
         * Sets opaque_suite.
         *
         * @param opaqueSuite the value to send
         * @return this builder
         */
        public Builder opaqueSuite(String opaqueSuite) {
            this.opaqueSuite = opaqueSuite;
            return this;
        }

        /**
         * Sets password_history_count.
         *
         * @param passwordHistoryCount the value to send
         * @return this builder
         */
        public Builder passwordHistoryCount(Integer passwordHistoryCount) {
            this.passwordHistoryCount = passwordHistoryCount;
            return this;
        }

        /**
         * Sets refresh_token_lifetime_secs.
         *
         * @param refreshTokenLifetimeSecs the value to send
         * @return this builder
         */
        public Builder refreshTokenLifetimeSecs(Long refreshTokenLifetimeSecs) {
            this.refreshTokenLifetimeSecs = refreshTokenLifetimeSecs;
            return this;
        }

        /**
         * Sets require_digits.
         *
         * @param requireDigits the value to send
         * @return this builder
         */
        public Builder requireDigits(Boolean requireDigits) {
            this.requireDigits = requireDigits;
            return this;
        }

        /**
         * Sets require_lowercase.
         *
         * @param requireLowercase the value to send
         * @return this builder
         */
        public Builder requireLowercase(Boolean requireLowercase) {
            this.requireLowercase = requireLowercase;
            return this;
        }

        /**
         * Sets require_symbols.
         *
         * @param requireSymbols the value to send
         * @return this builder
         */
        public Builder requireSymbols(Boolean requireSymbols) {
            this.requireSymbols = requireSymbols;
            return this;
        }

        /**
         * Sets require_uppercase.
         *
         * @param requireUppercase the value to send
         * @return this builder
         */
        public Builder requireUppercase(Boolean requireUppercase) {
            this.requireUppercase = requireUppercase;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a TenantSettingsOverride carrying exactly the fields that were set
         */
        public TenantSettingsOverride build() {
            return new TenantSettingsOverride(accessTokenLifetimeSecs, adminNotificationsEnabled, defaultCertValidityDays, deletionGracePeriodDays, emailVerificationGracePeriodHours, emailVerificationRequired, hibpCheckEnabled, lockoutBackoffMultiplier, lockoutDurationSecs, maxCertValidityDays, maxFailedLoginAttempts, maxLockoutDurationSecs, mfaChallengeLifetimeSecs, mfaEnforced, minLength, opaqueKsf, opaqueMode, opaqueSuite, passwordHistoryCount, refreshTokenLifetimeSecs, requireDigits, requireLowercase, requireSymbols, requireUppercase);
        }
    }
}
