// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

/**
 * X4 trust as returned. Same shape as the request; nothing here is secret — an operator reading a
 * provider needs to see exactly what it trusts.
 *
 * @param acceptedAudiences the server's accepted_audiences field
 * @param enabled the server's enabled field
 * @param maxLifetimeSecs the server's max_lifetime_secs field
 * @param maxTokenAgeSecs the server's max_token_age_secs field
 * @param scopeMap the server's scope_map field
 * @param subjectMapping the server's subject_mapping field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TokenExchangeTrustResponse(
        @JsonProperty("accepted_audiences") List<String> acceptedAudiences,
        @JsonProperty("enabled") Boolean enabled,
        @JsonProperty("max_lifetime_secs") @Nullable Long maxLifetimeSecs,
        @JsonProperty("max_token_age_secs") Long maxTokenAgeSecs,
        @JsonProperty("scope_map") JsonNode scopeMap,
        @JsonProperty("subject_mapping") String subjectMapping
) {
}
