// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token lifetime configuration.
 *
 * @param accessTokenLifetimeSecs the server's access_token_lifetime_secs field
 * @param refreshTokenLifetimeSecs the server's refresh_token_lifetime_secs field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TokenPolicy(
        @JsonProperty("access_token_lifetime_secs") Long accessTokenLifetimeSecs,
        @JsonProperty("refresh_token_lifetime_secs") Long refreshTokenLifetimeSecs
) {
}
