// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

/**
 * X4 trust for exchanging this provider's tokens (RFC 8693, external issuer).
 *
 * <p>Mirrors [{@code TokenExchangeTrust}] on the wire rather than reusing it directly so the API
 * surface can carry its own defaults: an admin PUTting a partial block gets the documented default
 * for anything they omitted, instead of a deserialization error listing fields they have never
 * heard of.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param acceptedAudiences Audiences an incoming subject token may name. Required (non-empty) when
 *     {@code enabled}; there is deliberately no accept-all value.
 * @param enabled Off unless explicitly enabled. Configuring a provider for *login* is not
 *     agreement to accept its tokens as API credentials.
 * @param maxLifetimeSecs Per-provider ceiling on the issued AXIAM token's lifetime.
 * @param maxTokenAgeSecs Bound on {@code now - iat}, independent of the token's own {@code exp}.
 * @param scopeMap External asserted value -&gt; AXIAM scopes. Deny-by-default: an external value
 *     with no entry contributes nothing.
 * @param subjectMapping {@code linked_only} (default) or {@code jit_provision}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record TokenExchangeTrustRequest(
        @JsonProperty("accepted_audiences") @Nullable List<String> acceptedAudiences,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("max_lifetime_secs") @Nullable Long maxLifetimeSecs,
        @JsonProperty("max_token_age_secs") @Nullable Long maxTokenAgeSecs,
        @JsonProperty("scope_map") @Nullable JsonNode scopeMap,
        @JsonProperty("subject_mapping") @Nullable String subjectMapping
) {

    /**
     * Starts a TokenExchangeTrustRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh TokenExchangeTrustRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse TokenExchangeTrustRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable List<String> acceptedAudiences;
        private @Nullable Boolean enabled;
        private @Nullable Long maxLifetimeSecs;
        private @Nullable Long maxTokenAgeSecs;
        private @Nullable JsonNode scopeMap;
        private @Nullable String subjectMapping;

        /**
         * Sets accepted_audiences.
         *
         * @param acceptedAudiences the value to send
         * @return this builder
         */
        public Builder acceptedAudiences(List<String> acceptedAudiences) {
            this.acceptedAudiences = acceptedAudiences;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets max_lifetime_secs.
         *
         * @param maxLifetimeSecs the value to send
         * @return this builder
         */
        public Builder maxLifetimeSecs(Long maxLifetimeSecs) {
            this.maxLifetimeSecs = maxLifetimeSecs;
            return this;
        }

        /**
         * Sets max_token_age_secs.
         *
         * @param maxTokenAgeSecs the value to send
         * @return this builder
         */
        public Builder maxTokenAgeSecs(Long maxTokenAgeSecs) {
            this.maxTokenAgeSecs = maxTokenAgeSecs;
            return this;
        }

        /**
         * Sets scope_map.
         *
         * @param scopeMap the value to send
         * @return this builder
         */
        public Builder scopeMap(JsonNode scopeMap) {
            this.scopeMap = scopeMap;
            return this;
        }

        /**
         * Sets subject_mapping.
         *
         * @param subjectMapping the value to send
         * @return this builder
         */
        public Builder subjectMapping(String subjectMapping) {
            this.subjectMapping = subjectMapping;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a TokenExchangeTrustRequest carrying exactly the fields that were set
         */
        public TokenExchangeTrustRequest build() {
            return new TokenExchangeTrustRequest(acceptedAudiences, enabled, maxLifetimeSecs, maxTokenAgeSecs, scopeMap, subjectMapping);
        }
    }
}
