// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import io.axiam.sdk.Sensitive;

/**
 * The UpdateFederationConfigRequest schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param allowTenantInheritance Whether tenants may inherit this organization-level provider.
 * @param allowedAlgorithms Accepted signature algorithms (CQ-B40/REQ-14 AC-5).
 * @param allowedIssuerTenants Accepted external IdP tenants for a templated issuer. Replaced
 *     wholesale.
 * @param appleKeyId Apple Key ID. {@code Some(None)} clears it.
 * @param appleTeamId Apple Team ID. {@code Some(None)} clears it.
 * @param attributeMap the server's attribute_map field
 * @param authorizationEndpoint OAuth2-variant authorization endpoint. {@code Some(None)} clears
 *     it.
 * @param buttonIcon Sign-in-button icon for a generic provider. {@code Some(None)} clears it.
 * @param clientId the server's client_id field
 * @param clientSecret the server's client_secret field -- SECRET: redacted from toString and from
 *     every JSON rendering except the one request body it is sent in
 * @param enabled the server's enabled field
 * @param idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML assertions
 *     (CQ-B40/REQ-14 AC-5). {@code Some(None)} clears the stored cert.
 * @param metadataUrl the server's metadata_url field
 * @param provider the server's provider field
 * @param providerSlug Operator-chosen identifier for a {@code generic_*} kind. {@code Some(None)}
 *     clears it.
 * @param requirePkce Send PKCE on the authorization request.
 * @param scopes Scopes to request. Replaced wholesale; empty restores the per-kind default.
 * @param tokenEndpoint OAuth2-variant token endpoint. {@code Some(None)} clears it.
 * @param tokenExchange the server's token_exchange field
 * @param userinfoEndpoint OAuth2-variant userinfo endpoint. {@code Some(None)} clears it.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateFederationConfigRequest(
        @JsonProperty("allow_tenant_inheritance") @Nullable Boolean allowTenantInheritance,
        @JsonProperty("allowed_algorithms") @Nullable List<String> allowedAlgorithms,
        @JsonProperty("allowed_issuer_tenants") @Nullable List<String> allowedIssuerTenants,
        @JsonProperty("apple_key_id") @Nullable String appleKeyId,
        @JsonProperty("apple_team_id") @Nullable String appleTeamId,
        @JsonProperty("attribute_map") @Nullable JsonNode attributeMap,
        @JsonProperty("authorization_endpoint") @Nullable String authorizationEndpoint,
        @JsonProperty("button_icon") @Nullable String buttonIcon,
        @JsonProperty("client_id") @Nullable String clientId,
        @JsonProperty("client_secret") @Nullable Sensitive clientSecret,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("idp_signing_cert_pem") @Nullable String idpSigningCertPem,
        @JsonProperty("metadata_url") @Nullable String metadataUrl,
        @JsonProperty("provider") @Nullable String provider,
        @JsonProperty("provider_slug") @Nullable String providerSlug,
        @JsonProperty("require_pkce") @Nullable Boolean requirePkce,
        @JsonProperty("scopes") @Nullable List<String> scopes,
        @JsonProperty("token_endpoint") @Nullable String tokenEndpoint,
        @JsonProperty("token_exchange") @Nullable TokenExchangeTrustRequest tokenExchange,
        @JsonProperty("userinfo_endpoint") @Nullable String userinfoEndpoint
) {

    /**
     * Starts a UpdateFederationConfigRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateFederationConfigRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateFederationConfigRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable Boolean allowTenantInheritance;
        private @Nullable List<String> allowedAlgorithms;
        private @Nullable List<String> allowedIssuerTenants;
        private @Nullable String appleKeyId;
        private @Nullable String appleTeamId;
        private @Nullable JsonNode attributeMap;
        private @Nullable String authorizationEndpoint;
        private @Nullable String buttonIcon;
        private @Nullable String clientId;
        private @Nullable Sensitive clientSecret;
        private @Nullable Boolean enabled;
        private @Nullable String idpSigningCertPem;
        private @Nullable String metadataUrl;
        private @Nullable String provider;
        private @Nullable String providerSlug;
        private @Nullable Boolean requirePkce;
        private @Nullable List<String> scopes;
        private @Nullable String tokenEndpoint;
        private @Nullable TokenExchangeTrustRequest tokenExchange;
        private @Nullable String userinfoEndpoint;

        /**
         * Sets allow_tenant_inheritance.
         *
         * @param allowTenantInheritance the value to send
         * @return this builder
         */
        public Builder allowTenantInheritance(Boolean allowTenantInheritance) {
            this.allowTenantInheritance = allowTenantInheritance;
            return this;
        }

        /**
         * Sets allowed_algorithms.
         *
         * @param allowedAlgorithms the value to send
         * @return this builder
         */
        public Builder allowedAlgorithms(List<String> allowedAlgorithms) {
            this.allowedAlgorithms = allowedAlgorithms;
            return this;
        }

        /**
         * Sets allowed_issuer_tenants.
         *
         * @param allowedIssuerTenants the value to send
         * @return this builder
         */
        public Builder allowedIssuerTenants(List<String> allowedIssuerTenants) {
            this.allowedIssuerTenants = allowedIssuerTenants;
            return this;
        }

        /**
         * Sets apple_key_id.
         *
         * @param appleKeyId the value to send
         * @return this builder
         */
        public Builder appleKeyId(String appleKeyId) {
            this.appleKeyId = appleKeyId;
            return this;
        }

        /**
         * Sets apple_team_id.
         *
         * @param appleTeamId the value to send
         * @return this builder
         */
        public Builder appleTeamId(String appleTeamId) {
            this.appleTeamId = appleTeamId;
            return this;
        }

        /**
         * Sets attribute_map.
         *
         * @param attributeMap the value to send
         * @return this builder
         */
        public Builder attributeMap(JsonNode attributeMap) {
            this.attributeMap = attributeMap;
            return this;
        }

        /**
         * Sets authorization_endpoint.
         *
         * @param authorizationEndpoint the value to send
         * @return this builder
         */
        public Builder authorizationEndpoint(String authorizationEndpoint) {
            this.authorizationEndpoint = authorizationEndpoint;
            return this;
        }

        /**
         * Sets button_icon.
         *
         * @param buttonIcon the value to send
         * @return this builder
         */
        public Builder buttonIcon(String buttonIcon) {
            this.buttonIcon = buttonIcon;
            return this;
        }

        /**
         * Sets client_id.
         *
         * @param clientId the value to send
         * @return this builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Sets client_secret.
         *
         * @param clientSecret the value to send
         * @return this builder
         */
        public Builder clientSecret(Sensitive clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets idp_signing_cert_pem.
         *
         * @param idpSigningCertPem the value to send
         * @return this builder
         */
        public Builder idpSigningCertPem(String idpSigningCertPem) {
            this.idpSigningCertPem = idpSigningCertPem;
            return this;
        }

        /**
         * Sets metadata_url.
         *
         * @param metadataUrl the value to send
         * @return this builder
         */
        public Builder metadataUrl(String metadataUrl) {
            this.metadataUrl = metadataUrl;
            return this;
        }

        /**
         * Sets provider.
         *
         * @param provider the value to send
         * @return this builder
         */
        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }

        /**
         * Sets provider_slug.
         *
         * @param providerSlug the value to send
         * @return this builder
         */
        public Builder providerSlug(String providerSlug) {
            this.providerSlug = providerSlug;
            return this;
        }

        /**
         * Sets require_pkce.
         *
         * @param requirePkce the value to send
         * @return this builder
         */
        public Builder requirePkce(Boolean requirePkce) {
            this.requirePkce = requirePkce;
            return this;
        }

        /**
         * Sets scopes.
         *
         * @param scopes the value to send
         * @return this builder
         */
        public Builder scopes(List<String> scopes) {
            this.scopes = scopes;
            return this;
        }

        /**
         * Sets token_endpoint.
         *
         * @param tokenEndpoint the value to send
         * @return this builder
         */
        public Builder tokenEndpoint(String tokenEndpoint) {
            this.tokenEndpoint = tokenEndpoint;
            return this;
        }

        /**
         * Sets token_exchange.
         *
         * @param tokenExchange the value to send
         * @return this builder
         */
        public Builder tokenExchange(TokenExchangeTrustRequest tokenExchange) {
            this.tokenExchange = tokenExchange;
            return this;
        }

        /**
         * Sets userinfo_endpoint.
         *
         * @param userinfoEndpoint the value to send
         * @return this builder
         */
        public Builder userinfoEndpoint(String userinfoEndpoint) {
            this.userinfoEndpoint = userinfoEndpoint;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateFederationConfigRequest carrying exactly the fields that were set
         */
        public UpdateFederationConfigRequest build() {
            return new UpdateFederationConfigRequest(allowTenantInheritance, allowedAlgorithms, allowedIssuerTenants, appleKeyId, appleTeamId, attributeMap, authorizationEndpoint, buttonIcon, clientId, clientSecret, enabled, idpSigningCertPem, metadataUrl, provider, providerSlug, requirePkce, scopes, tokenEndpoint, tokenExchange, userinfoEndpoint);
        }
    }
}
