// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import io.axiam.sdk.Sensitive;
import io.axiam.sdk.management.JsonNullable;

/**
 * The UpdateFederationConfigRequest schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call full of nulls is not something a reader can check.
 *
 * @param allowSha1Signatures SAML only: accept IdP responses signed with SHA-1. Refused on a
 *     non-SAML config; turning it on is audited ({@code federation.sha1_signatures_allowed}).
 * @param allowTenantInheritance Whether tenants may inherit this organization-level provider.
 * @param allowedAlgorithms Accepted signature algorithms (CQ-B40/REQ-14 AC-5).
 * @param allowedIssuerTenants Accepted external IdP tenants for a templated issuer. Replaced
 *     wholesale.
 * @param appleKeyId Apple Key ID. Explicit {@code null} clears it. -- null is NOT absent here
 *     (§27.4 rule 5): a Java null means the member is absent, JsonNullable.ofNull() means it is JSON
 *     null
 * @param appleTeamId Apple Team ID. Explicit {@code null} clears it. -- null is NOT absent here
 *     (§27.4 rule 5): a Java null means the member is absent, JsonNullable.ofNull() means it is JSON
 *     null
 * @param attributeMap the server's attribute_map field
 * @param authorizationEndpoint OAuth2-variant authorization endpoint. Explicit {@code null} clears
 *     it. -- null is NOT absent here (§27.4 rule 5): a Java null means the member is absent,
 *     JsonNullable.ofNull() means it is JSON null
 * @param buttonIcon Sign-in-button icon for a generic provider. Explicit {@code null} clears it.
 *     -- null is NOT absent here (§27.4 rule 5): a Java null means the member is absent,
 *     JsonNullable.ofNull() means it is JSON null
 * @param clientId the server's client_id field
 * @param clientSecret the server's client_secret field -- SECRET: redacted from toString and from
 *     every JSON rendering except the one request body it is sent in
 * @param enabled the server's enabled field
 * @param idpMetadataSigningCertPem SAML only: the IdP metadata signing certificate (#530).
 *     Explicit {@code null} clears it; omitted leaves it. Clearing it is audited ({@code
 *     federation.metadata_signing_cert_cleared}), and so is replacing it with a different certificate
 *     ({@code federation.metadata_signing_cert_changed}). -- null is NOT absent here (§27.4 rule 5): a
 *     Java null means the member is absent, JsonNullable.ofNull() means it is JSON null
 * @param idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML assertions
 *     (CQ-B40/REQ-14 AC-5). Explicit {@code null} clears the stored cert; omitted leaves it. -- null
 *     is NOT absent here (§27.4 rule 5): a Java null means the member is absent, JsonNullable.ofNull()
 *     means it is JSON null
 * @param metadataUrl OIDC discovery or SAML metadata URL. Explicit {@code null} clears it; omitted
 *     leaves it. -- null is NOT absent here (§27.4 rule 5): a Java null means the member is absent,
 *     JsonNullable.ofNull() means it is JSON null
 * @param provider the server's provider field
 * @param providerSlug Operator-chosen identifier for a {@code generic_*} kind. Explicit {@code
 *     null} clears it. -- null is NOT absent here (§27.4 rule 5): a Java null means the member is
 *     absent, JsonNullable.ofNull() means it is JSON null
 * @param requirePkce Send PKCE on the authorization request.
 * @param scopes Scopes to request. Replaced wholesale; empty restores the per-kind default.
 * @param tokenEndpoint OAuth2-variant token endpoint. Explicit {@code null} clears it. -- null is
 *     NOT absent here (§27.4 rule 5): a Java null means the member is absent, JsonNullable.ofNull()
 *     means it is JSON null
 * @param tokenExchange the server's token_exchange field
 * @param userinfoEndpoint OAuth2-variant userinfo endpoint. Explicit {@code null} clears it. --
 *     null is NOT absent here (§27.4 rule 5): a Java null means the member is absent,
 *     JsonNullable.ofNull() means it is JSON null
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateFederationConfigRequest(
        @JsonProperty("allow_sha1_signatures") @Nullable Boolean allowSha1Signatures,
        @JsonProperty("allow_tenant_inheritance") @Nullable Boolean allowTenantInheritance,
        @JsonProperty("allowed_algorithms") @Nullable List<String> allowedAlgorithms,
        @JsonProperty("allowed_issuer_tenants") @Nullable List<String> allowedIssuerTenants,
        @JsonProperty("apple_key_id") @Nullable JsonNullable<String> appleKeyId,
        @JsonProperty("apple_team_id") @Nullable JsonNullable<String> appleTeamId,
        @JsonProperty("attribute_map") @Nullable JsonNode attributeMap,
        @JsonProperty("authorization_endpoint") @Nullable JsonNullable<String> authorizationEndpoint,
        @JsonProperty("button_icon") @Nullable JsonNullable<String> buttonIcon,
        @JsonProperty("client_id") @Nullable String clientId,
        @JsonProperty("client_secret") @Nullable Sensitive clientSecret,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("idp_metadata_signing_cert_pem") @Nullable JsonNullable<String> idpMetadataSigningCertPem,
        @JsonProperty("idp_signing_cert_pem") @Nullable JsonNullable<String> idpSigningCertPem,
        @JsonProperty("metadata_url") @Nullable JsonNullable<String> metadataUrl,
        @JsonProperty("provider") @Nullable String provider,
        @JsonProperty("provider_slug") @Nullable JsonNullable<String> providerSlug,
        @JsonProperty("require_pkce") @Nullable Boolean requirePkce,
        @JsonProperty("scopes") @Nullable List<String> scopes,
        @JsonProperty("token_endpoint") @Nullable JsonNullable<String> tokenEndpoint,
        @JsonProperty("token_exchange") @Nullable TokenExchangeTrustRequest tokenExchange,
        @JsonProperty("userinfo_endpoint") @Nullable JsonNullable<String> userinfoEndpoint
) {

    /**
     * Starts a UpdateFederationConfigRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateFederationConfigRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateFederationConfigRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable Boolean allowSha1Signatures;
        private @Nullable Boolean allowTenantInheritance;
        private @Nullable List<String> allowedAlgorithms;
        private @Nullable List<String> allowedIssuerTenants;
        private @Nullable JsonNullable<String> appleKeyId;
        private @Nullable JsonNullable<String> appleTeamId;
        private @Nullable JsonNode attributeMap;
        private @Nullable JsonNullable<String> authorizationEndpoint;
        private @Nullable JsonNullable<String> buttonIcon;
        private @Nullable String clientId;
        private @Nullable Sensitive clientSecret;
        private @Nullable Boolean enabled;
        private @Nullable JsonNullable<String> idpMetadataSigningCertPem;
        private @Nullable JsonNullable<String> idpSigningCertPem;
        private @Nullable JsonNullable<String> metadataUrl;
        private @Nullable String provider;
        private @Nullable JsonNullable<String> providerSlug;
        private @Nullable Boolean requirePkce;
        private @Nullable List<String> scopes;
        private @Nullable JsonNullable<String> tokenEndpoint;
        private @Nullable TokenExchangeTrustRequest tokenExchange;
        private @Nullable JsonNullable<String> userinfoEndpoint;

        /**
         * Sets allow_sha1_signatures.
         *
         * @param allowSha1Signatures the value to send
         * @return this builder
         */
        public Builder allowSha1Signatures(Boolean allowSha1Signatures) {
            this.allowSha1Signatures = allowSha1Signatures;
            return this;
        }

        /**
         * Sets allow_tenant_inheritance.
         *
         * @param allowTenantInheritance the value to send
         * @return this builder
         */
        public Builder allowTenantInheritance(Boolean allowTenantInheritance) {
            this.allowTenantInheritance = allowTenantInheritance;
            return this;
        }

        /**
         * Sets allowed_algorithms.
         *
         * @param allowedAlgorithms the value to send
         * @return this builder
         */
        public Builder allowedAlgorithms(List<String> allowedAlgorithms) {
            this.allowedAlgorithms = allowedAlgorithms;
            return this;
        }

        /**
         * Sets allowed_issuer_tenants.
         *
         * @param allowedIssuerTenants the value to send
         * @return this builder
         */
        public Builder allowedIssuerTenants(List<String> allowedIssuerTenants) {
            this.allowedIssuerTenants = allowedIssuerTenants;
            return this;
        }

        /**
         * Sets apple_key_id, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param appleKeyId the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder appleKeyId(@Nullable String appleKeyId) {
            this.appleKeyId = JsonNullable.of(appleKeyId);
            return this;
        }

        /**
         * Sets apple_team_id, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param appleTeamId the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder appleTeamId(@Nullable String appleTeamId) {
            this.appleTeamId = JsonNullable.of(appleTeamId);
            return this;
        }

        /**
         * Sets attribute_map.
         *
         * @param attributeMap the value to send
         * @return this builder
         */
        public Builder attributeMap(JsonNode attributeMap) {
            this.attributeMap = attributeMap;
            return this;
        }

        /**
         * Sets authorization_endpoint, where null is a value: {@code null} here sends JSON null,
         * which clears the stored value (§27.4 rule 5). Not calling this leaves the member absent,
         * which keeps it.
         *
         * @param authorizationEndpoint the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder authorizationEndpoint(@Nullable String authorizationEndpoint) {
            this.authorizationEndpoint = JsonNullable.of(authorizationEndpoint);
            return this;
        }

        /**
         * Sets button_icon, where null is a value: {@code null} here sends JSON null, which clears
         * the stored value (§27.4 rule 5). Not calling this leaves the member absent, which keeps
         * it.
         *
         * @param buttonIcon the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder buttonIcon(@Nullable String buttonIcon) {
            this.buttonIcon = JsonNullable.of(buttonIcon);
            return this;
        }

        /**
         * Sets client_id.
         *
         * @param clientId the value to send
         * @return this builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Sets client_secret.
         *
         * @param clientSecret the value to send
         * @return this builder
         */
        public Builder clientSecret(Sensitive clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets idp_metadata_signing_cert_pem, where null is a value: {@code null} here sends JSON
         * null, which clears the stored value (§27.4 rule 5). Not calling this leaves the member
         * absent, which keeps it.
         *
         * @param idpMetadataSigningCertPem the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder idpMetadataSigningCertPem(@Nullable String idpMetadataSigningCertPem) {
            this.idpMetadataSigningCertPem = JsonNullable.of(idpMetadataSigningCertPem);
            return this;
        }

        /**
         * Sets idp_signing_cert_pem, where null is a value: {@code null} here sends JSON null,
         * which clears the stored value (§27.4 rule 5). Not calling this leaves the member absent,
         * which keeps it.
         *
         * @param idpSigningCertPem the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder idpSigningCertPem(@Nullable String idpSigningCertPem) {
            this.idpSigningCertPem = JsonNullable.of(idpSigningCertPem);
            return this;
        }

        /**
         * Sets metadata_url, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param metadataUrl the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder metadataUrl(@Nullable String metadataUrl) {
            this.metadataUrl = JsonNullable.of(metadataUrl);
            return this;
        }

        /**
         * Sets provider.
         *
         * @param provider the value to send
         * @return this builder
         */
        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }

        /**
         * Sets provider_slug, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param providerSlug the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder providerSlug(@Nullable String providerSlug) {
            this.providerSlug = JsonNullable.of(providerSlug);
            return this;
        }

        /**
         * Sets require_pkce.
         *
         * @param requirePkce the value to send
         * @return this builder
         */
        public Builder requirePkce(Boolean requirePkce) {
            this.requirePkce = requirePkce;
            return this;
        }

        /**
         * Sets scopes.
         *
         * @param scopes the value to send
         * @return this builder
         */
        public Builder scopes(List<String> scopes) {
            this.scopes = scopes;
            return this;
        }

        /**
         * Sets token_endpoint, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param tokenEndpoint the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder tokenEndpoint(@Nullable String tokenEndpoint) {
            this.tokenEndpoint = JsonNullable.of(tokenEndpoint);
            return this;
        }

        /**
         * Sets token_exchange.
         *
         * @param tokenExchange the value to send
         * @return this builder
         */
        public Builder tokenExchange(TokenExchangeTrustRequest tokenExchange) {
            this.tokenExchange = tokenExchange;
            return this;
        }

        /**
         * Sets userinfo_endpoint, where null is a value: {@code null} here sends JSON null, which
         * clears the stored value (§27.4 rule 5). Not calling this leaves the member absent, which
         * keeps it.
         *
         * @param userinfoEndpoint the value to send, or null to send JSON null
         * @return this builder
         */
        public Builder userinfoEndpoint(@Nullable String userinfoEndpoint) {
            this.userinfoEndpoint = JsonNullable.of(userinfoEndpoint);
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateFederationConfigRequest carrying exactly the fields that were set
         */
        public UpdateFederationConfigRequest build() {
            return new UpdateFederationConfigRequest(allowSha1Signatures, allowTenantInheritance, allowedAlgorithms, allowedIssuerTenants, appleKeyId, appleTeamId, attributeMap, authorizationEndpoint, buttonIcon, clientId, clientSecret, enabled, idpMetadataSigningCertPem, idpSigningCertPem, metadataUrl, provider, providerSlug, requirePkce, scopes, tokenEndpoint, tokenExchange, userinfoEndpoint);
        }
    }
}
