// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * The UpdateRole schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param description the server's description field
 * @param isGlobal the server's is_global field
 * @param name the server's name field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateRole(
        @JsonProperty("description") @Nullable String description,
        @JsonProperty("is_global") @Nullable Boolean isGlobal,
        @JsonProperty("name") @Nullable String name
) {

    /**
     * Starts a UpdateRole with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateRole.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateRole.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable String description;
        private @Nullable Boolean isGlobal;
        private @Nullable String name;

        /**
         * Sets description.
         *
         * @param description the value to send
         * @return this builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets is_global.
         *
         * @param isGlobal the value to send
         * @return this builder
         */
        public Builder isGlobal(Boolean isGlobal) {
            this.isGlobal = isGlobal;
            return this;
        }

        /**
         * Sets name.
         *
         * @param name the value to send
         * @return this builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateRole carrying exactly the fields that were set
         */
        public UpdateRole build() {
            return new UpdateRole(description, isGlobal, name);
        }
    }
}
