// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;

/**
 * The UpdateNotificationRuleRequest schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param description the server's description field
 * @param enabled the server's enabled field
 * @param events the server's events field
 * @param name the server's name field
 * @param recipientEmails the server's recipient_emails field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateNotificationRuleRequest(
        @JsonProperty("description") @Nullable String description,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("events") @Nullable List<NotificationEventType> events,
        @JsonProperty("name") @Nullable String name,
        @JsonProperty("recipient_emails") @Nullable List<String> recipientEmails
) {

    /**
     * Starts a UpdateNotificationRuleRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateNotificationRuleRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateNotificationRuleRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable String description;
        private @Nullable Boolean enabled;
        private @Nullable List<NotificationEventType> events;
        private @Nullable String name;
        private @Nullable List<String> recipientEmails;

        /**
         * Sets description.
         *
         * @param description the value to send
         * @return this builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets events.
         *
         * @param events the value to send
         * @return this builder
         */
        public Builder events(List<NotificationEventType> events) {
            this.events = events;
            return this;
        }

        /**
         * Sets name.
         *
         * @param name the value to send
         * @return this builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Sets recipient_emails.
         *
         * @param recipientEmails the value to send
         * @return this builder
         */
        public Builder recipientEmails(List<String> recipientEmails) {
            this.recipientEmails = recipientEmails;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateNotificationRuleRequest carrying exactly the fields that were set
         */
        public UpdateNotificationRuleRequest build() {
            return new UpdateNotificationRuleRequest(description, enabled, events, name, recipientEmails);
        }
    }
}
