// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;
import io.axiam.sdk.Sensitive;

/**
 * The UpdateFederationConfigRequest schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param allowedAlgorithms Accepted signature algorithms (CQ-B40/REQ-14 AC-5).
 * @param attributeMap the server's attribute_map field
 * @param clientId the server's client_id field
 * @param clientSecret the server's client_secret field -- SECRET: redacted from toString and from
 *     every JSON rendering except the one request body it is sent in
 * @param enabled the server's enabled field
 * @param idpSigningCertPem PEM-encoded X.509 certificate for verifying SAML assertions
 *     (CQ-B40/REQ-14 AC-5). {@code Some(None)} clears the stored cert.
 * @param metadataUrl the server's metadata_url field
 * @param provider the server's provider field
 * @param tokenExchange the server's token_exchange field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateFederationConfigRequest(
        @JsonProperty("allowed_algorithms") @Nullable List<String> allowedAlgorithms,
        @JsonProperty("attribute_map") @Nullable JsonNode attributeMap,
        @JsonProperty("client_id") @Nullable String clientId,
        @JsonProperty("client_secret") @Nullable Sensitive clientSecret,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("idp_signing_cert_pem") @Nullable String idpSigningCertPem,
        @JsonProperty("metadata_url") @Nullable String metadataUrl,
        @JsonProperty("provider") @Nullable String provider,
        @JsonProperty("token_exchange") @Nullable TokenExchangeTrustRequest tokenExchange
) {

    /**
     * Starts a UpdateFederationConfigRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateFederationConfigRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateFederationConfigRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable List<String> allowedAlgorithms;
        private @Nullable JsonNode attributeMap;
        private @Nullable String clientId;
        private @Nullable Sensitive clientSecret;
        private @Nullable Boolean enabled;
        private @Nullable String idpSigningCertPem;
        private @Nullable String metadataUrl;
        private @Nullable String provider;
        private @Nullable TokenExchangeTrustRequest tokenExchange;

        /**
         * Sets allowed_algorithms.
         *
         * @param allowedAlgorithms the value to send
         * @return this builder
         */
        public Builder allowedAlgorithms(List<String> allowedAlgorithms) {
            this.allowedAlgorithms = allowedAlgorithms;
            return this;
        }

        /**
         * Sets attribute_map.
         *
         * @param attributeMap the value to send
         * @return this builder
         */
        public Builder attributeMap(JsonNode attributeMap) {
            this.attributeMap = attributeMap;
            return this;
        }

        /**
         * Sets client_id.
         *
         * @param clientId the value to send
         * @return this builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Sets client_secret.
         *
         * @param clientSecret the value to send
         * @return this builder
         */
        public Builder clientSecret(Sensitive clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets idp_signing_cert_pem.
         *
         * @param idpSigningCertPem the value to send
         * @return this builder
         */
        public Builder idpSigningCertPem(String idpSigningCertPem) {
            this.idpSigningCertPem = idpSigningCertPem;
            return this;
        }

        /**
         * Sets metadata_url.
         *
         * @param metadataUrl the value to send
         * @return this builder
         */
        public Builder metadataUrl(String metadataUrl) {
            this.metadataUrl = metadataUrl;
            return this;
        }

        /**
         * Sets provider.
         *
         * @param provider the value to send
         * @return this builder
         */
        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }

        /**
         * Sets token_exchange.
         *
         * @param tokenExchange the value to send
         * @return this builder
         */
        public Builder tokenExchange(TokenExchangeTrustRequest tokenExchange) {
            this.tokenExchange = tokenExchange;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateFederationConfigRequest carrying exactly the fields that were set
         */
        public UpdateFederationConfigRequest build() {
            return new UpdateFederationConfigRequest(allowedAlgorithms, attributeMap, clientId, clientSecret, enabled, idpSigningCertPem, metadataUrl, provider, tokenExchange);
        }
    }
}
