// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

import java.util.List;

/**
 * The UpdateReactorRequest schema from the server's OpenAPI document.
 *
 * <p>Every component is optional, so this is a SPARSE body: what you leave null is left unchanged,
 * and is omitted from the wire request entirely rather than sent as null (§27.4 rule 5). Use the
 * builder — a canonical constructor call with six nulls in it is not something a reader can check.
 *
 * @param description the server's description field
 * @param enabled the server's enabled field
 * @param events the server's events field
 * @param failurePolicy the server's failure_policy field
 * @param mode the server's mode field
 * @param name the server's name field
 * @param priority the server's priority field
 * @param timeoutMs the server's timeout_ms field
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UpdateReactorRequest(
        @JsonProperty("description") @Nullable String description,
        @JsonProperty("enabled") @Nullable Boolean enabled,
        @JsonProperty("events") @Nullable List<String> events,
        @JsonProperty("failure_policy") @Nullable FailurePolicy failurePolicy,
        @JsonProperty("mode") @Nullable ReactorMode mode,
        @JsonProperty("name") @Nullable String name,
        @JsonProperty("priority") @Nullable Integer priority,
        @JsonProperty("timeout_ms") @Nullable Integer timeoutMs
) {

    /**
     * Starts a UpdateReactorRequest with nothing set.
     *
     * <p>Every field left unset is omitted from the wire body entirely, so a builder that sets one
     * field changes one field (§27.4 rule 5).
     *
     * @return a fresh UpdateReactorRequest.Builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builds a sparse UpdateReactorRequest.
     *
     * <p>What you do not set is not sent — not sent as null, absent from the body altogether.
     */
    public static final class Builder {

        /** Starts with every field unset. */
        private Builder() {
        }

        private @Nullable String description;
        private @Nullable Boolean enabled;
        private @Nullable List<String> events;
        private @Nullable FailurePolicy failurePolicy;
        private @Nullable ReactorMode mode;
        private @Nullable String name;
        private @Nullable Integer priority;
        private @Nullable Integer timeoutMs;

        /**
         * Sets description.
         *
         * @param description the value to send
         * @return this builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets enabled.
         *
         * @param enabled the value to send
         * @return this builder
         */
        public Builder enabled(Boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * Sets events.
         *
         * @param events the value to send
         * @return this builder
         */
        public Builder events(List<String> events) {
            this.events = events;
            return this;
        }

        /**
         * Sets failure_policy.
         *
         * @param failurePolicy the value to send
         * @return this builder
         */
        public Builder failurePolicy(FailurePolicy failurePolicy) {
            this.failurePolicy = failurePolicy;
            return this;
        }

        /**
         * Sets mode.
         *
         * @param mode the value to send
         * @return this builder
         */
        public Builder mode(ReactorMode mode) {
            this.mode = mode;
            return this;
        }

        /**
         * Sets name.
         *
         * @param name the value to send
         * @return this builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Sets priority.
         *
         * @param priority the value to send
         * @return this builder
         */
        public Builder priority(Integer priority) {
            this.priority = priority;
            return this;
        }

        /**
         * Sets timeout_ms.
         *
         * @param timeoutMs the value to send
         * @return this builder
         */
        public Builder timeoutMs(Integer timeoutMs) {
            this.timeoutMs = timeoutMs;
            return this;
        }

        /**
         * Builds the body.
         *
         * @return a UpdateReactorRequest carrying exactly the fields that were set
         */
        public UpdateReactorRequest build() {
            return new UpdateReactorRequest(description, enabled, events, failurePolicy, mode, name, priority, timeoutMs);
        }
    }
}
