// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;

/**
 * Which directory attribute feeds each AXIAM user field.
 *
 * @param displayName The attribute holding the human-readable name.
 * @param email The attribute holding the e-mail address.
 * @param externalId The attribute holding the immutable entry identifier ({@code entryUUID},
 *     {@code objectGUID}).
 * @param username The attribute holding the login name ({@code uid}, {@code sAMAccountName}).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record UserAttributeMap(
        @JsonProperty("display_name") String displayName,
        @JsonProperty("email") String email,
        @JsonProperty("external_id") String externalId,
        @JsonProperty("username") String username
) {
}
