// @generated by scripts/gen_management.py from management-registry.json and
// openapi.json. DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
package io.axiam.sdk.management.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * WebAuthn ceremony policy.
 *
 * <p>One field today. It is a struct rather than a bare field on [{@code SecuritySettings}] so
 * that the next WebAuthn control has an obvious home, and so the admin UI can group them.
 *
 * <p>The *attestation* policy is deliberately not here: it lives in [{@code
 * crate::models::webauthn_policy::WebauthnAttestationPolicy}], is tenant-only, and cannot join
 * this model because AAGUID allow/block lists have no "more restrictive than" ordering to validate
 * an override against. User verification does, so it can.
 *
 * @param webauthnUserVerification How hard the authenticator must prove *who* is present. Applies
 *     to enrolment and to second-factor authentication. Usernameless sign-in is held to {@code
 *     required} whatever this says — see [{@code WebauthnUserVerification}].
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public record WebauthnPolicy(
        @JsonProperty("webauthn_user_verification") String webauthnUserVerification
) {
}
