package io.axiam.sdk.ssf;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

import com.nimbusds.jose.JOSEObjectType;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.JWSObject;
import com.nimbusds.jose.Payload;
import com.nimbusds.jose.crypto.Ed25519Signer;
import com.nimbusds.jose.crypto.MACSigner;
import com.nimbusds.jose.jwk.Curve;
import com.nimbusds.jose.jwk.JWKSet;
import com.nimbusds.jose.jwk.OctetKeyPair;
import com.nimbusds.jose.jwk.gen.OctetKeyPairGenerator;

import io.axiam.sdk.AxiamClient;
import io.axiam.sdk.Sensitive;
import io.axiam.sdk.errors.AuthError;
import io.axiam.sdk.errors.NetworkError;
import io.axiam.sdk.errors.NotFoundError;
import io.axiam.sdk.errors.ValidationError;
import io.axiam.sdk.testutil.RouteServer;

import okhttp3.mockwebserver.MockResponse;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static io.axiam.sdk.testutil.RouteServer.json;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The SSF receiver helper &mdash; CONTRACT.md &sect;32.8's eight helper tests.
 *
 * <p>Every key is an Ed25519 key generated by the test, and every SET is signed
 * here: no key literal, no captured token.
 */
class SsfReceiverTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final String ISSUER = "https://iam.example.test/t/22222222-2222-4222-8222-222222222222";
    private static final String AUDIENCE = "https://rp.example.test";
    private static final Base64.Encoder B64 = Base64.getUrlEncoder().withoutPadding();

    private RouteServer server;
    private AxiamClient client;

    @BeforeEach
    void start() throws Exception {
        server = new RouteServer();
        client = AxiamClient.builder(server.base(), UUID.randomUUID().toString()).build();
    }

    @AfterEach
    void stop() throws Exception {
        client.close();
        server.close();
    }

    private static OctetKeyPair key() throws Exception {
        return new OctetKeyPairGenerator(Curve.Ed25519).keyID("k-" + UUID.randomUUID()).generate();
    }

    private static OctetKeyPair keyWithKid(String kid) throws Exception {
        return new OctetKeyPairGenerator(Curve.Ed25519).keyID(kid).generate();
    }

    private static ObjectNode claims() {
        ObjectNode c = MAPPER.createObjectNode();
        c.put("iss", ISSUER);
        c.put("aud", AUDIENCE);
        c.put("iat", 1_791_500_000L);
        c.put("jti", UUID.randomUUID().toString().replace("-", ""));
        c.put("txn", "t-1");
        ObjectNode sub = c.putObject("sub_id");
        sub.put("format", "iss_sub");
        sub.put("iss", ISSUER);
        sub.put("sub", UUID.randomUUID().toString());
        c.putObject("events").putObject(SsfEventTypes.SESSION_REVOKED).put("event_timestamp", 1_791_500_000L);
        return c;
    }

    private static String sign(OctetKeyPair key, JWSHeader header, JsonNode claims) throws Exception {
        JWSObject jws = new JWSObject(header, new Payload(claims.toString()));
        jws.sign(new Ed25519Signer(key));
        return jws.serialize();
    }

    private static String signSet(OctetKeyPair key, JsonNode claims) throws Exception {
        return sign(key, new JWSHeader.Builder(JWSAlgorithm.EdDSA)
                .type(new JOSEObjectType("secevent+jwt")).keyID(key.getKeyID()).build(), claims);
    }

    private RouteServer.Route jwks(OctetKeyPair... keys) {
        List<com.nimbusds.jose.jwk.JWK> pub = new ArrayList<>();
        for (OctetKeyPair k : keys) {
            pub.add(k.toPublicJWK());
        }
        return server.on("GET", "/oauth2/jwks", json(200, new JWKSet(pub).toString()));
    }

    private SsfReceiver receiver() {
        String token = "cc-" + UUID.randomUUID();
        return new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                        SsfKeySource.jwksUri(server.base() + "/oauth2/jwks"))
                .accessTokenProvider(() -> Sensitive.of(token)).build());
    }

    private static SetFailureReason reason(SsfReceiver r, String set) {
        SetVerificationError e = assertThrows(SetVerificationError.class, () -> r.verifySet(set));
        assertInstanceOf(AuthError.class, e);
        assertEquals(e.failureReason().code(), e.reason());
        return e.failureReason();
    }

    private static ObjectNode with(ObjectNode c, String k, Object v) {
        ObjectNode copy = c.deepCopy();
        copy.set(k, MAPPER.valueToTree(v));
        return copy;
    }

    private static ObjectNode without(ObjectNode c, String k) {
        ObjectNode copy = c.deepCopy();
        copy.remove(k);
        return copy;
    }

    // ── 1 ──
    @Test
    void aSetSignedByTheJwksKeyVerifiesIntoItsClaims() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        ObjectNode c = claims();
        SsfReceiver r = receiver();
        SecurityEvent event = r.verifySet(signSet(key, c));
        assertEquals(c.path("jti").asText(), event.jti());
        assertEquals(1_791_500_000L, event.iat());
        assertEquals(ISSUER, event.iss());
        assertEquals(MAPPER.getNodeFactory().textNode(AUDIENCE), event.aud());
        assertEquals("t-1", event.txn());
        assertEquals(SsfEventTypes.SESSION_REVOKED, event.eventType());
        assertEquals(c.path("events").path(SsfEventTypes.SESSION_REVOKED).toString(), event.event().toString());
        assertEquals(c.path("sub_id"), event.subId());

        // An aud array containing the audience, the media-type spelling of typ
        // in any case, and no txn.
        ObjectNode arr = without(with(claims(), "aud", List.of("other", AUDIENCE)), "txn");
        SecurityEvent second = r.verifySet(sign(key, new JWSHeader.Builder(JWSAlgorithm.EdDSA)
                .type(new JOSEObjectType("Application/SecEvent+JWT")).keyID(key.getKeyID()).build(), arr));
        assertTrue(second.aud().isArray());
        assertNull(second.txn());
    }

    // ── 2 ──
    @Test
    void aWrongTypOrAlgIsRefusedInThatOrder() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        SsfReceiver r = receiver();
        ObjectNode c = claims();
        assertEquals(SetFailureReason.INVALID_TYPE,
                reason(r, sign(key, new JWSHeader.Builder(JWSAlgorithm.EdDSA).keyID(key.getKeyID()).build(), c)));
        assertEquals(SetFailureReason.INVALID_TYPE, reason(r, sign(key, new JWSHeader.Builder(JWSAlgorithm.EdDSA)
                .type(JOSEObjectType.JWT).keyID(key.getKeyID()).build(), c)));
        String payload = B64.encodeToString(c.toString().getBytes(StandardCharsets.UTF_8));
        String none = B64.encodeToString("{\"alg\":\"none\",\"typ\":\"secevent+jwt\"}"
                .getBytes(StandardCharsets.UTF_8)) + "." + payload + ".";
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, none));
        byte[] macKey = new byte[32];
        new SecureRandom().nextBytes(macKey);
        JWSObject hs = new JWSObject(new JWSHeader.Builder(JWSAlgorithm.HS256)
                .type(new JOSEObjectType("secevent+jwt")).keyID(key.getKeyID()).build(), new Payload(c.toString()));
        hs.sign(new MACSigner(macKey));
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, hs.serialize()));
        assertEquals(SetFailureReason.MALFORMED, reason(r, "a.b"));
        assertEquals(SetFailureReason.MALFORMED, reason(r, "!!.@@.##"));
        assertEquals(SetFailureReason.MALFORMED, reason(r, B64.encodeToString("[]".getBytes(StandardCharsets.UTF_8))
                + "." + payload + ".AA"));
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, B64.encodeToString(
                "{\"alg\":\"EdDSA\",\"typ\":\"secevent+jwt\"}".getBytes(StandardCharsets.UTF_8)) + "." + payload + ".AA"),
                "no kid");
    }

    // ── 3 ──
    @Test
    void anotherKeyOrATamperedPayloadIsInvalidKey() throws Exception {
        OctetKeyPair key = key();
        OctetKeyPair rogue = keyWithKid(key.getKeyID());
        jwks(key);
        SsfReceiver r = receiver();
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, signSet(rogue, claims())));
        String[] parts = signSet(key, claims()).split("\\.");
        parts[1] = B64.encodeToString(with(claims(), "txn", "x").toString().getBytes(StandardCharsets.UTF_8));
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, String.join(".", parts)));
    }

    // ── 4 ──
    @Test
    void anotherIssuerOrAudienceIsRefused() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        SsfReceiver r = receiver();
        assertEquals(SetFailureReason.INVALID_ISSUER,
                reason(r, signSet(key, with(claims(), "iss", "https://iam.example.test"))));
        assertEquals(SetFailureReason.INVALID_AUDIENCE,
                reason(r, signSet(key, with(claims(), "aud", List.of("https://elsewhere.test")))));
        assertEquals(SetFailureReason.INVALID_AUDIENCE, reason(r, signSet(key, with(claims(), "aud", 7))));
    }

    // ── 5 ──
    @Test
    void expSubTwoEventsOrNoJtiIsInvalidRequest() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        SsfReceiver r = receiver();
        Map<String, Object> two = new LinkedHashMap<>();
        two.put(SsfEventTypes.ACCOUNT_DISABLED, Map.of());
        two.put(SsfEventTypes.ACCOUNT_PURGED, Map.of());
        for (ObjectNode c : List.of(
                with(claims(), "exp", 1_891_500_000L),
                with(claims(), "sub", "u"),
                with(claims(), "events", two),
                without(claims(), "jti"),
                with(claims(), "jti", ""),
                without(claims(), "iat"),
                with(claims(), "iat", "yesterday"),
                without(claims(), "sub_id"))) {
            assertEquals(SetFailureReason.INVALID_REQUEST, reason(r, signSet(key, c)));
        }
    }

    // ── 6 ──
    @Test
    void aReplayIsRefusedAndAShortWindowIsRefusedAtConfiguration() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        SsfReceiver r = receiver();
        String set = signSet(key, claims());
        r.verifySet(set);
        assertEquals(SetFailureReason.REPLAYED, reason(r, set));

        ValidationError e = assertThrows(ValidationError.class, () -> SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                SsfKeySource.jwksUri(server.base() + "/oauth2/jwks")).replayWindow(Duration.ofDays(6)).build());
        assertEquals("ssf.receiver", e.operation());
        assertThrows(ValidationError.class,
                () -> SsfReceiverConfig.builder("", AUDIENCE, SsfKeySource.jwksUri("https://x")).build());
        assertThrows(ValidationError.class,
                () -> SsfReceiverConfig.builder(ISSUER, "", SsfKeySource.jwksUri("https://x")).build());
        // A custom store is used, and a longer window is accepted.
        AtomicInteger asked = new AtomicInteger();
        SsfReceiver custom = new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                        SsfKeySource.jwksUri(server.base() + "/oauth2/jwks"))
                .replayWindow(Duration.ofDays(30)).replayStore((jti, window) -> {
                    asked.incrementAndGet();
                    return true;
                }).build());
        custom.verifySet(set);
        assertEquals(1, asked.get());
    }

    @Test
    void theMemoryStoreForgetsAfterTheWindow() {
        MemoryReplayStore store = new MemoryReplayStore();
        assertTrue(store.checkAndRecord("a", Duration.ofSeconds(60)));
        assertFalse(store.checkAndRecord("a", Duration.ofSeconds(60)));
        assertTrue(store.checkAndRecord("b", Duration.ZERO));
        assertTrue(store.checkAndRecord("b", Duration.ZERO), "expired, so new again");
        assertTrue(store.checkAndRecord("c", Duration.ofSeconds(Long.MAX_VALUE)));
    }

    // ── 7 ──
    @Test
    void anUnknownKidCostsOneRefetchAndASecondOneNone() throws Exception {
        OctetKeyPair key = key();
        RouteServer.Route hits = jwks(key);
        SsfReceiver r = receiver();
        r.verifySet(signSet(key, claims()));
        assertEquals(1, hits.calls(), "primes the cache");
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, signSet(key(), claims())));
        assertEquals(2, hits.calls(), "exactly one refetch");
        assertEquals(SetFailureReason.INVALID_KEY, reason(r, signSet(key(), claims())));
        assertEquals(2, hits.calls(), "no refetch within the minute");
    }

    // ── 8 ──
    @Test
    void pollPassesAckAndSetErrsThroughAndSortsTheAnswer() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        String stream = UUID.randomUUID().toString();
        ObjectNode good = claims();
        ObjectNode bad = with(claims(), "iss", "https://impostor.test");
        ObjectNode mismatched = claims();
        ObjectNode reply = MAPPER.createObjectNode();
        ObjectNode sets = reply.putObject("sets");
        sets.put(good.path("jti").asText(), signSet(key, good));
        sets.put(bad.path("jti").asText(), signSet(key, bad));
        sets.put("not-" + mismatched.path("jti").asText(), signSet(key, mismatched));
        sets.put("numeric", 42);
        reply.put("moreAvailable", true);
        RouteServer.Route poll = server.onEach("POST", "/ssf/v1/poll/" + stream,
                i -> i == 0 ? json(200, reply.toString()) : json(200, "{\"sets\":{},\"moreAvailable\":false}"));

        SsfReceiver r = receiver();
        Map<String, SetErr> errs = new LinkedHashMap<>();
        errs.put("old-1", SetErr.fromReason(SetFailureReason.REPLAYED));
        SsfPollResult result = r.poll(stream, new SsfPollOptions(10, true, List.of("done-1", "done-2"), errs));
        assertTrue(result.moreAvailable());
        assertEquals(1, result.events().size());
        assertEquals(good.path("jti").asText(), result.events().get(0).jti());
        assertEquals(List.of(
                new RefusedSet(bad.path("jti").asText(), SetFailureReason.INVALID_ISSUER),
                new RefusedSet("not-" + mismatched.path("jti").asText(), SetFailureReason.INVALID_REQUEST),
                new RefusedSet("numeric", SetFailureReason.MALFORMED)), result.refused());

        RouteServer.Seen sent = poll.last();
        assertEquals(MAPPER.readTree("{\"maxEvents\":10,\"returnImmediately\":true,\"ack\":[\"done-1\",\"done-2\"],"
                + "\"setErrs\":{\"old-1\":{\"err\":\"invalid_request\"}}}"), MAPPER.readTree(sent.body()),
                "exactly as given, and nothing acknowledged on the caller's behalf");
        assertTrue(sent.headers().get("Authorization").startsWith("Bearer cc-"));
        assertNull(sent.headers().get("Cookie"));

        // A second poll with no options sends an empty object: still no ack.
        SsfPollResult again = r.pollAsync(stream, SsfPollOptions.none()).get();
        assertEquals("{}", poll.last().body());
        assertTrue(again.events().isEmpty() && !again.moreAvailable());
    }

    @Test
    void pollIsNotRetriedOn400ButIsOn503() {
        RouteServer.Route bad = server.on("POST", "/ssf/v1/poll/s-1",
                json(400, "{\"error\":\"invalid_request\",\"message\":\"push stream\"}"));
        ValidationError e = assertThrows(ValidationError.class, () -> receiver().poll("s-1", SsfPollOptions.none()));
        assertTrue(e.getMessage().contains("push stream"));
        assertEquals(1, bad.calls(), "a 4xx is never retried");

        RouteServer.Route down = server.on("POST", "/ssf/v1/poll/s-2", new MockResponse().setResponseCode(503));
        assertThrows(NetworkError.class, () -> receiver().poll("s-2", SsfPollOptions.none()));
        assertTrue(down.calls() > 1, "a 5xx is retried per §16");

        server.on("POST", "/ssf/v1/poll/s-3", json(404, "{\"error\":\"not_found\"}"));
        assertThrows(NotFoundError.class, () -> receiver().poll("s-3", SsfPollOptions.none()));
        server.on("POST", "/ssf/v1/poll/s-4", json(401, "{\"error_description\":\"no\"}"));
        assertThrows(AuthError.class, () -> receiver().poll("s-4", SsfPollOptions.none()));
        server.on("POST", "/ssf/v1/poll/s-5", json(403, "{}"));
        assertThrows(io.axiam.sdk.errors.AuthzError.class, () -> receiver().poll("s-5", SsfPollOptions.none()));
        server.on("POST", "/ssf/v1/poll/s-6", json(409, "not json"));
        assertThrows(io.axiam.sdk.errors.ConflictError.class, () -> receiver().poll("s-6", SsfPollOptions.none()));
        server.on("POST", "/ssf/v1/poll/a%2Fb", json(200, "{}"));
        assertTrue(receiver().poll("a/b", SsfPollOptions.none()).events().isEmpty(), "the stream id is path-escaped");
    }

    @Test
    void discoverySuppliesTheJwksUriAndMustNameTheIssuer() throws Exception {
        OctetKeyPair key = key();
        jwks(key);
        ObjectNode doc = MAPPER.createObjectNode();
        doc.put("issuer", ISSUER);
        doc.put("jwks_uri", server.base() + "/oauth2/jwks");
        server.on("GET", "/.well-known/ssf-configuration", json(200, doc.toString()));
        SsfReceiver r = new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                SsfKeySource.discoveryUrl(server.base() + "/.well-known/ssf-configuration")).build());
        r.verifySet(signSet(key, claims()));

        SsfReceiver wrong = new SsfReceiver(client, SsfReceiverConfig.builder("https://someone-else.test", AUDIENCE,
                SsfKeySource.discoveryUrl(server.base() + "/.well-known/ssf-configuration")).build());
        NetworkError e = assertThrows(NetworkError.class, () -> wrong.verifySet(signSet(key, claims())));
        assertFalse(e instanceof ValidationError);
        // A poll with no token provider is refused locally.
        assertThrows(AuthError.class, () -> wrong.poll("s", SsfPollOptions.none()));
        assertTrue(wrong.toString().startsWith("SsfReceiver["));
        assertTrue(SsfKeySource.discoveryUrl("https://d").toString().contains("discoveryUrl"));
    }

    @Test
    void aJwksFetchFailureIsANetworkErrorNotARefusal() throws Exception {
        OctetKeyPair key = key();
        server.on("GET", "/oauth2/jwks", json(500, "{}"));
        assertThrows(NetworkError.class, () -> receiver().verifySet(signSet(key, claims())));
        server.on("GET", "/oauth2/jwks", json(200, "{\"keys\":\"nope\"}"));
        assertThrows(NetworkError.class, () -> receiver().verifySet(signSet(key, claims())));
        SsfReceiver plain = new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                SsfKeySource.jwksUri("http://keys.example.test/jwks")).build());
        assertThrows(NetworkError.class, () -> plain.verifySet(signSet(key, claims())), "https is required");
        SsfReceiver garbage = new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                SsfKeySource.jwksUri("not a url")).build());
        assertThrows(NetworkError.class, () -> garbage.verifySet(signSet(key, claims())));
        server.on("GET", "/no-jwks", json(200, "{\"issuer\":\"" + ISSUER + "\"}"));
        SsfReceiver noJwks = new SsfReceiver(client, SsfReceiverConfig.builder(ISSUER, AUDIENCE,
                SsfKeySource.discoveryUrl(server.base() + "/no-jwks")).build());
        assertThrows(NetworkError.class, () -> noJwks.verifySet(signSet(key, claims())));
    }

    @Test
    void pushErrorCodesAreRfc8935Codes() {
        Map<SetFailureReason, String> expected = Map.of(
                SetFailureReason.MALFORMED, "invalid_request",
                SetFailureReason.INVALID_TYPE, "invalid_request",
                SetFailureReason.REPLAYED, "invalid_request",
                SetFailureReason.INVALID_KEY, "invalid_key",
                SetFailureReason.INVALID_ISSUER, "invalid_issuer",
                SetFailureReason.INVALID_AUDIENCE, "invalid_audience",
                SetFailureReason.INVALID_REQUEST, "invalid_request");
        expected.forEach((reason, code) -> {
            assertEquals(code, reason.pushErrorCode());
            assertEquals(code, SetErr.fromReason(reason).err());
        });
        assertEquals("replayed", SetFailureReason.REPLAYED.code());
        assertEquals(8, List.of(SsfEventTypes.SESSION_REVOKED, SsfEventTypes.CREDENTIAL_CHANGE,
                SsfEventTypes.ASSURANCE_LEVEL_CHANGE, SsfEventTypes.ACCOUNT_DISABLED, SsfEventTypes.ACCOUNT_ENABLED,
                SsfEventTypes.ACCOUNT_PURGED, SsfEventTypes.VERIFICATION, SsfEventTypes.STREAM_UPDATED).size());
    }
}
